### ISSUE TITLE
How to Create  RoleId Using AppRole Authentication

### ISSUE THREAD

**Issue by bunny1116** [rajanadar/VaultSharp#102]
Iam trying to use Approle Authentication but for that i require Role Id and Secret Id.Could you please post  screen shot  the method to Create Role id  and generate secret  id in vault(Hashicorp) so that i can able to authenticate to vault.

Appreciate your help.
Thanks,
Srinivas

**Comment by rajanadar** [comment]
@bunny1116  do you still need this?
