### ISSUE TITLE
 *Issue writing secret to name space in Hashicorp Vault(Urgent assistance Required)

### ISSUE THREAD

**Issue by SrinivasSurigi** [rajanadar/VaultSharp#103]
I have issue writing secret to namespace in Hashicorp Vault gets below error
error: Unexpected character encountered while parsing value <,path   

Can we write secret & policy to name space using vault sharp ?.Appreciate your assistance.

vsc.v1.secrets.keyvalue.v1.writesecretaysnc(fullpath,secrets,mount)

Thanks,
Srinivas

**Comment by rajanadar** [comment]
Please provide a good code snippet to repro this.
