### ISSUE TITLE
Deadlock when calling from synchronous code

### ISSUE THREAD

**Issue by Poimen** [rajanadar/VaultSharp#107]
We have attempted to use this library in a IIS Hosted .Net Framework 4.6.2 service. The service needs to setup a secondary WCF connection via a behaviour which is a synchronous call. We can't make this asynchronous.

When we make the call to vault the client hangs. Our calling code looks something like:
```c#
var appRoleAuth = new AppRoleAuthMethodInfo(roleId, secretId);
var vaultClientSettings = new VaultClientSettings("https://example.org", appRoleAuth);
vaultClientSettings.ContinueAsyncTasksOnCapturedContext = false;

var vaultClient = new VaultClient(vaultClientSettings);
var result = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("some/path/key").Result;
```

We have tracked down the potential issue (which is similar to #39):
https://github.com/rajanadar/VaultSharp/blob/eca1e53b1864aa8647af92577f716e0432d06f91/src/VaultSharp/Core/Polymath.cs#L79

As per #39, if we change this to:
```c#
headers.Add(VaultTokenHeaderKey, await _lazyVaultToken.Value.ConfigureAwait(VaultClientSettings.ContinueAsyncTasksOnCapturedContext));
```

Then our code works as expected.

As a work around we have found this works:
```c#
var x = Task.Run(async () =>
{
  var appRoleAuth = new AppRoleAuthMethodInfo(roleId, secretId);
  var vaultClientSettings = new VaultClientSettings("https://example.org", appRoleAuth);
  vaultClientSettings.ContinueAsyncTasksOnCapturedContext = false;

  var vaultClient = new VaultClient(vaultClientSettings);

  var result = await vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("some/path/key");
  return result;
}).Result;
```

It would be great to have this fixed as it is cleaner than the use of `Task`.

We can submit a PR if this is useful?

**Comment by hoerup** [comment]
I would like to see this fix as a PR

**Comment by Poimen** [comment]
@hoerup - apologies, I've been out with some health issues. 

The commit https://github.com/hoerup/VaultSharp/commit/9664ef7a5c85e44649af2577cf02a09194c1a6e8 is exactly what the PR would have been.

**Comment by hoerup** [comment]
@Poimen see https://github.com/rajanadar/VaultSharp/issues/118

**Comment by hoerup** [comment]
@Poimen  you might want to look at https://github.com/VaultSharp/VaultSharp/pull/9 as well
