### ISSUE TITLE
Any plan for Reading Database Static Roles (and Credential Rotation) API?

### ISSUE THREAD

**Issue by stryt2** [rajanadar/VaultSharp#109]
Hello, 

Vault 1.2 or later supports [Database Static Roles and Credential Rotation](https://learn.hashicorp.com/vault/secrets-management/db-creds-rotation). 

Is there a plan to support Vault 1.2 or later or just this [get static credentials](https://www.vaultproject.io/api/secret/databases/index.html#get-static-credentials) API (i.e. reading from `database/static-creds/:name`) any time soon?

Thank you

**Comment by stryt2** [comment]
> @stryt2 , please look for a vnext date next week

@rajanadar , I'm afraid I don't understand what vnext date is.

**Comment by rajanadar** [comment]
@stryt2, 0.11.x release milestone is in 3 days, April 26. On Sunday, I'll be assigning a date for the vnext release.

**Comment by rajanadar** [comment]
@stryt2 I am beginning with the following APIs for 1.4.x version now.

read static role
list static roles
get static creds
rotate static creds

let me know if that's not sufficient to start with.
