### ISSUE TITLE
VaultClientSettings 

### ISSUE THREAD

**Issue by mmdrafiq** [rajanadar/VaultSharp#114]
VaultClientSettings method d'not have option to add namespace , so getting error as belwo 
VaultSharp.Core.VaultApiException
  HResult=0x80131500
  Message={"errors":["invalid role ID"]}

**Comment by Marusyk** [comment]
Hello @mmdrafiq 

Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking

**Comment by mmdrafiq** [comment]
Hi Marusyk ,

Thanks for your quick resoponse i am using following code to read the secreate 

IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
var vaultClientSettings = new VaultClientSettings("https://MY_VAULT_SERVER:8200", authMethod);

IVaultClient vaultClient = new VaultClient(vaultClientSettings);

to read the secrate values with specific namespace  need to specify the additional parameter for namespace , or is there any other method is available where i can specify the namespace .

**Comment by mmdrafiq** [comment]
downloaded VaultSharp 0.11.1002 NuGet Package and  VaultClientSettings  object d'not have property namespace to specify namespace and to read the secrets .

**Comment by Marusyk** [comment]
What do you mean by "namespace"?

**Comment by rajanadar** [comment]
fixed in #94

**Comment by andreifer20** [comment]
Could you please provide me an example with this features. I try to understand where I must define the namespace. Thanks in advance
