### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by puzanovrs** [rajanadar/VaultSharp#116]
Hi!
When the new NuGet package is released. We are waiting for an update of the #107 deadlock error when calling with a synchronous code. 
Thanks

**Comment by Marusyk** [comment]
It seems not soon. I'm waiting for release since last April, but no responses from @rajanadar

**Comment by hoerup** [comment]
I don't think anything is going to happen at this place. The only way forwards is a fork

**Comment by Poimen** [comment]
Just for FYI - 
For #107 the commit that @hoerup did in the fork at commit https://github.com/hoerup/VaultSharp/commit/9664ef7a5c85e44649af2577cf02a09194c1a6e8

should fix #107 

Cheers.

**Comment by hoerup** [comment]
https://github.com/rajanadar/VaultSharp/issues/118
