### ISSUE TITLE
Support for Cloud Foundry Auth method

### ISSUE THREAD

**Issue by devgig** [rajanadar/VaultSharp#120]
HashiCorp Vault has recently rolled out a Cloud Foundry Auth method https://www.vaultproject.io/docs/auth/cf/.  This is something all the cloud foundry users can benefit from.  I have working code and an example.  Please let me know if you want me to add this.  I can do a PR and include the additional feature.

**Comment by Marusyk** [comment]
Hi @devgig,

Thanks for your interest in this project. 
I think it's a great idea. But the project owner did not respond for a long time. We have quite an active fork, announced in #118. 

So if you're motivated that would be welcome!
https://github.com/VaultSharp/VaultSharp
