### ISSUE TITLE
Drop Support of DotNet Standard 1.3

### ISSUE THREAD

**Issue by devgig** [rajanadar/VaultSharp#121]
I am wanting to cache the token since it is expensive to retrieve from Vault.  I want to use Microsoft.Extensions.Caching.Memory but it is not supported in Dotnet Standard 1.3.

You can create a policy on the LeaseDurationSeconds property and just return the Cached Token on the GetVaultTokenAsync() method.
```
var policy = new MemoryCacheEntryOptions().SetAbsoluteExpiration(DateTimeOffset.Now.AddSeconds(authInfo.LeaseDurationSeconds));
Cache.Set(cacheKey, authInfo.ClientToken, policy);
```

**Comment by rajanadar** [comment]
@devgig , before we get into the caching part, VaultSharp retrieves the token only once per VaultClient. So it should be good till the expiry date, without ever refetching it.

Can you clarify?

**Comment by rajanadar** [comment]
@devgig  Let me know and if valid, i'll reopen

**Comment by devgig** [comment]
I understand what you are thinking now.  I could get requests for a different roleName, vaultServerUriWithPort, vaultNamespace with each request.  Holding the VaultClient in memory is not something I want to do for that reason, plus I need a way to know when the Lease has expired.   
I would want to cache the entire VaultClient object and use roleName, vaultServerUriWithPort, and vaultNamespace as the Key, but it is not Serializable.  I could just create my own Serializable VaultClient and then reconstitute VaultClient.
