### ISSUE TITLE
Support specifying `name` when using certificate authentication

### ISSUE THREAD

**Issue by woodne** [rajanadar/VaultSharp#133]
When authenticating with certificates it is possible to specify a name of the auth policy: https://www.vaultproject.io/docs/auth/cert#via-the-api

In my vault cluster, not passing the name causes the auth to fail. It would be useful to be able to pass the name along with the `CertAuthMethodInfo` to tell vault which policy to validate against

**Comment by rajanadar** [comment]
@woodne  I have published version 1.4.0.1 with this ability to provide role name.
Let me know if any issues.
