### ISSUE TITLE
list of aws roles

### ISSUE THREAD

**Issue by leowaisblatt** [rajanadar/VaultSharp#137]
It would be very useful if there were a way to get a list of aws roles (http call to /v1/aws/roles)

**Comment by rajanadar** [comment]
@leowaisblatt  I have published 1.4.0.2 with this ability.
Please upgrade the version and let me know if any issues.

**Comment by leowaisblatt** [comment]
thanks! @rajanadar. Pls note that the Http Method expected for vault is LIST, you are sending  GET and it fails.

**Comment by rajanadar** [comment]
Ohh oh. That's a silly bug on my side. I'll fix it in a couple of hours and get a new package out. Thanks for the instant feedback.

**Comment by rajanadar** [comment]
Meanwhile you can use the vault settings beforeapirequest handler to add the list query string if that is the url

**Comment by leowaisblatt** [comment]
it only works with Http Method= POST.
In the meantime I downloaded a version from git and fixed it on my local so I can move on.
thanks!

**Comment by rajanadar** [comment]
It will also work with http get, you need to append a query string of ?list=true

Anyways I'll fix it tonight

**Comment by rajanadar** [comment]
@leowaisblatt  please try 1.4.0.3. it should be fixed now.

**Comment by leowaisblatt** [comment]
looks good, thanks!
