### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by spetz** [rajanadar/VaultSharp#14]
Hi, are you planning to add the support for .NET Core? Since the **VaultSharp** references only _Newtonsoft.Json_ I guess that would be quite straightforward :).

**Comment by rajanadar** [comment]
thanks @spetz 

as soon as VaultSharp 0.6.2 is out, i'll be evaluating this and start making the changes.
0.6.2 had some changes in the underlying code to send http requests, so the core support will be a good item to look at after that. 

more than the actual code changes, i am guessing some time will be spent on setting up the solution, nugetting etc.. but it is definitely on the cards, after the 0.6.2 milestone. and i'll put a timeline to it, when i formulate it.

**Comment by spetz** [comment]
Thank you for the quick response, looking forward to this upgrade then.

**Comment by rajanadar** [comment]
jfyi @spetz and all the thumbs-up folks, am working on this as the last issue for 0.6.4
will wrap it up and publish 0.6.4 in a day. 

apart from Vault 0.6.4 parity, VaultSharp 0.6.4 will be strongly named and target both the full-fledged and core .net platforms.

**Comment by rajanadar** [comment]
@spetz and folks, VaultSharp 0.6.4 is live and cross-platform.
https://www.nuget.org/packages/VaultSharp/0.6.4

**Comment by CumpsD** [comment]
Awesome work! Thanks for this library @rajanadar

**Comment by rajanadar** [comment]
@spetz @CumpsD 

The latest version of VaultSharp (0.10.x) is out. It is cross-platform as well.
And it is redesigned from ground up, to be very modular. After the initial upgrade hiccup, it should get very intuitive to use.

Do check it out.
