### ISSUE TITLE
Create Database Role (Not a Static Role)

### ISSUE THREAD

**Issue by V1ct0rV** [rajanadar/VaultSharp#141]
Hi,

I will use dynamic credentials for my application on .net core 3.1, I can read the dynamic credentials, my app is multitenant, I want to create a role for each tenant and I want to do in the application, currently I'm creating the roles manually like so:

```
vault write database/roles/my-role \
    db_name=my-database \
    creation_statements="..." \
    default_ttl="1h" \
    max_ttl="24h"
```

Is there a way to do using the Library?

**Comment by rajanadar** [comment]
hi @V1ct0rV 

Right now, VaultSharp supports creation (and CRUD) of **static** database roles via the library. 

`vaultClient.V1.Secrets.Database.CreateStaticRoleAsync`

It seems what you are looking for are dynamic role creation. I'll add that this week and release a new version. Please look for an update shortly.
