### ISSUE TITLE
Kv2 secret engine

### ISSUE THREAD

**Issue by Melixen** [rajanadar/VaultSharp#142]
Hi!

According to these samples https://github.com/rajanadar/VaultSharp/blob/master/test/VaultSharp.Samples/Program.cs there is no way to upgrade kv secret engine to version 2. If I call 

`_authenticatedVaultClient.V1.System.MountSecretBackendAsync(kv2SecretsEngine)
`

with `SecretsEngineType.KeyValueV2` parameter I get error "plugin not found in the catalog: secret". In your samples I found also a comment "// raja todo: check this out later". 

Are you planning to finish up this feature? Or maybe I'm doing something wrong.

**Comment by rajanadar** [comment]
@Melixen 

You need to provide all the parameters needed to enable kv2, not just `SecretsEngineType.KeyValueV2`
Please see this API: https://www.vaultproject.io/api-docs/system/mounts#parameters

If you see the request payload parameters, you need to specify version as 2, in the options. Look for this text:

`version (string: "1") - The version of the KV to mount. Set to "2" for mount KV v2.`

In VaultSharp, you need to do:

```
kv2SecretsEngine.Options = new Dictionary<string, object>();
kv2SecretsEngine.Options.Add("version", "2");    // for a kv2 mount

await _authenticatedVaultClient.V1.System.MountSecretBackendAsync(kv2SecretsEngine)

```

Please give it a try and let me know. The program.cs is really my crude test program.

**Comment by Melixen** [comment]
1. vault.1.2.3
2. Non dev 
3. I tried to mount a totally new kv2 store and also I tried to upgrade kv1 to kv2. 
If I send request manually via Vault Rest API my kv becomes version 2
`/v1/sys/mounts/kv/tune`

**Comment by rajanadar** [comment]
Thanks. I'll setup that version, repro this and get back with a solution. By weekend.

**Comment by rajanadar** [comment]
One last thing. What's the VaultSharp version you are on?

**Comment by Melixen** [comment]
Ok, thanks. I use 1.4.0.3 version

**Comment by rajanadar** [comment]
@Melixen  i did a bit of debugging and it seems the "type" for kv2 is not "secret" anymore. It is "kv-v2"
Try this snippet and let me know.

```
var kv2SecretsEngine = new SecretsEngine
{
    Type = new SecretsEngineType("kv-v2"), // SecretsEngineType.KeyValueV2,
    Config = new Dictionary<string, object>
    {
        {  "version", "2" }
    },
    Path = path
};
```

**Comment by Melixen** [comment]
Yep, this works fine. Thanks.

**Comment by rajanadar** [comment]
Cool
