### ISSUE TITLE
Invalid secret path and failed reading

### ISSUE THREAD

**Issue by chuckhenry** [rajanadar/VaultSharp#143]
Hi Raja,
Thank you for offering this package. I would like to use it to access our Vault server and read the secrets in our .NET applications. I can read the secrets using python hvac for Python scripts. We prefer using your package to seemlessly integrate with our .net apps. I did a try with following codes but it always error out with my secret path  "/secret/corp/app1/dev/database_creds": 

> {"request_id":"84add85a-aa7e-6edc-752c-5415430db2ba","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,
>  "warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. 
>  If using the Vault CLI, use 'vault kv list' for this operation."],"auth":null}
> 

 Using Vault CLI, I can issue "vault read --format =json /secret/corp/app1/dev/database_creds" or "vault kv get --format=json /secret/corp/app1/dev/database_creds" to get the database credentials

     ```
  private async Task by_approle()
        {
            var roleId = "23b6dd8-b7f9-28dc-0e2e-6d1ec6d7d666";
            var secretId = "gf8da09a-d1c2-fa4a-f3a0-baeebcc90782";
            IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId, secretId);

            var url = "https://vault.server.services:443";
            var path = "/secret/corp/app1/dev/database_creds";

            var vaultClientSettings = new VaultClientSettings(url, authMethod);

            IVaultClient vaultClient = new VaultClient(vaultClientSettings);
            var secretTask = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretPathsAsync(path);
            Secret<ListInfo> secrets = await secretTask;
            ListInfo paths = secrets.Data;
        }
```
Based on the error message, it seems my secret path is invalid.  Then what could be the valid path for VaultSharp or I used **vaultClient.V1.Secrets.KeyValue.V1.ReadSecretPathsAsync** wrong ?
background: Vault server has 3 engines: kv (v2 kv_hss12a3), secret (generic_21232311), ssh. Our secrets are stored under /secret, which I thought it is unversioned KV engine but I do not have permission to call "vault secrets list".

           Thanks for your help and suggestions in advance!
           Henry

**Comment by chuckhenry** [comment]
when I add mountPoint:"secret" like 
var secretTask = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretPathsAsync(path, mountPoint:"secret");

It did not error for invalid path, but I got an exception of type 'VaultSharp.Core.VaultApiException'  with message of {"{\"errors\":[]}\n"}

**Comment by rajanadar** [comment]
Can you please provide the vault version and vault sharp version?

**Comment by chuckhenry** [comment]
vaultshart 1.4.0.4; Vault 1.4.2+prem (based on the vault UI bottom line)

**Comment by chuckhenry** [comment]
I found the issue: the path should not include the mount point. 
When I changed path from  var path = "/secret/corp/app1/dev/database_creds" to  var path = "corp/app1/dev/database_creds";
  and call: aultClient.V1.Secrets.KeyValue.V1.ReadSecretPathsAsync(path) to 
    aultClient.V1.Secrets.KeyValue.V1.ReadSecretPathsAsync(path, mountPoint:"secret"); 

I can get what I want. 

Thank you!

**Comment by rajanadar** [comment]
Cool. Was gonna look at this, this weekend. Glad that it's resolved.

**Comment by tarunnarang0201** [comment]
Hello @rajanadar 

I am also facing the same issue/error, I tried various combinations but none of them worked. 
Policy is mentioned below which I applied

```
path "devkv/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/dev/resources/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

path "kv/dev/resources/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}
```

New mountPoint was created by name of **devkv** and path **connections** which has **resources** key stored. 
**This is shown in the image below**
![image](https://user-images.githubusercontent.com/67380484/87852353-d2bc9e80-c91e-11ea-9acc-5afa36685ef7.png)

**And to retrieve the key, calling code is shown here:-**

![image](https://user-images.githubusercontent.com/67380484/87852461-d0a70f80-c91f-11ea-8715-822cf072cf34.png)

You knowledge/expertise would be appreciated.

Thanks
