### ISSUE TITLE
How to create and get the client token

### ISSUE THREAD

**Issue by chuckhenry** [rajanadar/VaultSharp#144]
I would like to use the system login user id and password to get a token in vault.

In CLI, I can get a token like: **vault login --path ping --method=userpass username=henry**, then I could get a response of keys and values.   How can I make a call with VaultSharp to do it?

**Comment by rajanadar** [comment]
@chuckhenry  You can get the token as follows:

```
IAuthMethodInfo authMethod = new UserPassAuthMethodInfo(username, password);
var vaultClientSettings = new VaultClientSettings("https://MY_VAULT_SERVER:8200", authMethod);

IVaultClient vaultClient = new VaultClient(vaultClientSettings);

// Now do any operation using vaultClient.
// Whenever the first operation is done, VaultSharp internally does a Login call
// and the Token Info is set in the 

```

`authMethod.ReturnedLoginAuthInfo` object.

Let me know if any new issues.

**Comment by chuckhenry** [comment]
after I executed vaultClient line code and then these two: 
 var data = await vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("ping/login/myusername", mountPoint: "auth");
            Dictionary<string, object> dataDictionary = data.Data;
it threw: 
"errors":["missing client token"]

When I used httpclient directly, I could get the token through the path like: https://myvault-url/v1/auth/ping/login/myusername.
