### ISSUE TITLE
Read KV Secret Issue

### ISSUE THREAD

**Issue by rajanadar** [rajanadar/VaultSharp#145]
Hello @rajanadar 

I am also facing the same issue/error, I tried various combinations but none of them worked. 
Policy is mentioned below which I applied

```
path "devkv/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/dev/resources/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

path "kv/dev/resources/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}
```

New mountPoint was created by name of **devkv** and path **connections** which has **resources** key stored. 
**This is shown in the image below**
![image](https://user-images.githubusercontent.com/67380484/87852353-d2bc9e80-c91e-11ea-9acc-5afa36685ef7.png)

**And to retrieve the key, calling code is shown here:-**

![image](https://user-images.githubusercontent.com/67380484/87852461-d0a70f80-c91f-11ea-8715-822cf072cf34.png)

You knowledge/expertise would be appreciated.

Thanks

_Originally posted by @tarunnarang0201 in https://github.com/rajanadar/VaultSharp/issues/143#issuecomment-660476022_

**Comment by rajanadar** [comment]
@tarunnarang0201 can you please provide the Vault version, Vault Sharp version and the commands you used to mount this KV engine, and to write the secret? And also the error that you get in VaultSharp.

**Comment by tarunnarang0201** [comment]
Vault version - 1.4.3, Vault Sharp Version - 1.4.0.1

I created the devkv engine through UI itself and added the key there.

**Error;-**, 
![image](https://user-images.githubusercontent.com/67380484/87853835-449ae500-c92b-11ea-982d-e9c0d4761029.png)

**Comment by rajanadar** [comment]
hey, 

Is your KV engine V1 or V2? If v2, can you try `vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("connections", mountPoint: "devkv")` ?

**Comment by tarunnarang0201** [comment]
Thanks @rajanadar it worked, admire your knowledge. 

What got changed from V1 to V2 at the backend which make it worked.

**Comment by rajanadar** [comment]
Hey @tarunnarang0201

The Vault team (not vault sharp) has 2 versions of their KV. One is pretty basic and the other newer v2 one has more features in term of version Ed secrets, Metadata etc. And because it is the newer recommended kv engine, v2 is the default kv engine in the newer versions of vault.

**Comment by tarunnarang0201** [comment]
Ok Thanks
