### ISSUE TITLE
Can't insert a kv v2 secret with nested dictionary as payload

### ISSUE THREAD

**Issue by sebastianrakel** [rajanadar/VaultSharp#147]
Hey,

i want to write a secret in a vault v2 keyvalue store. This secret is a nested dictionary. See following code:
```
var payload = new Dictionary<string, Dictionary<string, object>>();
payload.Add("test", new Dictionary<string, object>
            {
                {"Blub", 1 },
                {"Foo", "bar" }
            });

var writeTask = vaultClient.V1.Secrets.KeyValue.V2.WriteSecretAsync("mysecretpath/supersecret", payload);
writeTask.Wait();
```

i expected it to working but following error occured: 
```{"Error converting value \"2020-08-06T12:32:14.562878383Z\" to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'. Path 'data.created_time', line 1, position 159."}```

Can someone help me to get it work? or maybe it's a bug?

With a V1 KeyValue Secret Store this code works

**Comment by rajanadar** [comment]
Are you able to write a normal non nested dictionary?

**Comment by sebastianrakel** [comment]
Normal non nested dictionaries are working

**Comment by rajanadar** [comment]
OK. Can you please try the nested one with vault cli or postman? 

If that works, then there is a VaultSharp bug and I'll have a look. But if that also doesn't work, then this maybe a vault constraint that you cannot send nested dictionaries.

**Comment by sebastianrakel** [comment]
vault cli is working fine

```echo '{"test": {"foo": "bar", "bar": "foo"}}'  | vault kv put  mysecretpath/supersecret -```

**Comment by rajanadar** [comment]
Cool. I'll have a look today.

**Comment by rajanadar** [comment]
@sebastianrakel  I was able to repro this. This is a VaultSharp bug. Fix in progress.

**Comment by rajanadar** [comment]
this is fixed @sebastianrakel . The bug was because I assumed that the return value is the data you write. It is not.

**Comment by rajanadar** [comment]
I'll publish the new version by weekend.

**Comment by rajanadar** [comment]
https://www.nuget.org/packages/VaultSharp/1.4.0.7
