### ISSUE TITLE
Strongly name the release builds

### ISSUE THREAD

**Issue by pascal-enz** [rajanadar/VaultSharp#15]
Hi, would it be possible to sign the assembly with a strong name?
We have internal guidelines in the company that our assemblies need to be signed which also requires all referenced assemblies to have a strong name.

**Comment by rajanadar** [comment]
hi @pascal-enz 

right now, there is nothing on the radar about strong naming. my initial thinking was to reach v1.0.0 (kind of first stable version) and then think of these things. especially since i probably need to procure new certificates. 

also, am reading multiple guidelines on strong naming open sourced libraries.. some of them recommend 'not signing', some of them defer it to the consumer's company, some of them have custom methodologies (JameNK) etc.  so i also need to finalize on one recommended pattern.

no commitments yet, but l can re-evaluate and let you know after i release v0.6.2 next week.

**Comment by rajanadar** [comment]
no immediate plans for it right now.. let me know if this is blocking you badly

**Comment by anthonylangsworth** [comment]
I work in the same team as @pascal-enz . I respectfully disagree with your decision not to strong name your VaultSharp. It means teams referencing VaultSharp form strong named assemblies lose the ability to receive updates via NuGet and must manually merge changes instead to its own fork.

Meanwhile, strong naming does not preclude teams recompiling it from source and using their own strong name if the integrity check is desired. There are other integrity checking options available, including an authenticode digital signature or traditional file checksum scanning.

This is why most open source projects now choose to include the snk file for strong naming assemblies, including .Net Core, NUnit and xUnit. Log4net summarizes this conumdrum well at https://github.com/apache/log4net/blob/trunk/log4net.snk.readme. 

I appreciate there is a lot of work involved in a project like this and am happy to do the work of adding a strong name via a pull request if that would be easier.

**Comment by rajanadar** [comment]
thanks @anthonylangsworth for the insight and links.  
have re-opened the issue and re-titled it.

am finishing up 0.6.4, and will look into this (including a snk file option) as part of that.

**Comment by anthonylangsworth** [comment]
Just to make sure my understanding is correct, the plan is for the next release should include a strongly named assembly. Please let me know if that is incorrect.

**Comment by rajanadar** [comment]
@anthonylangsworth i am thinking through this a bit more, in terms of procuring a key and either including it in the source code (.snk), or the other option of just publishing the strongly named assembly to NuGet.. will try to accommodate it in 0.6.4, and if otherwise, will update this issue asap.

**Comment by rajanadar** [comment]
thanks @pascal-enz and @anthonylangsworth for this discussion and PR.
 VaultSharp 0.6.4 is now live. please go get it to see this fix!

**Comment by anthonylangsworth** [comment]
I have verified the fix in a test assembly. I will leave it to @pascal-enz to test in our product.

**Comment by pascal-enz** [comment]
I updated my projects to 0.6.4 and deployed them. Everything works fine. Thanks a lot for the fix.

**Comment by rajanadar** [comment]
thanks @pascal-enz 

quick question.. because 0.6.1 was not strongly named, and 0.6.4 is.. did NuGet automatically suggest an update to 0.6.4 (i thought a strong name change misdirects NuGet) 
OR
did you have to do a manual NuGet install of 0.6.4?

**Comment by pascal-enz** [comment]
Sorry, I don't know. I didn't update the Nuget package because with 0.6.1 we referenced a DLL directly which we signed ourselves without Nuget.

**Comment by anthonylangsworth** [comment]
> Sorry, I don't know. I didn't update the Nuget package because with 0.6.1 we referenced a DLL directly which we signed ourselves without Nuget.

You mean strong named, @pascal-enz . 😄 

@rajanadar The DLL gets updated automatically when you do a `nuget update` or similar.

**Comment by rajanadar** [comment]
oh cool. thanks @pascal-enz and @anthonylangsworth 

and as part of this exercise, i learned that strong naming of open-source libs has nothing to do with signing or security :)
