### ISSUE TITLE
Renew AppRole lease 

### ISSUE THREAD

**Issue by SchroterQuentin** [rajanadar/VaultSharp#151]
It seems that when using AppRole as authentication mechanism, the lease is not renewed every time it needs to.

I have an app (in production environment ^^) which is up since 33 days and this morning I'm getting a `{"errors":["permission denied"]}` when attempting to get a secret.
The Vault logs are the following :

> 2020-07-18T13:51:53.215Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/h5ba29e8a53385d2f6d35a0d7470c4cf1178f8183b6cea04a322131c8061e5b7b
> 2020-07-19T13:40:27.646Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/ha92fc0c446f237fc603ed17ddd138de9892caf56951df65f82056d15a369b121
> 2020-07-19T14:25:00.168Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/he8766be49212abefc20bf32742e200592fe480f9df9dd4ca49be6fe62cc660e7
> 2020-07-24T08:58:30.511Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/h84fe5ee244201987caeb88a188991f9afdaadffc24ca48a45aa7d43b8332f969
> 2020-07-24T16:29:20.150Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/h4e1d72246eb943198a1e546e56132c6df3760aa3cbcfe2fda1a2536a90c6f523
> 2020-08-04T21:30:21.971Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/ha522fc04194a51d11b13b0e80f13246ef692c128c96aa546c8075f0c0e738ed1
> 2020-08-15T17:19:46.102Z [INFO]  expiration: revoked lease: lease_id=auth/approle/login/hb14bc652a5929577f4fd532089247ec81f43304a08265213d89917a4d3cd1401

And after restarting the app, it works as expected so I guess it's an issue with lease renew.
I'm actually using the `IVaultClient` as a singleton in my app in order to not getting a new lease for each instance of VaultClient I need :

```cs
services.AddSingleton<IVaultClient>(sp =>
{
     IAuthMethodInfo authMethodInfo = new AppRoleAuthMethodInfo(vaultConfig.AuthRole, vaultConfig.AuthSecretId);
     var vaultClientSettings = new VaultClientSettings(vaultConfig.EndpointURI, authMethodInfo);
     return new VaultClient(vaultClientSettings);
});

```

VaultSharp : 1.4.0.3
Server Vault : 1.4.2

**Comment by rajanadar** [comment]
Hi

VaultSharp doesn't do auto renewal of any token or lease. It doesn't do any tracking of lifetime etc. It is left to the host application to track the expiry of a token and renew the lease as required.

A few folks that I have spoken to ensure that their app deployment cadence in production is less than the expiry of a token. That way, they balance security and effort to write renewal logic.

That's the reason VaultSharp also keeps away from automatically and perennially extending the life of a token, but does provide apis for the host to do it under their discretion.

**Comment by SchroterQuentin** [comment]
Hi,

Thanks for this quick response, I didn't know that it was left to the host application to ensure this renewal. If it's not written in the documentation, could we had it ?

Is there some snippets which show an example of how it may be handled by the host application ? I don't know well VaultSharp yet, but is there some classes which contains the lease / lifecycle or something like that, in the VaultClient ?

I may find a solution with the DI container to renew the instance expiration of the token lifetime. If so, I'll paste some code here.

Thanks @rajanadar
