### ISSUE TITLE
WriteSecretAsync returns null

### ISSUE THREAD

**Issue by ashtek19** [rajanadar/VaultSharp#154]
I'm using WriteSecretAsync to store secret in Vault. It is working fine ie it stores the secret in Vault but it is returning null
I use - KV Engine V1, Mountpoint 'cf', Vaultsharp ver 1.4.0.5

var result = await _vaultClient.V1.Secrets.KeyValue.V1.WriteSecretAsync(path, dataDictionary,  "cf");

When I check "result", it is null

Second issue - is there a way to know if DeleteSecretAsync was successful? Ex. if the secret was found and deleted, I return a boolean (true). If not, return false.

**Comment by rajanadar** [comment]
Do you still have this issue? @ashtek19

**Comment by rajanadar** [comment]
@ashtek19  Not sure if kv1 returns any value on write or delete. You need to read the secret to know about it.
