### ISSUE TITLE
Wrong target framework for nuget package

### ISSUE THREAD

**Issue by cosminvlad** [rajanadar/VaultSharp#159]
In the nuget package 1.4.0.3, all dlls targeted .netstandard1.3. From 1.4.0.4 on, they all target .net framework 4.5. The dlls in the respective folders should target  corresponding frameworks.
![image](https://user-images.githubusercontent.com/44359935/95718034-8ad7ba00-0c76-11eb-9673-40b5bc50da57.png)

**Comment by rajanadar** [comment]
thanks @cosminvlad

**Comment by rajanadar** [comment]
@cosminvlad I explored the NuGet packages and it shows different and correct stuff to me.

![image](https://user-images.githubusercontent.com/376958/100107381-6bf44800-2e1e-11eb-8bfa-25305cc0da26.png)

Other users haven't complained yet. Do you see any actual usage issues?
Can you try with a Nuget package explorer?

I have used my library with .net 4.5 and core and it works.
