### ISSUE TITLE
Question: How to retrieve a secret_id for an AppRole.

### ISSUE THREAD

**Issue by jefflill** [rajanadar/VaultSharp#16]
What's your recommended method for retrieving the a **secret_id** from an AppRole?  I have created an AppRole at `auth/approle/role/test` and using the Vault CLI, I'd retrieve the secret_id via:

&nbsp;&nbsp;&nbsp;&nbsp;`vault write -f auth/approle/role/test/secret-id`

which returns:

&nbsp;&nbsp;&nbsp;&nbsp;`Key                     Value`
&nbsp;&nbsp;&nbsp;&nbsp;`---                     -----`
&nbsp;&nbsp;&nbsp;&nbsp;`secret_id               306790f6-9ee0-3d7a-9af5-f87913ecb269`
&nbsp;&nbsp;&nbsp;&nbsp;`secret_id_accessor      dc47aaa4-fd39-5dff-476a-dddaf97d2d16`

`IVaultClient.WriteSecretAsync()` returns a void Task so there's no way I can see to obtain the results from the API.  I poked around the source and didn't see another method to do this, but maybe I missed it.

**Comment by rajanadar** [comment]
thanks @jefflill for using the library. 

you are right. there is no way to return the data as part of the generic write. i have created a bug to fix this in the next version.

the next version of VaultSharp is also going to have strongly typed API support for the AppRole authentication back-end Apis. that would solve the WriteSecretIdAsync problem 100% and return a strongly typed object with secret id and the accessor.

expect the next version after the holidays.

let me know how critical (time-wise) it is to get this functionality.

**Comment by jefflill** [comment]
Thanks for the update.

This is not a problem.  I'm just using the REST API directly for now.

--Jeff

**Comment by rajanadar** [comment]
@jefflill  VaultSharp 0.6.4 is now live. the write api now returns data instead of void. that should give you the secret id.

**Comment by jefflill** [comment]
Thanks for the update.

--Jeff
