### ISSUE TITLE
Drop dependency on Portable.BouncyCastle on core NuGet and move CloudFoundry to separate module

### ISSUE THREAD

**Issue by prcdpr** [rajanadar/VaultSharp#162]
Portable.BouncyCastle is very heavy DLL (around 2.65 MB). It's only used in CloudFoundry auth method, I think we should move that auth method to separate NuGet to make the core NuGet lighter.

**Comment by rajanadar** [comment]
Understood. So much for trying to make life easier for clients. But i agree 100% with you.

What I will do is, remove it and probably just have this snippet as a GitHub Gist in my docs.

**Comment by rajanadar** [comment]
removed the dependency. unfortunately it results in the constructor param changes.
also provided a gist reference for vaultsharp users: https://gist.github.com/rajanadar/84769efeca64e0128d7a8a627b7bb4db

**Comment by prcdpr** [comment]
Thank you very much for your work

**Comment by rajanadar** [comment]
https://www.nuget.org/packages/VaultSharp/1.4.0.7
