### ISSUE TITLE
kv put vs patch functionality

### ISSUE THREAD

**Issue by jluttrell** [rajanadar/VaultSharp#167]
**Describe the feature request or question**
vault cli has capability to do `kv patch` and `kv put` with the difference being:
> Unlike the kv put command, the patch command combines the change with existing data instead of replacing them. Therefore, this command makes it easy to make a partial updates to an existing data.

From what I can tell, this is not currently possible with the vault api or with VaultSharp (within single request or without custom logic), although I admit I'm still not entirely sure about the different scenarios when setting the Check-And-Set (cas) option.

So my questions are, is this currently possible and I'm just missing it? If it is missing, would this be worth implementing? I'm happy to help out any way I can, including opening a PR.

**Link to the Vault API Docs that support this feature**
[vault cli kv patch](https://www.vaultproject.io/docs/commands/kv/patch)
[vault cli kv put](https://www.vaultproject.io/docs/commands/kv/put)
[vault api create/update secret](https://www.vaultproject.io/api-docs/secret/kv/kv-v2#create-update-secret)

**Comment by rajanadar** [comment]
hi @jluttrell 

Thanks for this. This is currently not supported VaultSharp as a first-class concept. I'll add it and publish a new version this weekend. I have a couple of other changes to push as well.

**Comment by hs-joseph-luttrell** [comment]
Awesome! I look forward to checking it out. Lmk if you need anything else from me. Thanks @rajanadar!

**Comment by jluttrell** [comment]
Awesome! I look forward to checking it out. Lmk if you need anything else from me. Thanks @rajanadar!

**Comment by rajanadar** [comment]
@jluttrell  I published a new version with support for patch. Please use https://www.nuget.org/packages/VaultSharp/1.6.0.1 or later.

Let me know if any issues. 

The Readme.md help is here: https://github.com/rajanadar/VaultSharp/blob/master/README.md#patch-secret

The code sample is here: https://github.com/rajanadar/VaultSharp/blob/master/test/VaultSharp.Samples/Program.cs#L296

**Comment by jluttrell** [comment]
Thanks @rajanadar! I haven't been able to test it out yet but changes look great. Appreciate the quick turnaround.
