### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#168]
**Describe the bug**
Unable to fetch secret , getting Exception - An error occurred while sending the request.The request was aborted: Could not create SSL/TLS secure channel.

**VaultSharp Version**
The version of VaultSharp package being used is 1.4.0.5

**Vault Version**
The version of Vault server being used is 1.5.3

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**
 try
                {
                    ServicePointManager.Expect100Continue = true;
                    ServicePointManager.SecurityProtocol =
                        SecurityProtocolType.Tls
                        | SecurityProtocolType.Tls11
                        | SecurityProtocolType.Tls12
                        | SecurityProtocolType.Ssl3;

                // Certificate(TLS) Auth Method

                var certificate = new X509Certificate2(fetchCertificate);
                    IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
                    var vaultClientSettings = new VaultClientSettings(vaultUrl, authMethod);
                    IVaultClient vaultClient = new VaultClient(vaultClientSettings);

                Secret<SecretData> kv2Secret =
                        await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path, null, mountPoint); // Exception thrown from here!!
                    SecretData dataDictionary = kv2Secret.Data;

                    Logger.Trace("Fetch Secret successful : " + dataDictionary);
                    return Request.CreateResponse(HttpStatusCode.OK, dataDictionary);
}
 catch (Exception exception)
                {
                Logger.Trace("From Vault..Exception: "+exception.Message+exception.InnerException?.Message +exception.StackTrace);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, exception.Message+exception.InnerException?.Message +exception.StackTrace);

                }

**Exception Details/Stack Trace/Error Message**
 From Vault..Exception: An error occurred while sending the request.The request was aborted: Could not create SSL/TLS secure channel.   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeRequestAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.AuthMethods.Cert.CertAuthMethodLoginProvider.<GetVaultTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValueSecretsEngineV2Provider.<ReadSecretAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Any additional info**
i am trying withe  certificate authentication, able to retrieve the installed certificate.pfx  and also through CLI I am able to login to Vault and fetch secret. But via .NET Web API I am unable to retrieve. My .NET framework is "net452".

Please help on this. Thanks!

**Comment by rajanadar** [comment]
hi @mohanakrishnans007 

VaultSharp will throw a clear error message if the SSL cert has an issue in terms of not in the correct format, OR if it is missing the private key. From the error message, that is not the issue. So it is a good cert with private key.

From the error it looks like, it is a runtime exception during the SSL handshake. This could happen if the cert is self-signed and not signed by a trusted CA. In any case, can you please add the following snippet and let me know the results.

```

ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol =
SecurityProtocolType.Tls
| SecurityProtocolType.Tls11
| SecurityProtocolType.Tls12
| SecurityProtocolType.Ssl3;

            System.Net.ServicePointManager.ServerCertificateValidationCallback +=
                    (sender, cert, chain, error) =>
                    {
                        // put a breakpoint and debug the 'error' variable

                        return true;
                    };

```

**Comment by mohanakrishnans007** [comment]
Hi 

> hi @mohanakrishnans007
> 
> VaultSharp will throw a clear error message if the SSL cert has an issue in terms of not in the correct format, OR if it is missing the private key. From the error message, that is not the issue. So it is a good cert with private key.
> 
> From the error it looks like, it is a runtime exception during the SSL handshake. This could happen if the cert is self-signed and not signed by a trusted CA. In any case, can you please add the following snippet and let me know the results.
> 
> ```
> 
> ServicePointManager.Expect100Continue = true;
> ServicePointManager.SecurityProtocol =
> SecurityProtocolType.Tls
> | SecurityProtocolType.Tls11
> | SecurityProtocolType.Tls12
> | SecurityProtocolType.Ssl3;
> 
>             System.Net.ServicePointManager.ServerCertificateValidationCallback +=
>                     (sender, cert, chain, error) =>
>                     {
>                         // put a breakpoint and debug the 'error' variable
> 
>                         return true;
>                     };
> ```

Hi @rajanadar ,
I added the the code that you have suggested but no traces was found for the error variable. Please find below

 try
                {
                    ServicePointManager.Expect100Continue = true;
                    ServicePointManager.SecurityProtocol =
                        SecurityProtocolType.Tls
                        | SecurityProtocolType.Tls11
                        | SecurityProtocolType.Tls12
                        | SecurityProtocolType.Ssl3;
                ServicePointManager.ServerCertificateValidationCallback +=
                        (sender, cert, chain, error) =>
                        {
                            // put a breakpoint and debug the 'error' variable
                            Logger.Trace("ServerCertificateValidation Error: " + error.ToString());
                            return true;
                        };
                // Certificate(TLS) Auth Method

                var certificate = new X509Certificate2(fetchCertificate);
                    IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
                    _vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
                    {
                        BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
                        {
                            httpRequestMessage.Headers.Add("X-Vault-Namespace", vaultNamespace);
                        }
                    });

                Secret<SecretData> kv2Secret =
                        await _vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path, null, mountPoint);
                    SecretData dataDictionary = kv2Secret.Data;

                    Logger.Trace("Fetch Secret successful : " + dataDictionary.Data.Values.FirstOrDefault());
                    return Request.CreateResponse(HttpStatusCode.OK, dataDictionary.Data.Values.FirstOrDefault());
}
catch (Exception exception)
                {
                Logger.Trace("From Vault..Exception: "+exception.Message+exception.InnerException?.Message +exception.StackTrace);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, exception.Message+exception.InnerException?.Message +exception.StackTrace);

                }

please help. Thanks!

**Comment by rajanadar** [comment]
OK thanks.

Is the error variable null?
Also, is the cert self signed?

**Comment by mohanakrishnans007** [comment]
> OK thanks.
> 
> Is the error variable null?
> Also, is the cert self signed?

Hi @rajanadar 
No traces was found for the error variable - Logger.Trace("ServerCertificateValidation Error: " + error.ToString());
Even this "ServerCertificateValidation Error:" text also not logged .

Regd Certificate its signed a CA .

Thanks!
Mohan

**Comment by rajanadar** [comment]
Forget the trace. Please put a breakpoint and let me know what those variable values are. Are they coming up as null in your breakpoint watch variables?

**Comment by mohanakrishnans007** [comment]
Hi @rajanadar ,
Unfortunately my Dev VM to Hashi Corp Vault server there is no network connectivity(Some network restrictions) so I am deploying my changes in the Dev IIS server which has connectivity to HashiCorp Vault and tracing the errors through logs only.  

Even locally I tried to capture it through watch in VS but nothing is available. 

Thanks!
Mohan

**Comment by rajanadar** [comment]
Try emitting the details in the response content so that you can see it in the browser response in your dev env. We want to see is there are ssl validation errors.

Also, how did you verify that the same setup works on your iis instance using vault cli etc.? It is a necessary check to ensure that the issue is not with your vault role setup etc. Before we look at VaultSharp.

In your true iis environment we want to check if vault is setup correctly for pki Auth using the right roles, and that this cert works using vault cli etc.

**Comment by mohanakrishnans007** [comment]
In the  IIS server in the CLI, I am able to retrieve the Secret data successfully PFB the CMD commands details. But only with .NET Web API I am unable to fetch the secret data.

C:\cert>vault login -method=cert -client-cert=TEST.cer -client-key=TESTPVTKEY.key

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                            Value
---                            -----
token                          *********************
token_accessor                 **********************
token_duration                 768h
token_renewable                true
token_policies                 ["default" "*********"]
identity_policies              []
policies                       ["default" "************"]
token_meta_authority_key_id    ******************
3:28:5f:c8
token_meta_cert_name           *************
token_meta_common_name         ***************
token_meta_serial_number       *******************
token_meta_subject_key_id      *************************
2:c7:7d:f6

C:\cert>vault read ********/********/KEY
Key         Value
---         -----
data        map[KEY:**********************]
metadata    map[created_time:2020-12-01T14:47:40.939497602Z deletion_time: destroyed:false version:1]

**Comment by hoerup** [comment]
This sounds more like a generic https issue than a vault specific problem. I assume that your vault is using default tls_min_version = tls12
So you need to ensure that your dotnet runtime and code can speak tls 1.2 or better.

Try to do a very simple test where your code just queries https://<your-vault-server>:8200/sys/health with a normal HttpClient.getAync

**Comment by mohanakrishnans007** [comment]
> This sounds more like a generic https issue than a vault specific problem. I assume that your vault is using default tls_min_version = tls12
> So you need to ensure that your dotnet runtime and code can speak tls 1.2 or better.
> 
> Try to do a very simple test where your code just queries https://your-vault-server:8200/v1/sys/health with a normal HttpClient.getAync

HI @hoerup ,

I tried calling /sys/health got the same error PFB the details.

[HttpPost]
        [Route("test/api/v1/checkvault")]
        public async Task<HttpResponseMessage> PostVaultDetails(hashSearch)
        {
          var client = new HttpClient();
            var httpRequestMessage = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri(vaultUrl + healthUrl),
                Headers =
                {

                    {HttpRequestHeader.Accept.ToString(), "application/json"},
                    {"X-Version", "1"}
                }
            };
            try
            {
                var response = await client.SendAsync(httpRequestMessage);
                //  if (!response.IsSuccessStatusCode) return null;
                Logger.Trace("Http Response from Vault : " + response);
                var responseFromVault = await response.Content.ReadAsStringAsync();
                Logger.Trace("String Response from Vault : " + responseFromVault);
                return Request.CreateResponse(HttpStatusCode.OK, responseFromVault);
            }
            catch (Exception exception)
            {
                Logger.Error("Exception from Vault :" + exception.Message + exception.InnerException +exception.StackTrace);
                return Request.CreateResponse(HttpStatusCode.InternalServerError, exception);
            }		
		}

2020-12-10 18:09:43.2759|ERROR|Controller|23|Exception from Vault :An error occurred while sending the request.System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Please suggest/help how can we handle this? 
Thanks!
Mohan

**Comment by rajanadar** [comment]
That's a great suggestion by @hoerup

@mohanakrishnans007, based on the error, it definitely is an inherent problem between your iis server and the vault server. Not related to VaultSharp.

We really can't do anything in VaultSharp at this point. You need to investigate why even a normal https request from your iis server is not working with your vault server. 

Some of the things I would check are:

1. Remote into the iis server and just curl vault server to see if curl commands work
2. Remote and hit vault Get APIS in browser or postman like tool to see if you can see the response without ssl errors etc. 
3. Enable ssl log in. Net and try your snippet again. Here is a pointer.

https://stackoverflow.com/a/5985497/1174414 

Good luck with the issue. Though not related to VaultSharp, do let us know when the issue is solved, as to what the root cause was.

**Comment by mohanakrishnans007** [comment]
Hi @rajanadar @hoerup 
I am able to fetch successful response from Vaultserver with  https://your-vault-server:8200/v1/sys/health with a normal HttpClient.getAync

With the above Get Call code I added this piece of code
  ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol =
                SecurityProtocolType.Tls
                | SecurityProtocolType.Tls11
                | SecurityProtocolType.Tls12
                | SecurityProtocolType.Ssl3;


            ServicePointManager.ServerCertificateValidationCallback +=
                    (sender, cert, chain, error) =>
                    {
                                              return true;
                    };

With this I got the 200 Success response code 
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=16070400; includeSubDomains
Date: Fri, 11 Dec 2020 11:01:33 GMT
Content-Length: 348

"{\"initialized\":true,\"sealed\":false,\"standby\":false,\"performance_standby\":false,\"replication_performance_mode\":\"disabled\",\"replication_dr_mode\":\"disabled\",\"server_time_utc\":1607684658,\"version\":\"1.5.3+ent\",\"cluster_name\":\"vault-cluster-******************\",\"cluster_id\":\"**************************\",\"last_wal\":764}\n"



With these same piece of code for TLS, SSL Auth I am hitting the Vault Server with VaultSharp package I am getting The request was aborted: Could not create SSL/TLS secure channel error, what am I missing here, please help 

Thanks!
Mohan

**Comment by rajanadar** [comment]
@mohanakrishnans007  Can you please try a VaultSharp call with a non-cert Auth?
i.e. Using Token Auth etc. You can do this by making Vault CLI work first, then grab the vault token (s.xxxxx) and use that in VaultSharp by doing https://github.com/rajanadar/VaultSharp/blob/master/README.md#token-auth-login-method

If the above call succeeds, then it will prove that there is a VaultSharp issue with Cert based Auth. (A VaultSharp or Certificate problem)
If the above call fails with the same SSL error, then it'll prove that there is a genuine SSL issue with your vault connection. (not a VaultSharp issue)

**Comment by tanishagarg-sf** [comment]
Hi @rajanadar 
1. Using cert based auth i am seeing "The request was aborted: Could not create SSL/TLS secure channel" on our hosts, but code works fine on local. I tried token auth, using it C# code is able to successfully read secret from Vault. 
2. Using curl, i am able to successfully read secrets on our hosts
Can you please guide further thanks!
