### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#171]
@hoerup @rajanadar  Continuation of below issue
https://github.com/rajanadar/VaultSharp/issues/168#issuecomment-743134157

**Comment by rajanadar** [comment]
@mohanakrishnans007 

Can you please try a VaultSharp call with a non-cert Auth?

i.e. Using Token Auth etc. You can do this by making Vault CLI work first, then grab the vault token (s.xxxxx) and use that in VaultSharp by doing https://github.com/rajanadar/VaultSharp/blob/master/README.md#token-auth-login-method 

If the above call succeeds, then it will prove that there is a VaultSharp issue with Cert based Auth. (A VaultSharp or Certificate problem)
If the above call fails with the same SSL error, then it'll prove that there is a genuine SSL issue with your vault connection. (not a VaultSharp issue)

**Comment by mohanakrishnans007** [comment]
I have fixed this issue with IIS_AppPool/<AppliocationAppPoolName> providing access to the Client Certificate through the MMC. We can close this issue. Thanks!!

**Comment by rajanadar** [comment]
Glad to hear.
