### ISSUE TITLE
Reuse of token 

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#173]
**Describe the bug**
We have set the TTTL of the token for 60 seconds in the Vault Server end and we tested with 5 transactions with in that time limit. From the VaultServer end we could able to see 5 tokens generated for these 5 transactions. Is this the behavior of Vault Sharp? How can we reuse the token ? or do we need to tweak anything to reuse the token with in the TTL? Could you please let me know on this ? Thanks! 

**VaultSharp Version**
VaultSharp 1.6.0.2

**Vault Version**
1.5.3

**Does this work with Vault CLI?**
Yes/No

**Sample Code Snippet**
            {
                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                ServicePointManager.ServerCertificateValidationCallback +=
                    (sender, cert, chain, error) =>
                    {
                        _logger.Trace("Server Certificate Validation Error: " + error.ToString());
                        return true;
                    };
                // Certificate(TLS) Auth Method
                var certificate = new X509Certificate2(fetchCertificate);
                IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
                _vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
                {
                    BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
                    {
                        httpRequestMessage.Headers.Add("X-Vault-Namespace", vaultNamespace);
                    }
                });

                var vaultResponse = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);
                var gpSecretId = vaultResponse?.Data?.Values.FirstOrDefault()?.ToString();               
                var hashCorpVaultFetchSecretResponse = JObject.Parse(gpSecretId);
                var secretValue = hashCorpVaultFetchSecretResponse?.First?.First?.Value<string>();
                _logger.Trace("Secret from Vault : " + secretValue);
                vaultServerResponse.SecretValue  = secretValue ;
}

**Exception Details/Stack Trace/Error Message**
Error message, stack trace you see

**Any additional info**
Helpful info

**Comment by rajanadar** [comment]
hi @mohanakrishnans007 

What happens when you execute the following code?

```cs
IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
var _vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
{
BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
{
httpRequestMessage.Headers.Add("X-Vault-Namespace", vaultNamespace);
}
});

// Only for this first vault operation, VaultSharp will do a PKI Cert Login and get a Vault Token. ONCE.
var vaultResponse1 = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);

// For these 4 operations, VaultSharp will reuse the vault-Token fetched due to above call.
var vaultResponse2 = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);
var vaultResponse3 = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);
var vaultResponse4 = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);
var vaultResponse5 = await _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path, mountPoint);
```

@mohanakrishnans007  Are you saying, if you execute the above code, you are seeing VaultSharp generate 5 different vault tokens? It should be doing the login, only once.

Let me know.

**Comment by mohanakrishnans007** [comment]
@rajanadar HI , I checked the code you have provided its getting 1 token only and able to fetch secrets from different paths. 
But my scenario is that for every new transaction the entire code including the authentication runs which means a new token is generated every time / transaction while it fetches secret. How can we reuse the same token with in the same TTL for new transactions. Please let me know.

**Comment by rajanadar** [comment]
@mohanakrishnans007, you should be initializing the vault client only once. It is supposed to be used/injected as a singleton instance.

Once you do that, you can do any number of transactions using that same vault client instance, and it'll always use the same token. 

Conversely, every time you create anew or reinitialize the vault-client instance, every time it'll fetch a new vault token as well.

So if you notice my code snippet, I initialize vault client once, and then use the same instance everywhere.

**Comment by mohanakrishnans007** [comment]
@rajanadar  Could you please provide a sample or any documentation of using singleton instance of the VaultClient object in VaultSharp ? which will be very helpful. Thanks!

**Comment by rajanadar** [comment]
@mohanakrishnans007

VaultSharp is a library and has no concept of singleton. It depends on your host application. 

Do you have a asp.net web application? Or a windows form app? The singleton implementation depends on your app, the injection framework you are using etc.

**Comment by mohanakrishnans007** [comment]
@rajanadar Hi Raja, Mine is Web API (ASP.NET Web Appln) we use Simple Injector .Thanks!

**Comment by rajanadar** [comment]
hi @mohanakrishnans007 

You can do it as follows by:

1. Having a method dedicated to creating a vault instance
2. Providing this method as a Func to the Simple Injector Container's register method and provide singleton as the lifecycle.

```cs

private IVaultClient CreateVaultClient()
{
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

ServicePointManager.ServerCertificateValidationCallback +=
(sender, cert, chain, error) =>
{
    _logger.Trace("Server Certificate Validation Error: " + error.ToString());
    return true;
};

// Certificate(TLS) Auth Method
var certificate = new X509Certificate2(fetchCertificate);
IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);

IVaultClient vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
{
    BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
    {
        httpRequestMessage.Headers.Add("X-Vault-Namespace", vaultNamespace);
    }
});

return vaultClient;
}

// in your Simple Injector DI Container registrations, add this
container.Register<IVaultClient>(CreateVaultClient, SimpleInjector.Lifestyle.Singleton);

```

Now  any class in your application that needs IVaultClient can get it as a singleton. All you need to do it have IVaultClient as a constructor parameter in that class, and have your class be part of Simple Injector as well.

Please note that none of the above is VaultSharp specific. It is all about Web API and Simple Injector and DI and Singletons and DI instances created using factory methods.

**Comment by rajanadar** [comment]
Also unrelated to the issue, btw, if you are using the latest version of VaultSharp, you don't need to do this

```cs

            BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
            {
                httpRequestMessage.Headers.Add("X-Vault-Namespace", vaultNamespace);
            }

```

`VaultClientSettings` now supports a `Namespace` property that you can set, and VaultSharp will take care of setting the namespace http header for you. You don't need to use the delegate.

**Comment by mohanakrishnans007** [comment]
Hi @rajanadar , I will try this and let you know, this is very helpful . Thank you so much.

**Comment by mohanakrishnans007** [comment]
Hi @rajanadar  I have made the changes that you have suggested for VaultClient used as Singleton. Now what is happening is for example TTL - 1 minute or 60 seconds, for multiple transactions 1 token was only generated and we could able to fetch secrets. But when the TTL of the token expires we are not able to retrieve secret its is throwing 403 - Permission denied error.
How can we get the new token after the TTL expired?  Thanks!

**Comment by rajanadar** [comment]
Hi @mohanakrishnans007

Please see https://github.com/rajanadar/VaultSharp/pull/161

VaultSharp doesn't auto renew tokens. It is the responsibility of the host app to keep track of ttl. VaultSharp provides a

`Auth Info.ResetToken` method to force vault sharp to fetch a new token. You can invoke this method when the ttl expiry event is handled by you.
