### ISSUE TITLE
How can we get the new token after the TTL expired?

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#174]
Hi @rajanadar I have made the changes that you have suggested for VaultClient used as Singleton(https://github.com/rajanadar/VaultSharp/issues/173). Now what is happening is for example TTL - 1 minute or 60 seconds, for multiple transactions 1 token was only generated and we could able to fetch secrets. But when the TTL of the token expires we are not able to retrieve secret its is throwing 403 - Permission denied error.
How can we get the new token after the TTL expired? Thanks!

**Comment by rajanadar** [comment]
Please see

https://github.com/rajanadar/VaultSharp/issues/173#issuecomment-757963387

**Comment by mohanakrishnans007** [comment]
HI @rajanadar ,
I could see ResetToken() method in the link that you have provided. Could you please let me know where we need to use this in my scenario? any sample or any documentation available? Thanks!
