### ISSUE TITLE
Invalid Url Exception not handled with Status code

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#175]
**Describe the bug**
Invalid Url Exception not handled with status code, If i we use a invalid url for example https:// <invalidurl:8200> We are getting the below
unhandled exeption

![invalidUrl](https://user-images.githubusercontent.com/75024937/104614627-5530db80-5680-11eb-92f8-541a554bb0f5.JPG)

Same if I pass a invalid namespace the exception is handled with a error **StatusCode** 400 as below which I am using for Exception handling.
![namespaceerror](https://user-images.githubusercontent.com/75024937/104615080-c7092500-5680-11eb-826c-c6020ba23e69.JPG)

Could you please handle the Invalid Url Exception with proper error **Status Code** so that it will be useful for Error or Exception handling. Since in my project we are returning custom Error Code and Error Message with the error **Status Code** returned from Vault Server. Thanks!

**VaultSharp Version**
VaultSharp 1.6.0.2

**Vault Version**
1.5.3

**Does this work with Vault CLI?**
Yes/No

**Sample Code Snippet**
`catch (Exception exception)
            {                
                return new VaultServerResponse
                {
                    Errors = new List<Error>
                    {
                        new Error
                        {
                            ErrorCode = ((VaultSharp.Core.VaultApiException) exception).StatusCode.ToString()
                        }
                    }
                };
            }`

**Exception Details/Stack Trace/Error Message**
The remote server returned an error: 403 forbidden

**Any additional info**
Helpful info

**Comment by rajanadar** [comment]
hi @mohanakrishnans007 , this is not something VaultSharp manufactures. The code comes from Vault Server and the library just relays to you.
