### ISSUE TITLE
We are getting 403 forbidden error, instead of Error Code 404 for invalid path

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#176]
**Describe the bug**
As per the Vault API documentation present in https://vaultproject.io/api-docs its defined in HTTP Status codes section that vault will send a 404 in case of Invalid path, but in our case we are getting a 403 forbidden error from Vault Sharp, could you please check on this and return 404 error code. Thanks!
Example:
Mountpoint - Correct
Path - invalid Path (instead of "test" i am passing as "testttttttt")

Status Code : 403 Forbidden error
Message:
{"errors":["1 error occurred:\n\t* permission denied\n\n"]}

![invalidpatherror](https://user-images.githubusercontent.com/75024937/104910784-beb33180-5981-11eb-9842-e78593086d00.JPG)

**VaultSharp Version**
VaultSharp 1.6.0.2

**Vault Version**
1.5.3

**Does this work with Vault CLI?**
Yes/No

**Sample Code Snippet**
catch (Exception exception) { return new VaultServerResponse { Errors = new List<Error> { new Error { ErrorCode = ((VaultSharp.Core.VaultApiException) exception).StatusCode.ToString() } } }; }

**Exception Details/Stack Trace/Error Message**
Actual:
Status Code : 403 Forbidden error
Message:
{"errors":["1 error occurred:\n\t* permission denied\n\n"]}

Expected:
Status Code : 404 Not Found

**Any additional info**
https://vaultproject.io/api-docs

**Comment by rajanadar** [comment]
@mohanakrishnans007

VaultSharp doesn't manufacture its own http status code. It merely relays what it got from the vault server. Vault server is sending the 403 status code.

P.s. Please ensure that you are still sending the right vault token etc.
