### ISSUE TITLE
TOTP.ReadAllKeysAsync() always returns InvalidOperationException()

### ISSUE THREAD

**Issue by friedkiwi** [rajanadar/VaultSharp#179]
**Describe the bug**
TOTP.ReadAllKeysAsync() always returns InvalidOperationException()

**VaultSharp Version**
The version of VaultSharp package being used

**Vault Version**
1.6.0.2

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**

    IAuthMethodInfo authMethod = new TokenAuthMethodInfo(Properties.Settings.Default.VaultToken);
    var vaultClientSettings = new VaultClientSettings(Properties.Settings.Default.VaultURL, authMethod);
    IVaultClient vaultClient = new VaultClient(vaultClientSettings);
    Secret<ListInfo> keys = await vaultClient.V1.Secrets.TOTP.ReadAllKeysAsync();

**Exception Details/Stack Trace/Error Message**
I receive an InvalidOperationException telling me that the operation is invalid.

**Any additional info**
N/A

**Comment by rajanadar** [comment]
thanks @friedkiwi

**Comment by friedkiwi** [comment]
No worries - when will this change be pushed to the nuget repositories?

**Comment by rajanadar** [comment]
today

**Comment by rajanadar** [comment]
here you go @friedkiwi 

https://www.nuget.org/packages/VaultSharp/1.6.0.3

Let me (yourself :)) know if any issues.
