### ISSUE TITLE
Missing information from lookup-self

### ISSUE THREAD

**Issue by Ginja** [rajanadar/VaultSharp#18]
From my testing it appears the data returned from running `await this.Client.GetCallingTokenInfoAsync();`  should include the token's accessor, ttl, & creation time underneath its Data field:

What's available [now](https://github.com/rajanadar/VaultSharp/blob/9ce8d4bc5758640151cce6c6de7c83ba4c18672b/src/VaultSharp/Backends/Authentication/Models/Token/TokenInfo.cs):

![image](https://cloud.githubusercontent.com/assets/1631363/21830328/c807ce88-d750-11e6-81e3-0bd774485815.png)

What's returned via the `lookup-self` API:

```bash
curl --tlsv1.2 -X GET -H "X-Vault-Token:REDACTED" "https://x.x.x.x/v1/auth/token/lookup-self"
```

```json
{
  "request_id": "REDACTED",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "accessor": "REDACTED",
    "creation_time": 1484093665,
    "creation_ttl": 3600,
    "display_name": "approle",
    "explicit_max_ttl": 0,
    "id": "REDACTED",
    "meta": {
      "key": "value"
    },
    "num_uses": 0,
    "orphan": true,
    "path": "auth/approle/login",
    "policies": [
      "default"
    ],
    "renewable": true,
    "ttl": 3655
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Comment by rajanadar** [comment]
thanks @Ginja for crisply calling out the expected vs. actual.
fixed the bug.

was thrown off by Vault's documentation site showing the following stale format.
https://www.vaultproject.io/docs/auth/token.html

![image](https://cloud.githubusercontent.com/assets/376958/21839278/c2178c12-d78b-11e6-956c-d8e5bdcdf749.png)


have sent a PR for the Vault team as well. 
https://github.com/hashicorp/vault/pull/2258

**Comment by Ginja** [comment]
Thanks for such a quick fix, @rajanadar!

I haven't tested anything yet, but just looking at your changes (note, I am rusty with C#). Would it still return the Token ID underneath the `Data` field? I don't see the field in either of the `CallingTokenInfo.cs` or `TokenAccessorInfo.cs` classes.

**Comment by rajanadar** [comment]
The TokenAccessorInfo itself has a base class TokenInfo, which has the Id field along with some others.

**Comment by Ginja** [comment]
Right! Missed that.

Thanks again.

**Comment by rajanadar** [comment]
@Ginja  VaultSharp 0.6.4 is now live. please go get it to see this fix!

**Comment by Ginja** [comment]
Sorry I should have posted back. Once you merged it, I forked your repo, built the latest solution, & manually referenced it in my project. Works beautifully! Thank you for the quick response.

**Comment by rajanadar** [comment]
very cool.
