### ISSUE TITLE
Error when using namespace for CRUD secrets not when requesting a token

### ISSUE THREAD

**Issue by ImeneBoussour** [rajanadar/VaultSharp#183]
I am using VaultSharp for keyvalue secret management, here is a sample code for reading a secret:

`Dim authMethod As New LDAPAuthMethodInfo("username", "password")
        Dim vaultClientSettings As New VaultClientSettings("url", authMethod)
        vaultClientSettings.Namespace = "my/namespace"
        vaultClientSettings.UseVaultTokenHeaderInsteadOfAuthorizationHeader = True
        Dim VaultClient As New VaultClient(vaultClientSettings)
        Dim secret = VaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("net/myapp/dev").Result`

We need the namespace only for reading/writing a secret, not for requesting a token. If I use the namespace the request token fails with a bad request and if I remove it the read secret fails with access denied (as it tries to access something at the root).
How can I specify the namespace only for secret call?

**Comment by rajanadar** [comment]
hi @ImeneBoussour 

Very interesting that the namespace header causes issues with your LDAP login. Here is the solution you can use to solve your problem. Let me know.

Gist of the solution is that, VaultSharp allows customization of your HttpRequestMessage just before it makes a call to the Vault Api. We are adding a delegate to remove the namespace header, just for the login call.

```

Dim authMethod As New LDAPAuthMethodInfo("username", "password")

Dim vaultClientSettings As New VaultClientSettings("url", authMethod)

' 1. Remove/Comment this line  #raja
' vaultClientSettings.Namespace = "my/namespace"

vaultClientSettings.UseVaultTokenHeaderInsteadOfAuthorizationHeader = True

' 2. Add a custom delegate that will remove the namespace header 
' just for the login call #raja
vaultClientSettings.BeforeApiRequestAction = Sub(httpClient As HttpClient,
                                                    message As HttpRequestMessage)

                                                    ' Remove the added X-VaultNamespace header if it is a login call.
                                                    If Not message.RequestUri.AbsoluteUri.Contains("/login") Then
                                                        message.Headers.Remove("X-Vault-Namespace")
                                                    End If

                                                End Sub

Dim VaultClient As New VaultClient(vaultClientSettings)
Dim secret = VaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("net/myapp/dev").Result

```

**Comment by ImeneBoussour** [comment]
This worked
