### ISSUE TITLE
AWS Auth Method IAM new IAMAWSAuthMethodInfo signature ambigious

### ISSUE THREAD

**Issue by gh204689** [rajanadar/VaultSharp#185]
**Describe the bug**
AWS Auth Method IAM new IAMAWSAuthMethodInfo signature ambigious

**VaultSharp Version**
The version of VaultSharp package being used
1.6.2.1
**Vault Version**
The version of Vault server being used
n\a

**Does this work with Vault CLI?**
Yes/No

**Sample Code Snippet**
As per the readme of the AWS Auth Method IAM  C# code example

            // Step 4: Setup the IAM AWS Auth Info.

            var nonce = "1234";
            var roleName = "role-bastion";

            IAuthMethodInfo authMethod = new IAMAWSAuthMethodInfo(nonce, roleName, base64EncodedIamRequestHeaders);

This doesn't compile as there's no matching signature in IAMAWSAuthMethodInfo, which has these two...

 public IAMAWSAuthMethodInfo(string requestHeaders, string httpRequestMethod = "POST", string requestUrl = "aHR0cHM6Ly9zdHMuYW1hem9uYXdzLmNvbS8=", string requestBody = "QWN0aW9uPUdldENhbGxlcklkZW50aXR5JlZlcnNpb249MjAxMS0wNi0xNQ==", string nonce = null, string roleName = null);

  public IAMAWSAuthMethodInfo(string mountPoint, string requestHeaders, string httpRequestMethod = "POST", string requestUrl = "aHR0cHM6Ly9zdHMuYW1hem9uYXdzLmNvbS8=", string requestBody = "QWN0aW9uPUdldENhbGxlcklkZW50aXR5JlZlcnNpb249MjAxMS0wNi0xNQ==", string nonce = null, string roleName = null);

So the sample can't be used, can you suggest what should be in the request body and url or update the code snippet please?

Regards
Graeme

**Comment by rajanadar** [comment]
Updated the docs to use named parameters

``` 
IAuthMethodInfo authMethod = new IAMAWSAuthMethodInfo(nonce: nonce, roleName: roleName, requestHeaders: base64EncodedIamRequestHeaders);
```

**Comment by gh204689** [comment]
Thanks for the quick response, much appreciated.

I can confirm this now works as expected

Regards
Graeme

From: Raja Nadar ***@***.***>
Sent: 25 March 2021 01:17
To: rajanadar/VaultSharp ***@***.***>
Cc: Hunter, Graeme [GB-GB] ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [rajanadar/VaultSharp] AWS Auth Method IAM new IAMAWSAuthMethodInfo signature ambigious (#185)


CAUTION: This email originated from outside of Leidos. Be cautious when clicking or opening content.

Updated the docs to use named parameters

IAuthMethodInfo authMethod = new IAMAWSAuthMethodInfo(nonce: nonce, roleName: roleName, requestHeaders: base64EncodedIamRequestHeaders);
