### ISSUE TITLE
Change application configs on the fly without reloading an application

### ISSUE THREAD

**Issue by artem-avanesov** [rajanadar/VaultSharp#190]
I want to get rid of "appsettings.json" and store application configs in the HashiCorp Vault, it would be nice if this library could "inject" new application configs on the fly without reloading an application.

I imaging it to work like Redis pub/sub, when some data changes, all subscribed parties are notified.

Can this library do this?

Thanks in advance.

**Comment by rajanadar** [comment]
no @artem-avanesov . It can't. Also, it is not intended to.

This library is intended to be a helper library to access Vault APIs to manage secrets. Non-secret config, pub/sub, client failover etc. have been deliberately kept outside the scope of the library.
