### ISSUE TITLE
Permission Denied with AppRoleMethodInfo

### ISSUE THREAD

**Issue by elnoppo** [rajanadar/VaultSharp#191]
**Describe the bug**
With vaultClient and authentication Approle I get always permission denied. When I use the VaultClient to LogIn immediately (PerformImmediateLogin) and use this Token with a HTTPclient it Works. 
I am using KV engine in Version 2.
KV(v2) engine has the name kv
The path to one of my secrets is 1.
(kv/1)

**VaultSharp Version**
1.6.2.1

**Vault Version**
1.7.0 on a Server / 1.7.1 locally (Problem is the same on both versions)

**Does this work with Vault CLI?**
Yes. 
With the Vault CLI I am able to generate an clientToken for this Approle, use this clienttoken for login in Vault UI and see the keys. I have access to the keys.
It works over Postman with the generated clientToken. I can GET the keys. 
(GET http://localhost:6543/v1/kv/data/1)
It works with plain HTTPClient in .NET when I am using a generated ClientToken and set the X-Vault-Token Header. 
(HttpResponseMessage r = await client.GetAsync("http://localhost:6543/v1/kv/data/1");)

**Sample Code Snippet**
THIS does not work.
IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo("roleId", "secretId");
var vaultClientSettings = new VaultClientSettings("http://localhost:6543", authMethod);
IVaultClient vaultClient = new VaultClient(vaultClientSettings);
Secret<SecretData> kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("kv/1");
Secret<SecretData> kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("kv/data/1");
Secret<SecretData> kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("1");
Secret<SecretData> kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("kv");
(all this paths end in Permission denied)

THIS does work.
IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo("roleId", "secretId");
var vaultClientSettings = new VaultClientSettings("http://localhost:6543", authMethod);
IVaultClient vaultClient = new VaultClient(vaultClientSettings);
await vaultClient.V1.Auth.PerformImmediateLogin();
string s = authMethod.ReturnedLoginAuthInfo.ClientToken.ToString();

HttpClient client = new HttpClient();
client.DefaultRequestHeaders.Add("X-Vault-Token", s);
HttpResponseMessage r = await client.GetAsync("http://localhost:6543/v1/kv/data/1");
r.EnsureSuccessStatusCode();
string responseBody = await r.Content.ReadAsStringAsync();

**Exception Details/Stack Trace/Error Message**
Permission Denied
{"errors":["1 error occurred:\n\t* permission denied\n\n"]}

**Comment by niventc** [comment]
I think this might be to do with the mountpoint of the KV V2 engine, it defaults to `kv-v2` (see https://github.com/rajanadar/VaultSharp/blob/0c1c849080ed1fd0fc202963c26a3aee7909b377/src/VaultSharp/V1/SecretsEngines/SecretsEngineMountPoints.cs#L22), which I believe means you're essentially requesting "http://localhost:6543/v1/kv-v2/data/1".

Does it work if you do the following?

`Secret kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("1", mountPoint: "kv");`

If that works and you wanted to override the mountPoint globally, I recently raised a PR to support this (see https://github.com/rajanadar/VaultSharp/pull/187), it's pending release though so you'll need to do the above for the time being.

**Comment by rajanadar** [comment]
@elnoppo  Please let us know if you still see the issue.

**Comment by elnoppo** [comment]
Thank you very much. With this described by niventc it works.
