### ISSUE TITLE
Couldn't access secrets under Cloud foundry backends shared path

### ISSUE THREAD

**Issue by rv-bc** [rajanadar/VaultSharp#195]
**Describe the bug**
Couldn't access  Cloud foundry backends shared path using the system or key-value calls.

The app is bound with Vault-broker services. It has the following environment variables that show the path where secrets can be stored and retrieved. 

     "backends_shared": {
      "application": "cf/xxxxx-xxxx-xxxx-xxx-xxxx/secret",
      "organization": "cf/xxxxx-xxxx-xxxx-xxx-xxxx/secret",
      "space": "cf/xxxxx-xxxx-xxxx-xxx-xxxx/secret"
     }

VaultSharp Version
The version of VaultSharp package being used: 1.6.03

**Vault Version**
The version of Vault server being used: 1.5.5

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**
Non-confidential snippet of code:
We have tried the below steps. But not working. Please advise.

      //var _secrets1  = await client.V1.Secrets.KeyValue.V1.ReadSecretAsync("/secret/cf/xxxx-xxxx-xxx-xxx-xxx/secret/my-job");
      // var _secrets1 = await client.V1.Secrets.KeyValue.V2.ReadSecretAsync("/cf/xxxxx-xxx-xxx-xxx-xxx/secret/my-job", 0, "secret");
      //var _secrets1 = await client.V1.System.ReadRawSecretAsync("/cf/xxx-xxx-xxx-xxx-xxx/secret/my-job");
      //var _secrets1 = await client.V1.System.ReadRawSecretAsync("/v1/cf%xxx-xxx-xx-xxxxx-xxxx/secret/my-job");
      //var _secrets1 = await client.V1.System.ReadRawSecretAsync("secret/raw/cf/xxx-xxx-xxx-xxxx-xxx/secret/my-job");

**Exception Details/Stack Trace/Error Message**
Error message, stack trace you see
One or more errors occurred. ({"errors":["1 error occurred:\n\t* permission denied\n\n"]}
)'VaultApiException: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}

**Any additional info**
Helpful info
I was able to retrieve secrets under the same path using API.
https://xxx.vault.xxx-cloud.uk:xxxx/v1/cf/axxxxx-xxxx-xxxx-xxx-xxxxx12345/secret/my-job

**Comment by rajanadar** [comment]
@rv-bc

Can you please provide more C# code on the Auth Info setup?

Also, can you provide the vault cli commands you used, that works for you?

**Comment by rv-bc** [comment]
Hi Raja,  Thank you for the quick response. 

 var env = Environment.GetEnvironmentVariable("VCAP_SERVICES", EnvironmentVariableTarget.Process);
            var vault = (JObject)JsonConvert.DeserializeObject<JObject>(env)["hashicorp-vault"][0];
            var vcapSettings = JsonConvert.DeserializeObject<VCapSettings>(vault.ToString());

            IAuthMethodInfo authMethod = new TokenAuthMethodInfo(vaultToken: vcapSettings.credentials.auth.token);
            var vaultClientSettings = new VaultClientSettings(vcapSettings.credentials.address, authMethod)
            {
                ContinueAsyncTasksOnCapturedContext = false
            };
            var client = new VaultClient(vaultClientSettings);
           // var _secrets = await client.V1.Secrets.Cubbyhole.ReadSecretAsync(secretPath: "my-job"); // working set 
         //var _secrets1 = await client.V1.System.ReadRawSecretAsync("secret/raw/cf/xxx-xxx-xxx-xxxx-xxx/secret/my-job");
          return _secrets.Data;

Cli command : vault read /cf/xxx-xxx-xxx-xxxx-xxx/secret/my-jo

**Comment by rajanadar** [comment]
Assuming that your token is 100% valid and has permissions, the path to the secret is probably messed up.

Do you know your mount point for your kv1 secret backend? It is by default, "kv". Have you customized it?

From your URL, ```https://xxx.vault.xxx-cloud.uk:xxxx/v1/cf/axxxxx-xxxx-xxxx-xxx-xxxxx12345/secret/my-job```, it looks like the default **kv** mount point has been customized. Else, the URL would have contained a **kv** value in it. Also, you are using kv version 1. Else, the url would contain a **/data** since that is needed for reading a kv2 secret.

So assuming token is valid, and secret store is kv1, you need to provide the mountpoint and just the secret path as 2 separate parameters.

E.g. Reverse engineering your URL ```https://xxx.vault.xxx-cloud.uk:xxxx/v1/cf/axxxxx-xxxx-xxxx-xxx-xxxxx12345/secret/my-job```, what you need to try is:

```await client.V1.Secrets.KeyValue.V1.ReadSecretAsync("secret/my-job", mountPoint: "cf/xxxx-xxxx-xxx-xxx-xxx");```

Here, your mount point is ```cf/xxxx-xxxx-xxx-xxx-xxx``` and path/key for secret is ```secret/my-job```.
The Vault CLI needs both of them together. 

Try the above and let me know.

**Comment by rv-bc** [comment]
@rajanadar  Thank you again. It works. Let me deploy in the CF and get back to you.
