### ISSUE TITLE
README Inaccurate for ReadSecretAsync

### ISSUE THREAD

**Issue by JoshuaLyle** [rajanadar/VaultSharp#196]
**Describe the bug**
The README example for ReadSecretAsync does not work as of v0.11

**Sample Code Snippet**
The readme specifies this example for ReadSecretAsync
`KeyValue.V2.ReadSecretAsync("secret-name");`

However this comment shows the correct way to do it  which should be in the README instead https://github.com/rajanadar/VaultSharp/issues/86#issuecomment-507841211

`KeyValue.V2.ReadSecretAsync("database-definitions/test", null, "secret");`

**Comment by rajanadar** [comment]
thanks @JoshuaLyle . made the doc update at the 2 places
