### ISSUE TITLE
having some syntax issues creating a web method.

### ISSUE THREAD

**Issue by schall8** [rajanadar/VaultSharp#2]
Hello, i've been trying to create a web method to pull account configuration from our vault configuration.

This is a sample secret
$ vault read VSMapi/auth
Key             Value
lease_duration  2592000
account         $vsmgrpmgr002@auth.hpicorp.net
dn              DC=auth,DC=hpicorp,DC=net
domain          auth.hpicorp.net
path            OU=SRPA,OU=Groups,OU=Enclave,DC=auth,DC=hpicorp,DC=net

my C# code

how i Instantiate the object

                IVaultClient administrativeVaultClient = VaultClientFactory.CreateVaultClient(new Uri("http://0.0.0.0:8200"), 
                    new VaultSharp.Backends.Authentication.Models.Token.TokenAuthenticationInfo(token: "root token"));

This is the web method
            public string TestReadVault(string path)
            {
               
               ArrayList data;

               var secret = administrativeVaultClient.ReadSecretAsync(path);
               data = secret.Data; // this is the original dictionary back.
            
               string result = string.Join(",", data.ToArray());
               
               return result;

            }

I am getting the error on the data = secret.Data

It doesn't like the .Data

Also I am a perl guy C# isn't my friend.  My goal is a proof a concept if we can pull the domain configurations for our .NET web service from the VAULT.  If I can get this working i will switch it from the root token to an application role token.  I'm just trying to see if this will work for us at all.  Any guidance or help would be much appreciated.

'System.Threading.Tasks.Task<VaultSharp.Backends.System.Models.Secret<System.Collections.Generic.Dictionary<string,object>>>' does not contain a definition for 'Data' and no extension method 'Data' accepting a first argument of type 'System.Threading.Tasks.Task<VaultSharp.Backends.System.Models.Secret<System.Collections.Generic.Dictionary<string,object>>>' could be found (are you missing a using directive or an assembly reference?)	C:\data\vsm_sandbox\VSM\home\vsm_win\VSMapi_csharp\VSMapiCore\VSMapiCore\VSMapiCore.cs	128	30	VSMapiCore

**Comment by rajanadar** [comment]
hello @schall8 

ReadSecretAsync is an asynchronous method.. (kind of like promises in Perl I think!)
so the output of ReadSecretAsync is not the data but a promise for the data. Hence the compile error.

There are 2 ways to solve the problem.. 

1. you could make your whole method asynchronous in C# as follows:

Note the method definition using the 'async' keyword, and the ReadSecretAsync call using the 'await' keyword.

```
public async string TestReadVault(string path)
{
           var secret = await administrativeVaultClient.ReadSecretAsync(path);
           var data = secret.Data; // this is the original dictionary back.

           foreach(KeyValuePair<string, object> kv in data)
           {
             // kv.Key will contain the keys for your configuration.. e.g. 'account', 'dn', 'domain' etc.
            // kv.Value.ToString() will contain the values of the keys. e.g. 'auth.hpicorp.net' etc.
           }

      // build the string you want to return using the for loop above.
 
      // it maybe even beneficial to return the dictionary as-is, since a dictionary is
      // easier to work with for a caller, than to parse a monolithic string..
 }
```

The above method is the most recommended method. (using async/await)

2. The other way to go, if you don't want to use async/await is to invoke the API in a synchronous manner.

```
public string TestReadVault(string path)
{
          // We use the Result property of the task to get the data from the promise.
          // Please note that it is not recommended under certain conditions
          // o use the .Result property
          // as it may result in deadlock etc.
          // but for a Quick prototype and just to get the tool working, you can try this.
          // please don't try in a production application.
          // the recommended pattern is #1.

           var secret = administrativeVaultClient.ReadSecretAsync(path).Result;

           var data = secret.Data; // this is the original dictionary back.

           foreach(KeyValuePair<string, object> kv in data)
           {
             // kv.Key will contain the keys for your configuration..
             // e.g. 'account', 'dn', 'domain' etc.
             
             // kv.Value.ToString() will contain the values of the keys. 
             // e.g. 'auth.hpicorp.net' etc.
           }

      // build the string you want to return using the for loop above.
 
      // it maybe even beneficial to return the dictionary as-is, since a dictionary is
      // easier to work with for a caller, than to parse a monolithic string..
 }
```

hope that helps with your effort.

**Comment by schall8** [comment]
Thank you for your help, it is helping.  The compiler doesn't like the string after async says i need it to be void, Task or Task<t>

**Comment by rajanadar** [comment]
oh yeah, sorry i forgot :) an async method returns a Task.

try this snippet:

```
public async Task<string> TestReadVault(string path)
{
           var secret = await administrativeVaultClient.ReadSecretAsync(path);
           var data = secret.Data; // this is the original dictionary back.

           foreach(KeyValuePair<string, object> kv in data)
           {
             // kv.Key will contain the keys for your configuration.. 
             // e.g. 'account', 'dn', 'domain' etc.
             // kv.Value.ToString() will contain the values of the keys. 
             // e.g. 'auth.hpicorp.net' etc.
           }

      // build the string you want to return using the for loop above.

      // it maybe even beneficial to return the dictionary as-is, since a dictionary is
      // easier to work with for a caller, than to parse a monolithic string..
 }
```

**Comment by rajanadar** [comment]
@schall8 did that solve your problem? please let me know and i'll close the issue.

**Comment by rajanadar** [comment]
@schall8 i am closing this issue. please let me know if you still see issues. happy to help.
