### ISSUE TITLE
0.6.5 - Batch transit operations

### ISSUE THREAD

**Issue by fproulx-pbox** [rajanadar/VaultSharp#20]
0.6.5 adds Batch Transit Operations
This would be super super useful for us - any chance you can catch up to 0.6.5 soon ?

**Comment by rajanadar** [comment]
sure @fproulx-pbox 

i'll catch up on 0.6.5 this weekend.. starting with batch transit, and then the other features (radius etc).
thanks for the request.

**Comment by rajanadar** [comment]
Will be solved as part of #48 since 0.10.x supports batch api out of the box.
