### ISSUE TITLE
Unsafe API

### ISSUE THREAD

**Issue by ezyuzin** [rajanadar/VaultSharp#200]
Use with carefull.
API have mem leaks in httprequest and httpresponse, process memdump display in memory all secret responses from vault.
Token strings saved in plain text and also can be compromised with memdump

![2021-07-17_111001](https://user-images.githubusercontent.com/3999766/126037686-578088d1-d474-4434-8300-13b276e56edb.png)

**Comment by rajanadar** [comment]
thanks @ezyuzin. This is a known concern with several API clients. At the start of the project, I debated between SecureString, Char Array vs. String etc. for core Auth method inputs, and also deserialization responses from Vault. In the end, dropped the idea for diminishing ROI. Access to RAM or machine, to get a memory dump is a bigger concern. It means, the malicious user can generate the Vault token, outside of VaultSharp anyways.

**Comment by rajanadar** [comment]
@ezyuzin  I am closing this issue. Thanks again for the interest and the find.
