### ISSUE TITLE
How to explicitly provide server cert to vaultsharp?

### ISSUE THREAD

**Issue by ImeneBoussour** [rajanadar/VaultSharp#203]
Hello,

I am trying to provide a server cert when connecting to vault through a custom HttpClientHandler (per a security requirement) and I am encountering issues.
.NET Framework 4.6.1
**option 1:**
Vaultsharp version 1.6.2.3
Code:
```
 vaultClientSettings.PostProcessHttpClientHandlerAction = (originalHttpClientHandler) =>
                    {
                        originalHttpClientHandler = new WebRequestHandler();
                        ((WebRequestHandler)originalHttpClientHandler).ClientCertificates.Add(new X509Certificate2("c:/bundle.crt"));
                        ((WebRequestHandler)originalHttpClientHandler).ServerCertificateValidationCallback =
                            (httpRequestMessage, cert, cetChain, policyErrors) =>
                            {
                                return true;
                            };
                        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                    };
```
Error:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Option 2:**
VaultSharp Version 1.6.5.1
Code:
```
vaultClientSettings.PostProcessHttpClientHandlerAction = httpClientHandler =>
                    {
                        httpClientHandler = new WinHttpHandler
                        {
                            ServerCertificateValidationCallback =
                            (httpRequestMessage, cert, cetChain, policyErrors) =>
                            {
                                return true;
                            },
                            ClientCertificates.Add(new X509Certificate2("c:/bundle.crt"))
                        };
                        
                        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                    };
```
Error:
Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'. (from WinHHttpHandler )

Is this something you can help with?

**Comment by rajanadar** [comment]
@ImeneBoussour  what are you trying to achieve?

I am guessing, it is not Vault-Certificate-Auth, is it? Let me know your auth-method in any case.
https://github.com/rajanadar/VaultSharp/blob/master/README.md#certificate-tls-auth-method

If it is not cert-auth, and you just want to attach a certificate as part of vault-api request (for 2 way ssl i guess?) I think you have to attach a certificate with private key. So PFX typically. Are you sure your CRT file has a private key?

Check that first using this flag

``` new X509Certificate2("c:/bundle.crt").HasPrivateKey ```

Let me know

**Comment by rajanadar** [comment]
Let me know if still issues
