### ISSUE TITLE
Database.GetCredentialsAsync waits infinite

### ISSUE THREAD

**Issue by avikenjale** [rajanadar/VaultSharp#206]
**Describe the bug**
`Database.GetCredentialsAsync()` waits infinitely when called its `.Result`

**VaultSharp Version**
The version of VaultSharp package being used - 1.6.5.1

**Vault Version**
The version of Vault server being used - Not Sure

**Does this work with Vault CLI?**
Yes/No - Not sure

I have 2 .net applications - `Framework 461` - one is console app and another is web api. I have created a library which returns client based on `VaultClientURL` and profile sent.

When I can calling following line of code in Console application it works without wait time, and able to retrieve credentials.
```
public string[] GetVaultCredentials()
{
    var client = _vaultService.CreateVaultClient(AppConfig.SamlProfile, AppConfig.VaultClient);
    var creds =  client.V1.Secrets.Database.GetCredentialsAsync(AppConfig.SqlDatabaseRole).Result;

    return new string[] { creds.Data.Username, creds.Data.Password };
}
```
However, if above method is used in Web API - controller or following any layer (Business/ data access), `GetCredentialsAsync` line waits for infinitely and program just hangs there. 

However when used following method (async), it works as expected 
```
public async Task<string[]> GetVaultCredentialsAsync()
{
     var client = _vaultService.CreateVaultClient(AppConfig.SamlProfile, AppConfig.VaultClient);
     var creds = await client.V1.Secrets.Database.GetCredentialsAsync(AppConfig.SqlDatabaseRole);

     return new string[] { creds.Data.Username, creds.Data.Password };
}
```
Any idea why non-async method - with `'Result` is not working thru API but Console application?

**Comment by rajanadar** [comment]
hi @avikenjale 

You have hit a well-known issue with async/await in terms of deadlocks and waiting, especially in a Web Context.
Please see this: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Unfortunately, there isn't much VaultSharp can do here. The best it offers is a flag ```ContinueAsyncTasksOnCapturedContext``` in the ```VaultClientSettings``` class, that you can use to see if the issue goes away.

let me know.

**Comment by rajanadar** [comment]
Closing this. Let me know if anything.
