### ISSUE TITLE
System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

### ISSUE THREAD

**Issue by Leemool** [rajanadar/VaultSharp#207]
Hello,

When i try to use :
vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(something).GetAwaiter().GetResult();

I allways get this error :
System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

Is there an issue about my VaultClientSettings?
var vaultClientSettings = new VaultClientSettings("https://url:8200", authMethod)
            {
                Namespace = "mynamespace",
                MyHttpClientProviderFunc = handler => new HttpClient(handler)              
            };
            
I try to add proxy url ,but i don't know how to do.

Thx in advance
Regards

**Comment by rajanadar** [comment]
I see https. Is your ssl certificate trusted publicly?

**Comment by Leemool** [comment]
Trusted i'm pretty sure . 
Publicly not sure.
How can i find this particularity?

I'm not sure to understand well, so sorry for my maybe  bad knowledge about this subject

**Comment by rajanadar** [comment]
An ssl certificate has to be publicly trusted for the code to accept it. Without it, you'll get a non-trusted-ssl-cert error.

Are you able to connect and do the same operation via the vault cli or using curl/postman?

**Comment by rajanadar** [comment]
Apply this to debug ssl errors.
https://stackoverflow.com/a/56460131/1174414

Please don't use it in prod.

**Comment by Leemool** [comment]
Via vault cli i have no issue:
vault login s.q6DZF60Jrob8f7BcGUL9bnBW
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

I did not try with curl/postman. I will try

Thx for your help

**Comment by Leemool** [comment]
With curl it's ok

`curl     -H "X-Vault-Token: s.q6DZF60Jrob8f7BcGUL9bnBW" -H "X-Vault-Namespace: mynamespace"     -X GET     https://url.com:8200/v1/kv1/toto`

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   181  100   181    0     0    427      0 --:--:-- --:--:-- --:--:--   428{"request_id":"291f5697-a057-3328-d33e-58a687c4ec2f","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"key":"pass"},"wrap_info":null,"warnings":null,"auth":null}

**Comment by rajanadar** [comment]
Got it. Thanks for the quick responses.

Can you paste your VaultSharp C# code in full? (strike out sensitive info)

Also, have this code before you invoke vaultsharp and let me know what the ```sslPolicyErrors``` variable says?
And have that method (which temporarily tells dot net to ignore any ssl cert issues) and tell me if you still see the issue.

```
ServicePointManager
    .ServerCertificateValidationCallback += 
    (sender, cert, chain, sslPolicyErrors) =>
    {
     // what does the  sslPolicyErrors variable say?
     return true;
    }
``` 

Also, you don't need to set httpclientprovider

```
var vaultClientSettings = new VaultClientSettings("https://url:8200", authMethod)
{
Namespace = "mynamespace"
 // MyHttpClientProviderFunc = handler => new HttpClient(handler)  // not needed
};
```

**Comment by Leemool** [comment]
Thanks for taking time to help me :)

Here my code now, what can i add?
```
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) =>
                {
                    // what does the  sslPolicyErrors variable say?
                    return true;
                };

            IAuthMethodInfo authMethod = new TokenAuthMethodInfo("s.q6DZF60Jrob8f7BcGUL9bnBW");

            var vaultClientSettings = new VaultClientSettings("https://url.com:8200", authMethod)
            {
                Namespace = "mynamespace",
            };

            IVaultClient vaultClient = new VaultClient(vaultClientSettings);
            var kv2Secret = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("/v1/kv1/toto").GetAwaiter().GetResult();
```

it failed after this last command and here is the error message in totality:

_-> System.Net.Http.HttpRequestException: An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeRequestAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValueSecretsEngineV2Provider.<ReadSecretAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()_
-> System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

**Comment by rajanadar** [comment]
Use the following line and let me know.

```
var kv2Secret = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("toto", mountPoint: "kv1").Result;
```

If the above doesn't work, then try this.

```
var kv2Secret = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("kv1/toto").Result;
```

Basically, the mountPoint and secret path are 2 different things. And you don't need the absolute prefix of "v1/". That's the vault api version, and VaultSharp adds that automatically.

Nit. Not my business, but you are reading the secret from a kv version 1 store, and your variable is named kv2.

**Comment by Leemool** [comment]
Hello,

so:
```
var kv2Secret = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("toto", mountPoint: "kv1").Result;   =>KO
var kv2Secret = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("kv1/toto").Result;   =>KO
```

In another log i see after: System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR
"The time limit for the operation has passed."

> Nit. Not my business, but you are reading the secret from a kv version 1 store, and your variable is named kv2.
Yes i know , i tried with kv2 for tests but it was the same behavior.

Thanks

**Comment by rajanadar** [comment]
A timeout indicates connectivity issues or deadlock.

If you are using the same vault url, that works in cli and curl, from the same machine that has the VaultSharp code, then url is alright. Url is reachable.

To confirm on any deadlock or wait issues with async code, can you tell me if you are running the code in a web app? If yes, can you try it in a console app? (basically a non web app and let me know)

**Comment by rajanadar** [comment]
What is K0?

**Comment by Leemool** [comment]
sorry KO = "knock out" :) 
I would say the same log => Error 12002 ...

I running the code with a special app

**Comment by rajanadar** [comment]
On the same machine, cli and curl works, but a dot net app using VaultSharp is not working, for the same url, same vault token, same mount point, same secret name...

That is strange.

Is it possible to know how is kv1 setup? How was it mounted etc.? Is it a KV version 1 or Version 2 secrets engine? And for sure, your url is https right? Not http? Because, I see port 8200 and normally https urls don't use 8200.

**Comment by Leemool** [comment]
The url is good ,https with port 8200.
When i change to another i have another error.

I note a strange behavior with cli .
I must set HTTPS_PROXY and VAULT_ADDR then i can login with oidc or token.
If i set namespace before login i can't login.


For the other thing:

```
C:\Users\toto>vault secrets list
Path                     Type                     Accessor                 Description
----                     ----            --------                              -----------
cubbyhole/    ns_cubbyhole    ns_cubbyhole_3e038347    per-token private secret storage
kv/                 kv                         kv_487345e6              Versioned key-value secret engine (v2)
kv1/               kv                         kv_778c9760              n/a
secret/           kv                         kv_c5cbcb24              Unversioned key-value secret engine (v1)
```




```
C:\Users\toto>vault kv get /kv1/toto
==== Data ====
Key      Value
---      -----
admin    pass

```


```
C:\Users\toto>vault kv get /kv/test2
====== Metadata ======
Key              Value
---              -----
created_time     2021-06-21T15:25:00.866852657Z
deletion_time    n/a
destroyed        false
version          1

====== Data ======
Key         Value
---         -----
test-user    test-pass
```

**Comment by Leemool** [comment]
trying without namespace with vaultsharp = same error... i will be crazy... :/

**Comment by rajanadar** [comment]
Namespace is not the problem. Proxy might be.
What dot net framework are you using? And what are your proxy url details? 

Try setting the proxy url in the http-client-handler delegate.

**Comment by Leemool** [comment]
Maybe the proxy yes, how can i do : Try setting the proxy url in the http-client-handler delegate?

I just try `await vaultClient.V1.Auth.PerformImmediateLogin();  
`
and i have the same error so i have an auth issue

**Comment by rajanadar** [comment]
Set your proxy like this

```
var vaultClientSettings = new VaultClientSettings("https://url.com:8200", authMethod)
{
    Namespace = "mynamespace",

    PostProcessHttpClientHandlerAction = (HttpMessageHandler httpMessageHandler) =>
    {
        // based on your dot net framework, the httpMessageHandler
        // could be of type HttpClientHandler (normally) or
        // WebRequestHandler (for .net 4.5) or WinHttpHandler (for .net 4.6+)

        var httpClientHandler = httpMessageHandler as HttpClientHandler;

        if (httpClientHandler != null)
        {
            httpClientHandler.UseProxy = true;
            httpClientHandler.Proxy = new WebProxy("[YOUR-PROXY-URL]"); // if your proxy needs credentials, add more parameters
        }
    }
};
```

**Comment by Leemool** [comment]
Hello

Better message issue i think:
VaultSharp.Core.VaultApiException: {"request_id":"f6a98610-185e-14fa-03a6-a1513304c78e","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."],"auth":null}



i use 
```

PostProcessHttpClientHandlerAction = (HttpMessageHandler httpMessageHandler) =>
                {
                    // based on your dot net framework, the httpMessageHandler
                    // could be of type HttpClientHandler (normally) or
                    // WebRequestHandler (for .net 4.5) or WinHttpHandler (for .net 4.6+)

                    var httpClientHandler = httpMessageHandler as WinHttpHandler;

                    if (httpClientHandler != null)
                    {
                        httpClientHandler.WindowsProxyUsePolicy = WindowsProxyUsePolicy.UseCustomProxy;
                        httpClientHandler.Proxy = new WebProxy("http://proxy/"); // if your proxy needs credentials, add more parameters
                    }
                }
                              
```

                I try a lot of path but it dos not work

**Comment by rajanadar** [comment]
This is progress. The timeout issue was due to proxy. So that's solved.

And your enumeration of ```vault secrets list``` tells us that, the paths ```kv1``` and ```secret``` are Version 1 of Key-Value Secret Engine. And the path ```kv``` is Version 2 of Key-Value Secret Engine.

So all of this should work. Let me know.

```
var kv1SecretFromFromKV1Path = vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("toto", mountPoint: "kv1").Result;

var kv2SecretFromFromKVPath = vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("test2", mountPoint: "kv").Result;
```

**Comment by Leemool** [comment]
Yes in my first post, that's was i talk about:
"I try to add proxy url ,but i don't know how to do." Thx you for the help for the proxy.

And finally it works with your last command with mountPoint, i think i did not read well the doc before so ... sorry

I just try  another thing without proxy , because on  the begining on my tests,   i had results like (  {"errors":[]}   ) with this:
```
var vaultClientSettings = new VaultClientSettings("https://url:8200", authMethod)
            {
                Namespace = "mynamespace ",
                MyHttpClientProviderFunc = handler => new HttpClient()      //without handler in HttpClient(handler)

            };

```
And this works too without proxy setup in c# code 


Thanks a lot for your patience !

ps

**Comment by rajanadar** [comment]
yes, you mentioned "proxy" in your first post itself. <smile />
Nice that it all works now. Cheers.

I'll close the issue.

**Comment by Leemool** [comment]
Okay thx a lot for you help  :) 

do not understand the real difference between :

`MyHttpClientProviderFunc = handler => new HttpClient(handler)   //on my first post `

and

`MyHttpClientProviderFunc = handler => new HttpClient()  // this works `


But it works now and i'm  happy

**Comment by rajanadar** [comment]
The only difference between the 2 lines is that when you do ```new HttpClient()```, .NET internally initializes the ```HttpClient``` with a ```HttpClientHandler``` (https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/HttpClient.cs#L132)

And when you do, ```new HttpClient(handler)```, the data type of the ```handler``` could be any of ```WebRequestHandler```, ```WinHttpHandler``` or ```HttpClientHandler```, due to this logic that depends on the .NET framework you're using.  (https://github.com/rajanadar/VaultSharp/blob/master/src/VaultSharp/Core/Polymath.cs#L37)

So it looks like when the handler is ```HttpClientHandler```, things work for you. But any other handler doesn't work.

**Comment by Leemool** [comment]
Thx for all again :)

Good bye
