### ISSUE TITLE
Missing client token VaultApiException when using AppRoleAuthMethoInfo

### ISSUE THREAD

**Issue by dbrighton** [rajanadar/VaultSharp#208]
I have the code that initializes my vault client

            var vaultAddr = "http://127.0.0.1:8200";
            var nameSpace= "/xyz/dev";
            var vaultRoleId = "ZSW7A8Z";
            var vaultSecretId = "37BCA754-0BAF-4915-81AB-197015B57EA6";

            var authMethod = new AppRoleAuthMethodInfo(moutPoint, vaultRoleId, vaultSecretId);
            var vaultClientSettings = new VaultClientSettings(vaultAddr, authMethod);

            _vaultClient = new VaultClient(vaultClientSettings);

     // this line throws "VaultApiException {"errors:["missing client token"]"}"    ​
     ​var secret = _vaultClient.V1.Secrets.KeyValue.V1.ReadSecreatAsync("JwtKey", nameSpace).Result;
	 
	 Note: When I run post commands using curl with the nameSpace, roleId and secretId from above it works fine.

What am I doning wrong?

**Comment by rajanadar** [comment]
@dbrighton 

The usage of namespace is incorrect. If your namespace is the vault namespace concept, then it needs to be provided as follows.
```
var vaultClientSettings = new VaultClientSettings(vaultAddr, authMethod) { Namespace = nameSpace };

// later
 var secret = _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("JwtKey", mountPoint: "[YOUR-KV1-PATH]").Result;
```

To find the mountpoint for your KV1 secret engine, let me know how you're accessing the same secret via CURL.
The mountpoint will be the value in the URL after, ```http://127.0.0.1:8200/v1``` and before ```/JwtKey```

**Comment by dbrighton** [comment]
I guess I'm confusing the mount point with namespace.   I'm not sure what "mountpint" needs to be.  I guess  I was passing in the namespace.

**Comment by rajanadar** [comment]
An key value engine is one of several secret engine supported by vault. As a consumer of vault, you are free to setup 100 buckets of key value engines. Each bucket is identified by its unique mount point.

E.g. Imagine when you plug in 4 USB drives to your computer. All are usbs. But they get their own drive names. MountPoint is that.

You could have a kv engine on /mykv1 mountPoint. Another one on /mykv2.

Show me your working curl url to read the secret and I'll tell you your mount point.

Normally, the person who sets up the kv engine for the first time knows the mountPoint. If nobody has setup the secret engine explicitly, then vault comes with its own default for certain engines. In that case, you can skip that parameter altogether in VaultSharp and VaultSharp will internally provide the expected default.

The problem with the current code is that, we instructed VaultSharp to feed in the mountPoint we specify but we are specifying a namespace.

Give me the working curl url.

**Comment by rajanadar** [comment]
If you want to use the default mountpoint ("secret" i think), just do this

``` ​var secret = _vaultClient.V1.Secrets.KeyValue.V1.ReadSecreatAsync("JwtKey").Result; ```

**Comment by rajanadar** [comment]
Hey, let me know if more issues.
