### ISSUE TITLE
412 Precondition Failed error - X-Vault-Forward: active-node need to be added in VaultClient 

### ISSUE THREAD

**Issue by mohanakrishnans007** [rajanadar/VaultSharp#209]
**Describe the bug**
From Vault we received 412 Precondition Failed error, to fix this from one of our API which is developed in APIC we used the request header which was suggested 
![image](https://user-images.githubusercontent.com/75024937/128713684-8f924405-b021-4def-a29c-58099aa2c666.png)
So from  our .NET Webapi end also its consumes Vault to retrieve secrets, we tried to add/ update this header but in Vault Sharp we find only Namespace header which can be configured. 

In order to have this **X-Vault-Forward: active-node** header to be added on the IClient Could you please advice/ update package.? 

**VaultSharp Version**
The version of VaultSharp package being used **Vault Sharp 1.6.0.2**

**Vault Version**
The version of Vault server being used- Problem occurred in Vault 1.7.1

**Does this work with Vault CLI?**
Yes/No

**Sample Code Snippet**
  // Certificate(TLS) Auth Method
            IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
            IVaultClient vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
            {
                Namespace = vaultNamespace,
                
            });
            return vaultClient;

**Exception Details/Stack Trace/Error Message**
 412 Precondition Failed

**Any additional info**
Helpful info

**Comment by rajanadar** [comment]
@mohanakrishnans007 

You can add custom headers to every outgoing http request, using the ```BeforeApiRequestAction``` delegate, as follows:

            IAuthMethodInfo authMethod = new CertAuthMethodInfo(certificate);
            IVaultClient vaultClient = new VaultClient(new VaultClientSettings(vaultUrl, authMethod)
            {
                BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
                    httpRequestMessage.Headers.Add("X-Vault-Forward", "active-node")
            });

            return vaultClient;

**Comment by rajanadar** [comment]
That should solve your issue. Let me know if you encounter any other issues.

**Comment by mohanakrishnans007** [comment]
> That should solve your issue. Let me know if you encounter any other issues.

Thanks Much!! :)

**Comment by rajanadar** [comment]
Cool
