### ISSUE TITLE
Implement Terraform Cloud Secret Backend

### ISSUE THREAD

**Issue by afmorris** [rajanadar/VaultSharp#210]
**Describe the feature request or question**
The Terraform Cloud Secret Backend is not implemented.

**Link to the Vault API Docs that support this feature**
https://www.vaultproject.io/docs/secrets/terraform

**Additional context**

**Comment by rajanadar** [comment]
Thanks @afmorris. This will be available this weekend in a new package.

**Comment by rajanadar** [comment]
Available as part of 1.7.0 package

**Comment by rajanadar** [comment]
@afmorris In your real integration, let me know if you find any issues.

**Comment by afmorris** [comment]
Thanks @rajanadar -- I'll try this out this week and let you know.

**Comment by rajanadar** [comment]
cool
