### ISSUE TITLE
Mutual TLS login using certificate chain

### ISSUE THREAD

**Issue by mr-miles** [rajanadar/VaultSharp#215]
**Describe the bug**
It is not possible to add a chain of certificates to the cert auth.  This means that client certificates generated by a trusted intermediate are impossible to log in with.

**VaultSharp Version**
1.7.1

**Vault Version**
1.8.1

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**
Constructor only takes a single X509Certificate2.  To support this, the constructor needs to take an X509Certificate2 array or X509Certificate2Collection and add them all to the ClientCertificates property of the HttpClientHandler.  Then windows will handle it all.

**Any additional info**
Trusted intermediates are quite common.  I'd be happy to provide a patch/PR for this if its welcome.

**Comment by rajanadar** [comment]
Interesting. I didn't know this.

Cool, I'll add an overload to the CertAuthInfo to provide multiple certs and publish an update this weekend.
I have some other changes in the work as well.

**Comment by rajanadar** [comment]
Had to publish an intermediate version this weekend, for some consumers who were blocked. Onto this now.
