### ISSUE TITLE
Types for epoch based timestamps

### ISSUE THREAD

**Issue by zitcomdev** [rajanadar/VaultSharp#218]
**Describe the bug**
As in PR #217, one might consider going through the codebase for other epoch based values as well. I just noticed that certificate Revocation Time is also an integer, and should probably be changed to int64/long. Although I haven't looked into Vault documentation for the appropriate types.

**VaultSharp Version**
Latest

**Comment by rajanadar** [comment]
Makes sense @zitcomdev . Will have a sweep next weekend

**Comment by rajanadar** [comment]
@zitcomdev  I have created a branch with the sweep. I have to do the painful part of verifying it with the vault api code and/or docs. Most fields seem to be ttl, so hopefully it covers 90% of things.

**Comment by rajanadar** [comment]
will revisit this on-demand
