### ISSUE TITLE
VaultClient stucks with exception when vault server is not available

### ISSUE THREAD

**Issue by ng923** [rajanadar/VaultSharp#220]
**Describe the bug**
If application uses newly created VaultClient when VaultServer is not available, this client stuck in throwing the same exception on each try to access VaultServer event if it is up and running.

**VaultSharp Version**
1.7.0

**Sample Code Snippet**
The source of the issues is 
`In Polymath.cs 
  internal void SetVaultTokenDelegate()
        {
            if (_authMethodLoginProvider != null)
            {
                _lazyVaultToken = new Lazy<Task<string>>(_authMethodLoginProvider.GetVaultTokenAsync);
            }
        }`

This code may improved by adding LazyThreadSafetyMode.PublicationOnly parameter to constructor of Lazy<Task<string>> to fix the issue.

` internal void SetVaultTokenDelegate()
        {
            if (_authMethodLoginProvider != null)
            {
                _lazyVaultToken = new Lazy<Task<string>>(_authMethodLoginProvider.GetVaultTokenAsync, LazyThreadSafetyMode.PublicationOnly);
            }
        }`

**Comment by rajanadar** [comment]
thanks @ng923 . Didn't know this. What a nasty/nice bug. Will make this change in next publish of VS on 10/10 weekend
