### ISSUE TITLE
Code snippet fires an error "

### ISSUE THREAD

**Issue by ratmount** [rajanadar/VaultSharp#222]
using System;
using System.Threading.Tasks;
using VaultSharp;
using VaultSharp.V1.AuthMethods;
using VaultSharp.V1.AuthMethods.Token;
using VaultSharp.V1.Commons;

namespace ConsoleVault
{
    class Program
    {
        static async Task Main(string[] args)
        {       
            var vaultUrl = "http://127.0.0.1:8200";
            await Program.by_token(vaultUrl);

            Console.WriteLine("Hello World!");
        }

        static async Task<SecretData> by_token(string vaultUrl)
        {
            // Initialize one of the several auth methods.
            IAuthMethodInfo authMethod = new TokenAuthMethodInfo(@"s.0lTUY94JWKS37bXuqU4Z0Jpj");

            // Initialize settings. You can also set proxies, custom delegates etc. here.
            var vaultClientSettings = new VaultClientSettings(vaultUrl, authMethod);

            IVaultClient vaultClient = new VaultClient(vaultClientSettings);
            await vaultClient.V1.Auth.PerformImmediateLogin();

            // Use client to read a key-value secret.
            Secret<SecretData> kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: "kv/hello", mountPoint: "/");
                        
            return kv2Secret.Data;
        }
    }
}

Gives an error :  VaultSharp.Core.VaultApiException: '{"errors":["missing client token"]}

**Comment by ratmount** [comment]
Found the solution:

started to work after the addition of:

IVaultClient vaultClient = new VaultClient(vaultClientSettings);
**vaultClient.Settings.UseVaultTokenHeaderInsteadOfAuthorizationHeader = true;**

**Comment by rajanadar** [comment]
Cool.
