### ISSUE TITLE
Users should have the possibility to retrieve raw secret data without deserialization

### ISSUE THREAD

**Issue by std66** [rajanadar/VaultSharp#228]
**Describe the feature request or question**
Since VaultSharp uses Newtonsoft.Json to deserialize responses internally, it is not possible to configure the deserialization process or to obtain raw secret data.

Example for KV-V2 secret engine (but applicable to other secret engines, eg. Database), which stores JSON objects, the user is forced to deserialize this JSON object either into Dictionary<string, object> or a user-defined type:
```
public interface IKeyValueSecretsEngineV2 {
   //deserializes into Dictionary<string, object>
   Task<Secret<SecretData>> ReadSecretAsync(string path, int? version = null, string mountPoint = null, string wrapTimeToLive = null);

   //deserializes into a user-defined type
   Task<Secret<SecretData<T>>> ReadSecretAsync<T>(string path, int? version = null, string mountPoint = null, string wrapTimeToLive = null);
}
```

My proposal is to have a new method which makes it possible to the user to access the secret in raw JSON-string format:
```
public class RawSecretData : SecretData<string> {...}

Task<Secret<RawSecretData>> ReadRawSecretAsync(string path, int? version = null, string mountPoint = null, string wrapTimeToLive = null);
```

**Link to the Vault API Docs that support this feature**
None

**Additional context**
None

**Comment by rajanadar** [comment]
hi @std66 , this is an interesting ask. May I ask the value-prop of this please?
I do have a "rawResponse" flag that I use internally for certain Vault APIs, but that flag is not exposed to the clients, deliberately. 

The JRaw limitations are a bummer. There is a another workaround to get the raw response of any Vault API call, from VaultSharp.

The gist is to setup a ```AfterApiResponseAction``` delegate on the ```VaultClientSettings``` that gets invoked on every api call with the ```HttpResponseMessage``` object returned by the ```WebClient```. And in your delegate, you can get the response content.

```

String rawSecret = null;

vaultClientSettings.AfterApiResponseAction = httpResponseMessage =>
    rawSecret  = await httpResponseMessage.Content.ReadAsStringAsync(); // do null check on content;

// make the call to read the secret here.

// the rawSecret variable should hopefully have the captured raw value.

```

Let me know if this works for you.
