### ISSUE TITLE
Retrieving available paths (or metadata) for KV engine

### ISSUE THREAD

**Issue by RonnieJorgensen** [rajanadar/VaultSharp#229]
Using the Vault UI, I can see that it's using the following API call to list all available paths of the KV engine: /v1/{mountPoint}/metadata/?list=true

I don't see this option available in VaultSharp, since all methods for KeyValue.V2 requires a path. I didn't successfully find anything about this specific call in the API documentation either, but I believe this is the CLI equivalent: https://www.vaultproject.io/docs/commands/kv/metadata

The use case here is that I'm using a KV engine for N number of applications that need X number of values. On top of that I need another application to know of each path (X) to monitor things.

**Comment by konidev20** [comment]
Can you confirm if you are referring to these APIs corresponding to the appropriate KV versions from the documentation?  

List Secrets HTTP API KV-v1: https://www.vaultproject.io/api-docs/secret/kv/kv-v1#list-secrets

List Secrets HTTP API KV-v2: https://www.vaultproject.io/api-docs/secret/kv/kv-v2#list-secrets

These 2 APIs exist in the VaultSharp Library already.

The API has the signature:
KeyValueSecretsEngineV1Provider
`Task<Secret<ListInfo>> ReadSecretPathsAsync(string path, string mountPoint = null, string wrapTimeToLive = null);`

KeyValueSecretsEngineV1Provider
`Task<Secret<ListInfo>> ReadSecretPathsAsync(string path, string mountPoint = null, string wrapTimeToLive = null);`

The functionality for these already exists; refer the VaultSharp documentation: http://rajanadar.github.io/VaultSharp/

**Comment by konidev20** [comment]
> The use case here is that I'm using a KV engine for N number of applications that need X number of values. On top of that I need another application to know of each path (X) to monitor things.

For this use case: You must recursively call the `ReadSecretPathsAsync` API on the results of the ListInfo. Initially you must provide the `path` parameter as a `null` or `""` (empty string).

**Comment by RonnieJorgensen** [comment]
> > The use case here is that I'm using a KV engine for N number of applications that need X number of values. On top of that I need another application to know of each path (X) to monitor things.
> 
> For this use case: You must recursively call the `ReadSecretPathsAsync` API on the results of the ListInfo. Initially you must provide the `path` parameter as a `null` or `""` (empty string).

Thank you, that's the one I needed.
