### ISSUE TITLE
Could you push 1.7.0.3 to nuget?

### ISSUE THREAD

**Issue by mr-miles** [rajanadar/VaultSharp#230]
I want to use the certificate chain feature you kindly added, but the latest versions aren't on nuget.

Would you be able to push the latest build to the package feed?

**Comment by konidev20** [comment]
I belive it's version 1.7.0.2

+1 on the Request. I am waiting for some of the features and fixes in the last few commits.

I locally built and packed the library for dev testing. 

Thanks

**Comment by rajanadar** [comment]
Thanks folks. Will publish it tonight then.

**Comment by rajanadar** [comment]
Its pushed. Please check v 1.7.0.2

**Comment by konidev20** [comment]
@rajanadar thank you.

**Comment by rajanadar** [comment]
Thank you @konidev20 for all the engagement.
