### ISSUE TITLE
Missing ConfigureAwait with ContinueAsyncTasksOnCapturedContext option

### ISSUE THREAD

**Issue by glecchi** [rajanadar/VaultSharp#235]
**Describe the bug**
In the Polymath class on line 144 there is no ConfigureAwait with the ContinueAsyncTasksOnCapturedContext option and in my case this causes a deadlock.

**VaultSharp Version**
1.7.0.3

**Any additional info**
.NET Framework 4.8

**Comment by rajanadar** [comment]
fixed by https://github.com/rajanadar/VaultSharp/commit/93cb204a0946b0c058268f31f636c8e29680e5a5

**Comment by rajanadar** [comment]
@glecchi  please check https://www.nuget.org/packages/VaultSharp/1.7.0.4
