### ISSUE TITLE
Documentation for IVaultClient registration in DI

### ISSUE THREAD

**Issue by AleksandreJavakhishvili** [rajanadar/VaultSharp#236]
**Describe the feature request or question**
With the current documentation It is not clear how we should register `IVaultClient` in DI with scoped/transient or singleton scope, I mistakenly added as a singleton, which ended up to have one instance of VaultClient and as It doesn't support token refresh we got `{"errors":["permission denied"]}` after 24h, It would be better If we add DI section in README.md.

**Comment by rajanadar** [comment]
done @AleksandreJavakhishvili

**Comment by rajanadar** [comment]
@AleksandreJavakhishvili please check https://www.nuget.org/packages/VaultSharp/1.7.0.4
