### ISSUE TITLE
Azure Auth not returning response nor timeout while retrieving secrets

### ISSUE THREAD

**Issue by ZSilver55** [rajanadar/VaultSharp#237]
**Describe the bug**
We've been migrating from Token Auth to Azure Auth changed the Auth object but the behavior now is that it doesn't return a response, not even a timeout several hours after we invoked the code.

**VaultSharp Version**
1.7.0.3

**Vault Version**
Vault 1.6.6+prem

**Does this work with Vault CLI?**
Not tested

**Sample Code Snippet**
IAuthMethodInfo authMethodAzure = new AzureAuthMethodInfo(roleName , jwt);
var vaultClientSettings = new VaultClientSettings(vaultserverUri, authMethodAzure);
vaultClientSettings.Namespace = vaultserverNamespace;
VaultClient vaultClient = new VaultClient(vaultClientSettings);
Secret<SecretData> secrets = VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(id).GetAwaiter().GetResult();

**Exception Details/Stack Trace/Error Message**
The thread keeps waiting for a response but none is returned

**Any additional info**
We successfully got a auth.client_token from the vault server with the API as stated in the documentation:
$ curl \
--request POST \
--data '{"role": "dev-role", "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."}' \
https://127.0.0.1:8200/v1/auth/azure/login

source:
https://www.vaultproject.io/docs/auth/azure

**Comment by rajanadar** [comment]
hi @ZSilver55 

This snippet of ```Secret secrets = VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(id).Result;``` is recommended for synchronous apps with clear assurance of no deadlock/infinite wait behavior. Otherwise, the recommended way to use VaultSharp is in async mode.

``` Secret secrets = await VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(id);```

If you really want to use the sync way, ensure you set the ```continueAsyncTasksOnCapturedContext``` flag on the client settings and try your snippet again.
