### ISSUE TITLE
Feature request: Entities and Groups

### ISSUE THREAD

**Issue by ajhall** [rajanadar/VaultSharp#238]
**Describe the feature request or question**
I'd like to use the Entity, Entity Alias, Group, Group Alias, and Lookup features of the Identity Secrets Engine. Currently, VaultSharp only supports the Identity Tokens features of this engine.

**Link to the Vault API Docs that support this feature**
* https://www.vaultproject.io/api-docs/secret/identity/entity
* https://www.vaultproject.io/api-docs/secret/identity/entity-alias
* https://www.vaultproject.io/api-docs/secret/identity/group
* https://www.vaultproject.io/api-docs/secret/identity/group-alias
* https://www.vaultproject.io/api-docs/secret/identity/lookup

**Comment by konidev20** [comment]
Hey @ajhall,

I can help you out with this feature request. Implementing on all the APIs you've requested might take a few days.

If you can prioritize the ones, you need the most, we can implement it first and release a small release so that you're not blocked.

**Comment by ajhall** [comment]
Oh, thanks! I also started to investigate adding these features to VaultSharp, but the app I was implementing was so simple that I ended up rewriting it in Go and using HashiCorp's official Go API package. In the end, I only really needed `LIST identity/entity/id`,  `POST identity/entity/name`, and `POST identity/entity-alias`. I would have preferred writing in C#, but I got the job done either way. 😁

Regardless, I think this is still a gap in this library that might be useful in the future.

**Comment by rajanadar** [comment]
thanks @ajhall for raising this. thanks @konidev20  for implementing this. we will close this out in new year

**Comment by RyanGaudion** [comment]
Just to add a +1 to this, I need the following endpoints:
`POST identity/group`, `POST identity/group-alias`

**Comment by konidev20** [comment]
> Just to add a +1 to this, I need the following endpoints:
> `POST identity/group`, `POST identity/group-alias` 

Sure let me add these over the weekend to the same PR I've linked here.

**Comment by rajanadar** [comment]
Available here: https://www.nuget.org/packages/VaultSharp/1.7.2
