### ISSUE TITLE
Impossible to use with anything lower than .NET Framework 4.7.2

### ISSUE THREAD

**Issue by Amarus** [rajanadar/VaultSharp#243]
**Describe the bug**
Using VaultSharp with a version of .NET Framework lower than 4.7.2 is not possible because the DLL is built against .NET Framework 4.7.2.

`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3274: The primary reference "VaultSharp, Version=1.7.0.4, Culture=neutral, PublicKeyToken=cb3d4aad92b0eded, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".`

**VaultSharp Version**
1.7.0.4

**Vault Version**
N/A

**Does this work with Vault CLI?**
N/A

**Sample Code Snippet**
Create an empty console app targeting anything lower than .NET Framework 4.7.2 (e.g. 4.6.1) and use this:
```
using VaultSharp.V1.AuthMethods;
using VaultSharp.V1.AuthMethods.Token;

namespace VaultSharpTest
{
    class Program
    {
        static void Main(string[] args)
        {
            IAuthMethodInfo authMethod = new TokenAuthMethodInfo(vaultToken: "x");
        }
    }
}
```

**Exception Details/Stack Trace/Error Message**
The compilation error is:
`error CS0246: The type or namespace name 'VaultSharp' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Amarus** [comment]
After some investigation it seems to be related to this:
https://github.com/rajanadar/VaultSharp/blob/e298fa40b097552d91301d9c147e4632a30c6a86/src/VaultSharp/VaultSharp.csproj#L43

I _think_ that it's safe to remove that line.

**Comment by rajanadar** [comment]
thanks @Amarus 

I'll look into this in the new year

**Comment by jwdomes** [comment]
@rajanadar  - any follow-up on this request. I have a .NET 4.7 app and would like to use this library.

**Comment by Amarus** [comment]
> @rajanadar - any follow-up on this request? I have a .NET 4.7 app and would like to use this library.

It's a quick and dirty workaround but, if it helps, you can do as I did:
I removed the line in my [comment here](https://github.com/rajanadar/VaultSharp/issues/243#issuecomment-993618024), recompiled locally and uploaded the nuget on an internal repository.

**Comment by codyspeck-chr** [comment]
Also running into this issue with the latest versions of VaultSharp running in a .NET Framework 4.6.2 application.

**Comment by rajanadar** [comment]
fixed in https://www.nuget.org/packages/VaultSharp/1.7.1
