### ISSUE TITLE
VaultClient stucks with exception when vault server is not available

### ISSUE THREAD

**Issue by ng923** [rajanadar/VaultSharp#244]
**Describe the bug**
If application uses newly created VaultClient when VaultServer is not available, this client stucks in throwing the same exception on each try to access VaultServer event if it is up and running.

There was an similar issue https://github.com/rajanadar/VaultSharp/issues/220 but unfortunately fix didn't work

**VaultSharp Version**
1.7.0.4

**Sample Code Snippet**
The source of the issues is
`In Polymath.cs internal void SetVaultTokenDelegate() { if (_authMethodLoginProvider != null) { _lazyVaultToken = new Lazy<Task<string>>(_authMethodLoginProvider.GetVaultTokenAsync, LazyThreadSafetyMode.PublicationOnly); } }`

Main problem here, that task which may throw an exception during execution will be stored in Lazy.Value, and therefore each time awaiting will not cause new execution but only accessing first run result. And if it was with any exception, it will be rethrown.

Here is SO thread https://stackoverflow.com/questions/56404540/prevent-lazyt-caching-exceptions-when-invoking-async-delegate with full description of source of the problem and a few ways to solve it.

Also this https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.asynclazy-1?view=visualstudiosdk-2019 may be used.

**Comment by rajanadar** [comment]
thanks @ng923 . i'll have a look in new year

**Comment by rajanadar** [comment]
@ng923 This is an interesting issue. At this point, I am reluctant to include custom AsyncLazy implementations.
This thread indicates that the support may come in, as part of the base .NET framework at some point. I'll give it a wait.

https://github.com/dotnet/runtime/issues/27510
