### ISSUE TITLE
Methods to handle Token Roles

### ISSUE THREAD

**Issue by ferAbleTech** [rajanadar/VaultSharp#245]
Hello,

I'm trying to create new token roles (as seen in the API: https://www.vaultproject.io/api/auth/token#create-update-token-role),
but I'm not finding any way to do so with the current version. 
A set of methods to to handle them would be very useful, just like policies methods are currently implemented, but even just create/read methods would suffice.

Thanks!

**Comment by konidev20** [comment]
Hey @ferAbleTech. 

I found sometime over the weekend to implement the requested APIs. I have raised a PR for the same. I will test and make changes if required. 

Thanks,

**Comment by rajanadar** [comment]
thanks @konidev20 

@ferAbleTech , please consume the latest package and let us know if any issues
