### ISSUE TITLE
Refactor client usage to make use of extension methods for strongly-typed access to backends

### ISSUE THREAD

**Issue by ebekker** [rajanadar/VaultSharp#25]
Thank you for this useful client!

I wanted to open this up to discussion -- how would you feel about refactoring the client library so that the main client entry point (the `IVaultClient` interface and implementation(s)) gets reduced to a slim, basic interface to the general-purpose Vault primitives (reading, writing, admin), and all of the strongly-typed methods get re-implemented as extension methods?

This way the interface becomes *cleaner* and user only needs to import the backend-specific namespaces that they care about, which minimally extends the client for just the types specific to those backends.

**Comment by rajanadar** [comment]
thanks @ebekker for this.

Can you please expand on the value-add of your proposition?

- If a consumer only deals with say, "Github Authentication" and a "Postgres Backend", the code would just have namespaces pertaining to that. What other namespaces do you see?
- Also, extension methods come in the way of unit testing for the consumers. (since they are eseentially static methods) Folks cannot just mock IVaultClient and get-away.
- If you have a credential manager class which handles Vault stuff, do you really concern with 40 namespaces in that file?

Please share your thoughts.

**Comment by ebekker** [comment]
The overall idea is to reduce the "weight" of the main client interface.  Right now, it's a superset of all the core vault primitives, as well all domain-specific accessors.  When a user is *exploring* the client interface, say through IntelliSense or just browsing generated documentation, they see all the methods and that can be quite overwhelming.

Because all those type-safe additions have their own custom models, a client user would still need to import the namespaces of each one anyway, so that would be no different if you moved to using extension methods.

With respect to mocking -- you are correct in that you wouldn't mock a specific type-safe method.  But these methods just call in turn on the core vault primitives, just as the extension methods would, and that is where you can do the mocking, in the core methods.  This is actually more effective at testing the client functionality, since it mimic what really happens in the *real world* -- that is, the client is just returning data through the core primitives, and you need to test that the extension methods are *doing the right thing* in their interpretation of that basic data structure.

In the case of a *super user* -- a client user that deals with many or even all of the type-safe methods, as I said before, you still need to import all of the domain-specific models for each method so it does not save anything either way.   And if you look at the *typical* usage patterns, I would guess that most users are only interested in fewer type-safe methods, maybe one or a few that are specific to their use case, and far less would fall into this *super user* scenario.  In that respect, I would say you want to orient the API to favor most users in the majority use cases, but still support the minority use cases in a very elegant way.

This API approach is very much like many of the new APIs in the .NET Core and ASP.NET Core if you are familiar with those.  For example, the new Logging extensions, or the way that an ASP.NET Core application's services are composed.  You have a very slim core, and then there are specific handler and providers that *extend* this core.

This approach also opens it up for users to provide their own implementations by writing their own extension method sets, without needing to modify the core interface.

**Comment by arledesma** [comment]
How about simply employing [ISP](https://en.wikipedia.org/wiki/Interface_segregation_principle), combing all role interfaces back into the already existing `IVaultClient` for your *super user* scenario.  This would just about accomplish the same goal without introducing a breaking change to all current users of the library.

**Comment by rajanadar** [comment]
thanks @ebekker and @arledesma for the inputs.

it makes sense. and as i was writing the interface methods, i realized that this is going to end up as a huge pile. for pre 1.0.0 versions, i have tried to mitigate this by having METHOD PREFIXES which kind of groups the functionality. but that is a weak way to do it. no 2 ways about it.

will be definitely doing this, before hitting the 1.0 stable version. (especially from a 0.a. to 0.b version switch
)
right now, the priority is to get 0.7.0 features. and i'll see if this is a good time.
if not, surely before the next 2 minor version upgrades.

**Comment by rajanadar** [comment]
I have finished the re-design of the interface into smaller ones. They were getting overwhelming.
Now with broken down primitives, the code looks a lot cleaner and composable.

This is a baby step for this release, and the next steps would be to learn and understand pain points around extensibility etc.

**Comment by rajanadar** [comment]
@ebekker and @arledesma 

The latest version of VaultSharp is modularized to be very specific to the sub-parts you are interested in.
Do check it out.
