### ISSUE TITLE
Asynchronous OIDC authentication with Vault

### ISSUE THREAD

**Issue by bbartels** [rajanadar/VaultSharp#258]
We have been trying to get OIDC authentication to work with Vault. Unfortunately, in our use-case we use a third party authentication provider from which we want to fetch our JWT in order to authenticate with Vault.  
As the way to fetch the JWT from `JWTAuthMethodInfo` is synchronous we are calling out to our auth provider within that property. While it does work it is not exactly an elegant solution. 
Are we overlooking anything that would allow us to have an asynchronous way to fetch our token or is this a limitation of the library?

**Comment by konidev20** [comment]
Hey @bbartels,

From my understanding of your question, you need to fetch the JWT first before assigning creating an instance of `JWTAuthMethodInfo`.

Request you to share an example of what you’re trying to achieve.

**Comment by rajanadar** [comment]
Closing on lack of response.
@bbartels , please let us know if still an issue
