### ISSUE TITLE
I am not able to install this package in Visual Studio Professional 2015 with .NET 4.6X version

### ISSUE THREAD

**Issue by dilip280** [rajanadar/VaultSharp#26]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'VaultSharp 0.6.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by rajanadar** [comment]
@dilip280 thanks for using the library.

i think by default i created packages for .net 4.5, 4.6 and netstandard 1.4

is it possible for you to upgrade your project to .NET 4.6? not just for VaultSharp but for the overall well-being of your project?

(even 4.5.1 has reached end of support as of Jan 2016)

it is recommended for .NET apps to be on 4.5.2 or 4.6.x or even better netstandard.

let me know.

**Comment by dilip280** [comment]
Hi rajanadar

I am using .net 4.6 where this is happening

Thanks

**Comment by rajanadar** [comment]
@dilip280 

i think you maybe using .Net 4.6, but your config files maybe still targeting 4.0. (basically compatibility mode)

You need to change that to 4.6, to be truly using the 4.6 framework.
