### ISSUE TITLE
v1.7.0.5 not available on nuget

### ISSUE THREAD

**Issue by tl-daniel-cohen** [rajanadar/VaultSharp#262]
**Describe the feature request or question**
Can [v1.7.0.5](https://github.com/rajanadar/VaultSharp/releases/tag/v1.7.0.5) be made available on nuget?

**Comment by hoerup** [comment]
-> https://github.com/rajanadar/VaultSharp/discussions/255

**Comment by tl-daniel-cohen** [comment]
👍
