### ISSUE TITLE
Using AppRole with role-id and secret-id not working

### ISSUE THREAD

**Issue by MB34** [rajanadar/VaultSharp#277]
VaultSharp version is 1.7.0.4, the Hashicorp Vault UI version we have is 1.3.2+prem. My local CLI is v1.11.0 (ea296ccf58507b25051bc0597379c467046eb2f1), built 2022-06-17T15:48:44Z.

**Problem:**
Due to not being able to get any help on our wrapping token issue we are pivoting to use AppRole with role-id & secret-id. We want to create our VaultClient using AppRole authentication. I have followed the examples and documentation but am still having difficulties getting this thing running. We have 3 different AppRoles, so we pass in an api identifier that determines which AppRole to use.
**Code:**
```
    string role_id;
    string secrets_id;
    switch(api)
    {
        case 0:
            role_id = settings.AppRoleAuthRoleId0;
            secrets_id = settings.AppRoleAuthSecretsId0;
            break;
        case 1:
            role_id = settings.AppRoleAuthRoleId1;
            secrets_id = settings.AppRoleAuthSecretsId1;
            break;
        case 2:
            role_id = settings.AppRoleAuthRoleId2;
            secrets_id = settings.AppRoleAuthSecretsId2;
            break;
        default:
            role_id = settings.AppRoleAuthRoleId0;
            secrets_id = settings.AppRoleAuthSecretsId0;
            break;
    }

    IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId: role_id, secretId: secrets_id);
    var vaultClientSettings = new VaultClientSettings(_settings.Address, authMethod);
    
    IVaultClient vaultClient = new VaultClient(vaultClientSettings);
```    

Now, if I try to use vaultClient to do ANYTHING, I get a "Missing Client Token" Exception. 

1. How do I get AND pass that "client token" before I do anything with vaultClient? (Can't use authMethod.ReturnedLoginAuthInfo.ClientToken because ReturnedLoginAuthInfo is null)
2. Am I just not understanding the documentation correctly or could it be that our installation isn't setup correctly to do AppRole authentication?

**Comment by konidev20** [comment]
Hey @MB34,

The VaultClient Lazy loads the client token. It is fetched when the first API call is made to the HashiCorp Vault API. Now in your case, you have 3 different clients, you should perform an immediate login whenever you change the AuthMethod Info something like the code snippet below.
```
IVaultClient vaultClient = new VaultClient(vaultClientSettings);
vaultClient.V1.Auth.PerformImmediateLogin();
```
Refer: http://rajanadar.github.io/VaultSharp/
Section: VaultSharp and Immediate Login Failure Detection

Also, client token lifecycle management is supposed to be taken care of by you based on the token time to live (TTL) set by you.

Please check the above-mentioned items and let us know if there is anything.

**Comment by rajanadar** [comment]
@MB34  where is the rest of your code? The actual call you are making to vault using the vaultsharp client?

**Comment by MB34** [comment]
@rajanadar , I tried using both
`vaultClient.V1.Auth.PerformImmediateLogin()`;
and 
`kv2Secret = await _client.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: "trans", mountPoint: "namespace"); `

If I use TokenAuthMethod, everything works exactly as designed and my secrets are returned.

**Comment by MB34** [comment]
Code:
```
var roleId = ConfigurationManager.AppSettings["role-id"];
var secretId = ConfigurationManager.AppSettings["secret_id"];

IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
var vaultClientSettings = GetVaultClientSettings(authMethod);

IVaultClient vaultClient = new VaultClient(vaultClientSettings);

Secret<CallingTokenInfo> tokenData = vaultClient.V1.Auth.Token.LookupSelfAsync().Result;
var _token = tokenData.Data.Id;
Environment.SetEnvironmentVariable("VAULT_TOKEN", _token);

vaultClient.V1.Auth.PerformImmediateLogin();

var kv2Secret = vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: "trans", mountPoint: "exgw/exp").Result;

```
Getting a Permission Denied error with the last call above...
Now, if I use the returned token above and use the CLI to login with the token, I get this:

```
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                     Value
---                     -----
token                   <token returned from approle client login>
token_accessor          <token accessor>
token_duration          19m41s
token_renewable         true
token_policies          ["default" "trans"]
identity_policies       []
policies                ["default" "trans"]
token_meta_role_name    trans
```

Then, I attempt to access my secrets that the role trans, which is "attached" to the policy trans, like this:

```
vault kv get secret/data/trans

This is what I get:
Error making API request.
URL: GET <my value URL>
Code: 403. Errors:
* preflight capability check returned 403, please ensure client's policies grant access to path "secret/data/trans/"

```

Here's my trans policy HCL contents:

```
path "secret/data/trans" {
    capabilities = ["read", "list"]
}

```

Do you think it could be that the Vault sandbox that I'm working with his incorrectly configured for AppRoles?

**Comment by konidev20** [comment]
Hey @MB34, that's what it looks like since the Vault command itself is throwing a 403 error.

**Comment by konidev20** [comment]
Check your mount points @MB34 probably list the mount points as well once.

**Comment by MB34** [comment]
If I do this: 
`vault kv get express/trans`
It returns this:
```
====== Secret Path ======
exp/data/trans
```
Along with all my secrets, My gateway is named `exgw`
And this code:
`var kv2Secret = vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: "trans", mountPoint: "exgw/exp").Result;`
returns a permission denied

**Comment by MB34** [comment]
Yeppers, changing the mountPoint to remove the namespace got it working. Thanks @konidev20

**Comment by konidev20** [comment]
Hey @MB34, 

I'm glad I was able to help you out with this 😃. 

I have been in a situation where I have used the wrong mount points.

Thanks & Regards, 
@konidev20

**Comment by MB34** [comment]
I do have one question. Is the Namespace being read from my ENV variable or is it inherent from the client used to login to the role?

**Comment by konidev20** [comment]
Hey @MB34,

Namespaces have to be initialized when creating the `IVaultClient` using `VaultClientSettings` option `Namespace`. This will set the `X-Vault-Namespace` header for each API request being made.

Now, if you don't initialize the namespace in the vault client, you will have to prefix your mount-point paths with the namespace it is in.

>For example, these three requests are equivalent:
> 1. Path: ns1/ns2/secret/foo
> 2. Path: secret/foo, Header: X-Vault-Namespace: ns1/ns2/
> 3. Path: ns2/secret/foo, Header: X-Vault-Namespace: ns1/

Refer: https://www.vaultproject.io/docs/enterprise/namespaces

Thanks,
@konidev20

**Comment by manishsarode** [comment]
In addition to previous missing token error, I was facing all sorts of errors related to assembly references/service references as I was trying to call my new C# code file in an existing project.

I created a brand new project for accessing vault secrets. I can now re-use the new appln dll in other programs to integrate to Vault.

Yes, syntax mentioned by you in previous thread worked perfectly for me. Many Thanks for clarification.

**Comment by konidev20** [comment]
Hey @manishsarode, 

I'm glad I was able to help with the code snippet. 

If you are using VaultSharp version 1.13.0+, it doesn't support EOL .NET 4.6 and .NET 4.6.1 which might explain the package and reference errors you were getting.

Thanks & Regards, 
@konidev20

**Comment by manishsarode** [comment]
@konidev20 
Hi Srigovind,

Need a clarity on _AppRole_ authentication.:
As per Vault documentation my initial understanding was, Role Id and Secret Id's purpose was to authenticate with Vault and then further use token (implicitly) held by app role policy to read secrets. And there was a need to regenerate the token (associated to app role policy) when its about to expire as per its TTL.
I thought VaultSharp's _ReadSecretAsync_ method implicitly used that token until token expires.

We force expired the token associated with our app role policy using _**revoke**_ command. And to my surprise _AppRole_ authentication used in my .NET program authenticated, generated new token behind the scenes and read secrets too. 

Does it mean if we use _AppRole_ authentication we never have to worry about re-set token ?

**Comment by manishsarode** [comment]
@konidev20 
Hi Srigovind,

I would really appreciate if you could reply to my query above.

Many Thanks
Manish

**Comment by konidev20** [comment]
Hey @manishsarode, 

The VaultSharp library doesn't automatically renew tokens. 

You have to write some kind of a background service to renew. 

I have a rough example of how you can achieve this [Example](https://github.com/konidev20/HCVaultTokenManagement/blob/master/BackgroundServices/HashiCorpVaultLoginService.cs) 

Note: I was just trying stuff with this make appropriate changes for production usage.

Can I confirm if you're using the `VaultClient` as a Singleton?

Thanks,
@konidev20

**Comment by konidev20** [comment]
Hey @manishsarode, 

If it's not singleton then for each request it's creating a new vault client object and a new vault token is being fetched. 

That's my understanding. The VaultSharp library doesn't auto renew
