### ISSUE TITLE
VaultSharp does not have CancellationTokens for async methods

### ISSUE THREAD

**Issue by Taturevich** [rajanadar/VaultSharp#282]
None of the async methods have a cancellation token as an optional parameter. Cancellation token should be provided in method contracts and propagated up to the HttpClient call. The current implementation causes inconveniences during the timeout logic implementation.

**Comment by rajanadar** [comment]
hi @Taturevich 

Can you please explain your use case for Cancelation further? This is a huge change across all methods.

**Comment by rajanadar** [comment]
To start with, let me know the specific methods where you need it, and I'll at least start there.

**Comment by robv8r** [comment]
`CancellationToken`s allow applications to "stop" an asynchronous process before it has completed.  This is very useful with web based applications, when the user navigates to a different page before an async WebAPI Controller method has completed.

Without the ability to pass a `CancellationToken` to the VaultSharp API, developers would need to manage token cancelation themselves.  This can be done by calling [token.ThrowIfCancellationRequested](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.throwifcancellationrequested#system-threading-cancellationtoken-throwifcancellationrequested).  However, doing this after each method call can significantly clutter user code.

By accepting a `CancellationToken` as the last parameter for all `async` methods and passing that token to the `HttpClient` calls, if an HTTP Request is interrupted, the application doesn't continue processing the work on that async `Task`.

Here's an example from Microsoft: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2016
