### ISSUE TITLE
Regarding Implementation of VaultSharp

### ISSUE THREAD

**Issue by aggarwalnittin** [rajanadar/VaultSharp#283]
Hi ,I am beginner and learning this VaultSharp. when i check you code i have found lot of code steps which make me Little bit confuse.

My requirement is:
1) Integrate the HashiCorp in .net core (Microservice). Already created.
2) What is the process to deploy this code in production we are using AWS for deployment purpose.

I have tried the code but not successfully. Just need a small application steps that help me step by step to integrate with existing application or new application.

Even you can add this video in YouTube so that everyone can check and follow that steps.

**Comment by rajanadar** [comment]
hi @aggarwalnittin , this is a simple DLL to be added as a reference library to any host application (console app or windows app or web app or windows service etc.) The deployment of the host app is really outside the scope of VaultSharp.
