### ISSUE TITLE
Missing RabbitMQ endpoints for managing roles.

### ISSUE THREAD

**Issue by codecooper** [rajanadar/VaultSharp#286]
I am working on a multi-tenant application and one of the requirements is that RabbitMQ credentials must be separated by tenant using vhosts. Vault accomplishes this by using RabbitMQ roles to limit what vhosts and permissions a generated set of credentials have access to. The create/read/delete role methods are not VaultSharp.

[The Vault Docs URL](https://developer.hashicorp.com/vault/api-docs/secret/rabbitmq)

I have already built and tested this and have a PR ready.

**Comment by rajanadar** [comment]
fixed by #287

**Comment by rajanadar** [comment]
Available here: https://www.nuget.org/packages/VaultSharp/1.7.2
