### ISSUE TITLE
Getting token TimeToLive

### ISSUE THREAD

**Issue by daviddahan01** [rajanadar/VaultSharp#29]
Hi, I'm trying to figure out how to obtain the TTL (after renewal) . i'm using the GetTokenInfoAsync
method, it returns all data expect for WrappedInformation (null). i saw that TTL can be obtained from WrapInfo class.

I also tried to use LookupTokenWrapInfoAsync to get the WrappedInformation . but than got an exception indicating the token invalid or does not exists...

Can you help me to figure it out please?

Best.
David Dahan.

**Comment by thestonehead** [comment]
+1

**Comment by rajanadar** [comment]
thanks @daviddahan01 and @thestonehead 

what version of the library are you using?
can you please send me some repro steps?

as I finish the next version, I'll verify this with as well.

**Comment by rajanadar** [comment]
@daviddahan01 please reopen with the details.
