### ISSUE TITLE
Missing api methods for AWS Secrets Engine.

### ISSUE THREAD

**Issue by fillefilip8** [rajanadar/VaultSharp#294]
**Describe the feature request or question**
All api methods provided by the AWS Secrets Engine are not exposed in the VaultSharp client.
Would be useful if these can be added to make the client support all methods.

**Link to the Vault API Docs that support this feature**
[Example of api method missing](https://developer.hashicorp.com/vault/api-docs/secret/aws#create-update-role)

**Comment by rajanadar** [comment]
@fillefilip8  The work is done. Should be ready to use in next package publish
