### ISSUE TITLE
Facing an intermittent issue while reading the secret key from vault

### ISSUE THREAD

**Issue by soundaryadandu** [rajanadar/VaultSharp#295]
After few requests it is throwing exception saying 
{“errors”:[2 errors occurred:\n\t* crypto/rsa: verification error\n\t*
Below is the code snippet

IAuthMethodInfo authMethod = new CloudFoundryAuthMethodInfo(mountpath,roleName,CF_INSTANCE__CERT,signature);
            VaultClientSettings vaultClientsettings = new VaultClientSettings(Configuration [“pcf:vault”],authMethod);
IVaultClient vaultclient= new VaultClient(vaultclientsettings)
Task<Secret<System.Collections.Generic.Dictionary<string, object> >> getsecret = Task.Run(() => _vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(path: _vaultConfiguration.SecretsPath,mountpoint));

getsecret.Wait()

.net version-3.1
Vaultsharp version-1.7.1

**Comment by rajanadar** [comment]
hi @soundaryadandu 

If the read secret calls were succeeding continuously and then suddenly stopped working, and then never started working again, then it could be a signature time-validity expiration problem. Is that the case?

Can you please check (yourself or your vault team) with the vault to CloudFoundry setup team as to what configuration they gave while setting up connections between Vault and CF?

Specifically the ```login_max_seconds_not_before``` parameter here: https://developer.hashicorp.com/vault/api-docs/auth/cf#create-configuration

**Comment by soundaryadandu** [comment]
Yes
secret calls were succeeding continuously and then suddenly stopped working, and then never started working again

This is the case
 I will check with cloud support team
Usually how much time do we need to setup for these two parameteters to overcome this
login_max_seconds_not_before
login_max_seconds_not_after

**Comment by rajanadar** [comment]
It depends on your security team. It is a balance between your security tolerance since a higher value is prone to replay attacks and a shorter value is better for security but hard on the app code since it has to reinitialize things frequently.

The other thing to find out is that VaultSharp really just uses CF only ONCE to generate a pure vault login token (the first time you try to read a secret). Once the vault token is generated, only that is used for future logins. No more need for signatures. So it is a bit bizarre that crypto failures are happening.

**Comment by soundaryadandu** [comment]
Basically we are getting signature and reading secret keys from vault for every webapi call in the application
The reason y is we need the keys to send the request to azure ad and validate the token

so since we are making multiple requests for getting the signatures everytime might cause this issue

**Comment by rajanadar** [comment]
Interesting. Then this might solve your problem.

The intended usage of VaultSharp is to initialize the VaultClient only once as a singleton instance. This is typically done as part of your Dependency Injection systems.

So this object should be constructed only once. ```IVaultClient```
And when you construct it using ```CFAuthInfo```, use the ```PerformImmediateLogin``` api to ensure VaultSharp immediately does a CF check and gets a vault token for you. 

https://github.com/rajanadar/VaultSharp#vaultsharp-and-immediate-login-failure-detection

After this, the ```IVaultClient``` instance can be used any number of times till the lifetime of the app. You don't need to reinitialize it on every request. And VaultSharp will use the vault token directly and doesn't look at the CfAuthInfo object anymore.

Try this and let me know

**Comment by rajanadar** [comment]
And if you don't want to make any significant changes to your code, then my other easy suggestion is to ensure you recalculate the ```signature``` value, every time as well.

```
var freshSignature = "<calculate freshly every time>";
IAuthMethodInfo authMethod = new CloudFoundryAuthMethodInfo(mountpath,roleName,CF_INSTANCE__CERT,freshSignature);
```

**Comment by rajanadar** [comment]
Also, without sharing any confidential keys, please let me know if the signature generation snippet can be shared. Lot of times, folks don't use a signatureTime variable anchor. They use DateTime.Now twice resulting in slightly problematic signature verifications.

**Comment by soundaryadandu** [comment]
![Uploading 30B1C38E-A18D-4BDA-83AF-C271F75EF887.jpeg…]()

**Comment by soundaryadandu** [comment]
![3F3B4CFB-7ABF-4A37-AC2C-C2ACFD47019F](https://user-images.githubusercontent.com/39556396/208980252-92f3896c-9f17-4271-a689-5d29752e2e5d.jpeg)

**Comment by soundaryadandu** [comment]
![E4F4CF61-5A71-460F-8650-1E5FE8A99FA9](https://user-images.githubusercontent.com/39556396/208980431-a6e0f44f-297d-409b-9787-0ba54f7c737e.jpeg)

**Comment by rajanadar** [comment]
Thanks for that @soundaryadandu. The bug is in your dual use of ```DateTime.UtcNow```. You're providing 2 different values to the system. It should be a single value. Please do the following.

```

DateTime signatureDateTime = DateTime.UtcNow;

string signature = GetSignature(signatureDateTime, .... );  // pass the above date variable here.
// more code

IAuthMethodInfo authMethod = new CloudFoundryAuthMethod(.. signatureDateTime...); // use the same variable as above

```

Let me know if you still see the issue after the above fix.

**Comment by soundaryadandu** [comment]
Hi rajanadar

since we are making call to vault for everyapi request we are facing lot of issues resulting in no response from vault.

can we call vault only once throughout the application and use the keys everywhere so that traffic will be less and the application will be fast 

any idea how to do that in .net3.1

**Comment by rajanadar** [comment]
Normally, people load the secrets only once during the app startup.
In your case, you can initialize vault client and also go fetch the secrets you want, and then have it available for the rest of the app, anytime.

Both in windows app, console app or web app, there are initialization places that will run only once.
You can do the single vault call here and store the secret locally.

Also, even if you call Vault millions of times, it shouldn't be giving you no response. That is a separate problem

**Comment by rajanadar** [comment]
Closing this, as this is not a VaultSharp issue.
