### ISSUE TITLE
ReturnedLoginAuthInfo is comming as null

### ISSUE THREAD

**Issue by kirankg15** [rajanadar/VaultSharp#296]
I am using approle auth method.

![20221223_104619](https://user-images.githubusercontent.com/51697019/209275771-81224e98-c2ba-4081-8925-4a3d97441c62.jpg)

I initialized auth method 
![20221222_170852](https://user-images.githubusercontent.com/51697019/209127750-6e8eee99-8f71-44e4-af0f-37e564fe63a8.jpg)

Then build vault settings
![20221222_171022](https://user-images.githubusercontent.com/51697019/209127894-198e1d48-dac7-4c63-8e61-c2b243e808cd.jpg)

I am using secret path as combination of namespace + secret path

![20221223_105213](https://user-images.githubusercontent.com/51697019/209276232-e10a1edb-aa7b-4157-9722-68ed22a1a847.jpg)

When fetching secrets it is giving permission denied error.

When I check auth method info it is showing null.
So is this causing error as : permission denied?

![20221223_105622](https://user-images.githubusercontent.com/51697019/209276622-0bb20c57-9827-41d6-bd5a-ab5c1cb793ce.jpg)

Please suggest.

**Comment by rajanadar** [comment]
@kirankg15 

The first parameter for ```ReadSecretAsync``` is not the namespace. It is the path of the secret.
You're using namespace. Change and let me know

**Comment by kirankg15** [comment]
I updated the my comment and code aswell 
please recheck

**Comment by rajanadar** [comment]
Here is a sample snippet that can write a secret and then read it.
You don't need to provide namespace here

```
var secret = vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: "test2-key", mountPoint: "xyz-kv-secret").Result;
```

**Comment by kirankg15** [comment]
@rajanadar 
Added that snippet but still same error

**Comment by rajanadar** [comment]
Then the role policies need to be checked. Can you try using CLI?
If you see the same error, then the role has been setup with some missing permissions

**Comment by kirankg15** [comment]
Yes I set them through cli and when I test them with postman methods i can see secrets.

But as you said let recheck the role policies again.

**Comment by kirankg15** [comment]
@rajanadar 
I recreated the policy.
![20221223_134114](https://user-images.githubusercontent.com/51697019/209299084-7c65ee54-4b1b-4db6-9d04-8088e212b5e8.jpg)

Also recreated the role with attached policy
![20221223_134354](https://user-images.githubusercontent.com/51697019/209299174-07855fce-5baa-4bca-a73d-bd7d1b494068.jpg)

Still getting the same error.
But when tested through api,i can get the secret

**Comment by rajanadar** [comment]
Can you show me the API call that is working? The URL, Header etc.

**Comment by kirankg15** [comment]
Here it is a working api call.


![20221223_160623](https://user-images.githubusercontent.com/51697019/209321556-97b87626-7449-44ce-a1e5-8f281c097786.jpg)

**Comment by rajanadar** [comment]
How did you get the token in that header? The hvs.C*** one?
Did you get it by doing a CLI login on the AppRole role id, secret id etc.?

**Comment by kirankg15** [comment]
Yes i retrieved it with role id and secret id by hitting another api method call.
Call: V1/auth/approle/login
Then I am using that token in above mentioned api to fetch secrets.

**Comment by rajanadar** [comment]
Can you let me know the exact URL you used to fetch the login token?

v1/auth/approle/login doesn't sound right because, your mountpoint in other snippet says ```test_approle``` as the mount point.

**Comment by kirankg15** [comment]
@rajanadar 
That's correct url:v1/auth/test_approle/login

I just given you that by modifying for security reasons.

**Comment by rajanadar** [comment]
OK thanks.

Instead of app role Auth info, can you please use the TokenAuthMethod and use the above working token, and then try the same read secret call?

**Comment by rajanadar** [comment]
Vault Sharp will throw a nice exception, if it is not able to fetch a vault token using the app role parameters. Because you didn't get that error, I don't think the problem is in the app role token creation.

The problem seems to be more on the policies. Some path or names pace is creating the issye.

**Comment by kirankg15** [comment]
> OK thanks.
> 
> Instead of app role Auth info, can you please use the TokenAuthMethod and use the above working token, and then try the same read secret call? Only for debugging purposes.

@rajanadar 
With token authentication also, I am getting the same error.

**Comment by kirankg15** [comment]
@rajanadar 
Hey finally issue got resolved.
The url was the culprit.
I was appending /V1 to the base url.
I rechecked all your methods where you are already appending V1 /auth wherever necessary so I removed and tried.
It's worked like a charm.

**Comment by rajanadar** [comment]
Good to hear.
