### ISSUE TITLE
Getting error “x509: certificate signed by unknown authority”

### ISSUE THREAD

**Issue by soundaryadandu** [rajanadar/VaultSharp#297]
I am connecting to vault and fetching the keys during in startup.cs file 
While deploying the application to pivotal cloud foundry i am facing this issue “x509: certificate signed by unknown authority”
Note: i am able to get the signature,CF_INSTANCE_KEY and CF_INSTANCE_CERT

**Comment by rajanadar** [comment]
Please provide VaultSharp specific details on the code snippet, the
exception stack trace, what line etc.

**Comment by soundaryadandu** [comment]
![8429170B-5921-4BAC-A1F2-91C6235EF4A1](https://user-images.githubusercontent.com/39556396/209663669-d455df88-9812-4020-a1a7-5bedf8ff97ca.jpeg)


This is the exception

![14B593E9-71D5-41A4-BD87-35CF389B7E2E](https://user-images.githubusercontent.com/39556396/209663709-aad7eaa8-0e1c-4fe0-9193-feca8c397c1f.jpeg)

This is the code snippet

**Comment by rajanadar** [comment]
OK. Looks like a certificate chain issue on your side. Check with your ops
team if the CA chain is signed with proper public authories.

**Comment by soundaryadandu** [comment]
This is working fine till monday we are facing this issue from yesterday 
No changes are applied to code

**Comment by rajanadar** [comment]
Check if a cert or a chain cert expired as of yesterday etc.

**Comment by EKovalenok** [comment]
> This is working fine till monday we are facing this issue from yesterday
> No changes are applied to code

I just tested this case. It works for me.

Try to disable SSL certificate validation for HttpClient in your .NET application. If this works, then the problem with your certificate

**Comment by soundaryadandu** [comment]
I checked with the pcf team the issue is because of cert rotation in pcf.
Team had updated the certificates and now it is working fine. Thanks

**Comment by rajanadar** [comment]
good to hear
