### ISSUE TITLE
Supporting no authentication method for Vault Agent's use_auto_auth_token feature

### ISSUE THREAD

**Issue by farseeker** [rajanadar/VaultSharp#303]
**Describe the feature request or question**
There is no way to use VaultSharp without explicitly setting a vault token. If you write a custom authentication provider and set the Vault Token to blank, you still [trigger an exception](https://github.com/rajanadar/VaultSharp/blob/c18cc5f22cb4e34252b30a9b5ed62c6fbedb6427/src/VaultSharp/V1/AuthMethods/Custom/CustomAuthMethodLoginProvider.cs#L28).

This means that if you're using a Vault Agent with

```
cache {
  use_auto_auth_token = true
}
```

configured in the agent, there's no way to use VaultSharp with the agent. When `use_auto_auth_token`  is enabled, you talk to Vault via the agent's API and the agent will append the token to your request. This means that the client application has to do no authentication work at all.

**Link to the Vault API Docs that support this feature**
[The Vault Docs URL](https://developer.hashicorp.com/vault/docs/agent/caching#using-auto-auth-token)

**Additional context**
When you are working via the Vault CLI, you set your `VAULT_ADDR` to the agent and never set a `VAULT_TOKEN` variable to work with the vault API in this way.

I realise this is likely a niche case - why on earth would you go through the trouble of using vault agent and not just generate the vault token using an Agent sink, or some other way? And yet, here I am!

**Comment by rajanadar** [comment]
@farseeker We maybe mixing use cases here.

The auto-auth feature of vault agent is for vault agent to use a previously fetched vault toke via the agent, that it caches. This ensures that all future requests sent via the agent can pick up this internally cached vault token. Its a bundled feature where the flag, the initial login to get the token and cache it, and the subsequent logins are all within the agent context

I am not sure, if you can set that flag, and then open up postman and independently make a vault api call with no VAULT token. The call would succeed. Postman knows nothing about this.

The case is similar with VaultSharp. It has no knowledge of the agent in auto auth mode and is not going to try to peek inside it for the cached token etc. 

VaultSharp is intended for production applications that connect to systems via credentials. And we don't expect the multiple prod servers to have vault agents running in this auto auth mode.

Hopefully, the separation of concerns is clear. Let me know if any questions/concerns.
