### ISSUE TITLE
VaultSharp.V1.SecretsEngines.Database: The JSON value could not be converted to System.String. Path: $.data.default_ttl 

### ISSUE THREAD

**Issue by DamienDennehy** [rajanadar/VaultSharp#315]
**Describe the bug**
When calling "await vaultClient.V1.Secrets.Database.ReadRoleAsync("role_name");", a JsonException is thrown.

**VaultSharp Version**
1.13.0.1

**Vault Version**
1.13.2

**Does this work with Vault CLI?**
Yes

**Sample Code Snippet**
var databaseRole = await vaultClient.V1.Secrets.Database.ReadRoleAsync("role_name");

**Exception Details/Stack Trace/Error Message**
"System.Text.Json.JsonException: 'The JSON value could not be converted to System.String. Path: $.data.default_ttl | LineNumber: 0 | BytePositionInLine: 373.'"

**Any additional info**
This seems very similar to https://github.com/rajanadar/VaultSharp/issues/312

**Comment by rajanadar** [comment]
hi @DamienDennehy  let me have a look this weekend

**Comment by KyleZevenbergen** [comment]
Yes it seems vault returns ints for default_ttl and max_ttl while your library is expecting a string.

https://developer.hashicorp.com/vault/api-docs/secret/databases#parameters-7
