### ISSUE TITLE
Upgrade VaultSharp to latest JSON Nuget Package 10

### ISSUE THREAD

**Issue by therightstuff** [rajanadar/VaultSharp#32]
Currently receiving the following exception when attempting to read and write with NewtonSoft.Json 10 installed:
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))

Upon downgrading to 9.0.1 the issue is resolved.

EDIT: is there a way to specify a minimum installation / range? From the previous upgrade's commit it looks like all that was done was changing the numbers...

**Comment by rajanadar** [comment]
thanks @therightstuff for using the library.

There is some churn going on with JSON package and strong naming.
I am working through a clean 10.x of JSON package in the next release, common across all types of .NET.

This should be resolved or at least simplified at that moment.
