### ISSUE TITLE
An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by tanishagarg-sf** [rajanadar/VaultSharp#321]
**Describe the bug**
A one liner of what the bug is.
Error: ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**VaultSharp Version**
The version of VaultSharp package being used
VaultSharp.1.4.0.1

**Vault Version**
The version of Vault server being used

**Does this work with Vault CLI?**
Yes/No
Yes using curl commands

**Any additional info**
Helpful info

**Comment by konidev20** [comment]
Hey @tanishagarg-sf, 

I see that the remote certificate validation is failing in the HTTP Client being used by the VaultSharp library. The error is `The remote certificate is invalid according to the validation procedure.`

This usually occurs when the certificate is invalid of the certificate of the server is not in the trust store of the client machine. Can you provide more information about if the vault server in question has self-signed certificates or has Global CA signed certificates with valid intermediate certs?

Thanks,
@konidev20

**Comment by tanishagarg-sf** [comment]
Hi @konidev20 
I resolved this error by adding server CA root to Trust store. 
Can you please help with below ?

After this, i am seeing this error, [vaultsharp.core.vaultapiexception {"errors":["tls connection required"]}](https://stackoverflow.com/questions/76647138/vaultsharp-core-vaultapiexception-errorstls-connection-required), if you want i can paste details here as well. Thanks!

**Comment by konidev20** [comment]
Hey @tanishagarg-sf, 

It looks like a configuration issue. I will try to support you on StackOverflow. 

Request @rajanadar to close this issue.

**Comment by tanishagarg-sf** [comment]
Sure @konidev20 Please help [this](https://stackoverflow.com/questions/76646951/error-the-request-was-aborted-could-not-create-ssl-tls-secure-channel) second issue as well along, this one of my friend raised as i was not able to post. Thanks!

**Comment by konidev20** [comment]
Hey @tanishagarg-sf ,

Since your connection is going through a proxy. Have you checked if the connection between the proxy, I reckon the TLS connection is being terminated on the proxy. Ideally, from the proxy there must be another TLS connection to the Vault Server. 

I couldn't answer on StackOverflow.
