### ISSUE TITLE
How to read the root token and use it to call Vault APIs?

### ISSUE THREAD

**Issue by apetrut** [rajanadar/VaultSharp#324]
Hi,

I am trying to read the root token in a secure way using ReadSecretAsync but without passing the root token in the IAuthMethod.

```
AuthMethodInfo authMethod = new TokenAuthMethodInfo("123456789");
var vaultClientSettings = new VaultClientSettings("http://127.0.0.1:8200", authMethod);
var vaultClient = new VaultClient(vaultClientSettings);

var secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("auth/token/root");
var rootToken = secret.Data.Data["token"];
```

Is there a way to do that programatically and secure?

**Comment by rajanadar** [comment]
@apetrut  That's not a valid use case. KV Secret is used to store your own secrets.
Root token is a starting point and you need to have access.
