### ISSUE TITLE
Failed to look up namespace from the token

### ISSUE THREAD

**Issue by discofire** [rajanadar/VaultSharp#325]
**Describe the bug**
Unable to perform any calls (ReadSecretsAsync, ReadConfigAsync, etc...)

**VaultSharp Version**
1.13.0.1

**Vault Version**
1.12.0-dev1

**Does this work with Vault CLI?**
Yes

**Sample Code `Snippet**
```
string vaultToken = @"hvs.ahjsdkfjhasdkfjhaskdfjhksfLOTSOFSTUFFaksjdhfksajhf"; //This is not my actual token
var tokenAuthMethod = new TokenAuthMethodInfo(vaultToken);
var vaultClientSettings = new VaultClientSettings(this.environmentVariables["VAULT_URL"], tokenAuthMethod);
var vaultClient = new VaultSharp.VaultClient(vaultClientSettings);
vaultClient.V1.Secrets.KeyValue.V2.ReadConfigAsync();
```

**Exception Details/Stack Trace/Error Message**
`VaultApiException: {"errors":["error performing token check: failed to look up namespace from the token: no namespace"]}`

**Any additional info**

- I am able to login to the vault webpage using token authentication using the token
- I am able to login and retrieve secrets from the command line using the token
- I am able to login and retrieve secrets from a Python script using the hvac package with the same token.

I also tried version 1.13.0 (initially installed before upgrading hoping maybe a bug had been fixed).

**Comment by konidev20** [comment]
Hey @discofire, 

1. Do you have an enterprise version of HashiCorp Vault?
3. Can you give me an example of the `VAULT_URL` and `mountPoint` for the KV engine?

**Comment by konidev20** [comment]
Hey @discofire, 

1. Do you have an enterprise version of HashiCorp Vault?
3. Can you give me an example of the `VAULT_URL` and `mountPoint` for the KV engine?

**Comment by rajanadar** [comment]
closing due to no response.
