### ISSUE TITLE
Should this be hardcoded to v1?

### ISSUE THREAD

**Issue by traviisd** [rajanadar/VaultSharp#33]
https://github.com/rajanadar/VaultSharp/blob/380ce0c7e06437198932129669c53d79da8251a4/src/VaultSharp/VaultClient.cs#L52

**Comment by rajanadar** [comment]
thanks @traviisd 

VaultSharp 0.9.x is in progress, and I have redesigned the usage a bit, to accommodate changing versions of the Vault API, when Vault API actually gets there.

For now, it is about laying the ground work for version compatibility. And the library will take care of it. It'll make it very easy for the clients to specify the version of the api they want to interact with.
