### ISSUE TITLE
Allow skipping certificate validation

### ISSUE THREAD

**Issue by Sean-Brown** [rajanadar/VaultSharp#35]
In my dev environment I've been using self-signed certificates, which has caused problems with the HttpClient when it goes to do certificate validation. In this dotnet core project I've been able to circumvent this by modifying the HttpClient to skip certificate validation by setting
`ServerCertificateCustomValidationCallback = delegate { return true; }`

Note that in dotnet core setting `System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };` has no effect, so I have to modify the HttpClient creation directly.

This is the first library I've encountered in the project where the HttpClient construction is completely hidden, thus I can't give the HttpClient an HttpClientHandler which has that ServerCertificateCustomValidationCallback set.

If this is agreeable then I could even do the work and create a PR, just let me know your thoughts.

**Comment by Sean-Brown** [comment]
I just looked at the project more closely and it looks like the version of System.Net.Http that it's using does not have the `ServerCertificateCustomValidationCallback` property on the HttpClientHandler, so I'm not sure if what I ask is even possible.

**Comment by Sean-Brown** [comment]
Doesn't seem possible, going to explore other avenues

**Comment by rajanadar** [comment]
@Sean-Brown , this is not 100% clean, but here is a somewhat clunky way.
the next version of VaultSharp gives more control on the httpclient.

in this version, when you instantiate VaultClient using the factory method, there is an optional parameter called: `Action<HttpClient> postHttpClientInitializeAction = null`

You can supply your own action method to work on the HttpClient I create internally. (which is pretty much new HttpClient())
Once you have this client, you can access (reflect on HttpClient's base class private member called 'handler') its HttpClientHandler and deal with SSL settings as follows: 

```
httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
httpClientHandler.ServerCertificateCustomValidationCallback = 
    (httpRequestMessage, cert, cetChain, policyErrors) =>
{
    return true;
};
```

I haven't tried out this code, but it should work theoretically. Give it a shot and let me know.
As I said, it is not 100% clean, but it is something.

**Comment by rajanadar** [comment]
@Sean-Brown you can also see this for reference: https://github.com/rajanadar/VaultSharp/issues/11

**Comment by rajanadar** [comment]
@Sean-Brown the latest version of VaultSharp gives you hooks to control httphandler and client behaviors. let me know if any issues.
