### ISSUE TITLE
Will VaultSharp support .net8 as well?

### ISSUE THREAD

**Issue by techieenthuziast** [rajanadar/VaultSharp#356]
We intend to use VaultSharp for our .net6.0 apps, but in less than  3 months, we will be nearing End of Life for .net6 and will have to move to .net8. 

I do not see that there is any support for .net8 yet, so that will impact my decision of whether or not to use this for my applicaiton.

Please let me know if there is any future plan for .net8 support too.

**Comment by rajanadar** [comment]
first-class .net 8.0 support will be in the release next week.
