### ISSUE TITLE
Expose 'ca_chain' in CertificateData

### ISSUE THREAD

**Issue by groselt** [rajanadar/VaultSharp#36]
When calling `PKIGenerateDynamicCredentialsAsync`, I need to access `data.ca_chain`, but this is not exposed in `CertificateCredentials`.

Is it possible to add this to `CertificateData`?

**Comment by rajanadar** [comment]
yes @groselt . it'll be added as part of the 0.9.x in progress.

meanwhile, as a stop gap measure, you can use the generic readasync method to get the data in a raw dictionary form, including data.ca_chain.
