### ISSUE TITLE
Base ConnectionConfigModel Not Deserializing

### ISSUE THREAD

**Issue by treyhendon** [rajanadar/VaultSharp#363]
https://github.com/rajanadar/VaultSharp/blob/4f906a91681a2f1d265065d1c43c1f726602afe4/src/VaultSharp/V1/SecretsEngines/Database/ConnectionConfigModelJsonConverter.cs#L109

`PostgreSQLConnectionConfigModel` is properly being deserialized, but base properties from `ConnectionConfigModel` (i.e. connection_url, username, password) are null in the returned `Secret<ConnectionConfigModel>`.

**Comment by treyhendon** [comment]
I'm debugging through locally to try to find a solution.  Posting here in case you know a quick fix.  Thanks!

**Comment by treyhendon** [comment]
Any base property that didn't have a default in the class appears null, yes.  I do see the value in the `jsonString` from the API response.

**Comment by treyhendon** [comment]
As an example, here's what I get in `jsonString`:
```
{"allowed_roles":["api-sample","api-sample-migration"],"connection_details":{"connection_url":"postgresql://{{username}}:{{password}}@myserver.svc.cluster.local:5432/sample?sslmode=require","username":"myuser"},"password_policy":"","plugin_name":"postgresql-database-plugin","plugin_version":"","root_credentials_rotate_statements":[]}
```

I made a temp obj variable to capture the deserialzed value:
![image](https://github.com/user-attachments/assets/fdbcbfe1-9392-47c0-a670-605ac15d13b1)

**Comment by rajanadar** [comment]
thanks , that is very helpful. I think it is not a deser issue. The structure of the connection object between the write and read seems to be different.  The read structure is as follows: https://developer.hashicorp.com/vault/api-docs/secret/databases#sample-response

Thats the problem. I'll release a fix with the right model tomorrow.

**Comment by treyhendon** [comment]
Oh! I think I see it.  The JSON structure is slightly different than expected.

```
{
	"allowed_roles": [
		"api-sample",
		"api-sample-migration"
	],
	"connection_details": {
		"connection_url": "postgresql://{{username}}:{{password}}@myserver.svc.cluster.local:5432/sample?sslmode=require",
		"username": "myuser"
	},
	"password_policy": "",
	"plugin_name": "postgresql-database-plugin",
	"plugin_version": "",
	"root_credentials_rotate_statements": []
}
```

Looks like `ConnectionDetails` would hold `ConnectionUrl`, `Username`, `Password`, etc

**Comment by rajanadar** [comment]
@treyhendon  I prepared a local fix. Which version of .NET are you using? i'll give you a DLL for temp testing here, before releasing a nuget

**Comment by treyhendon** [comment]
I'm using .net 8. Thanks!

**Comment by rajanadar** [comment]
please use this dll and let me know.
[VaultSharp-1.17.5.1-For-Test-.NET 8.zip](https://github.com/user-attachments/files/17033795/VaultSharp-1.17.5.1-For-Test-.NET.8.zip)

**Comment by treyhendon** [comment]
I actually just pulled your master branch and was able to successfully test!  I'll download the dll and try that as well.  Thanks!

**Comment by rajanadar** [comment]
Ah cool. I forget that folks can easily build from the project as well.

**Comment by treyhendon** [comment]
I can also confirm the .net 8 dll is a success.  Thanks again for such a quick response!

**Comment by rajanadar** [comment]
Cool, good to hear. I'll publish the official nuget in a day. It's my bad, I overlooked the read Api response model.

**Comment by rajanadar** [comment]
@treyhendon , here it is: https://www.nuget.org/packages/VaultSharp/1.17.5.1
