### ISSUE TITLE
PKI Secrets Engine - return raw cert data, incl. revocation date

### ISSUE THREAD

**Issue by joevanwanzeeleKF** [rajanadar/VaultSharp#366]
Currently, the  .V1.Secrets.PKI.ReadCertificateAsync(serial, mountpoint) method returns a "CertificateData" object, that only includes the format, content, and serial number.  The API endpoint returns the  revocation_time, revocation_date, and issuer_id as well.  

Without these values it is not possible (afaik) to check when a cert was revoked.

If instead we returned a "CertificateDataRaw" object, those values would be included.

Is there a good reason for excluding these values from the response?

My request is to have those values included in the response.

Thanks

**Comment by rajanadar** [comment]
makes sense @joevanwanzeeleKF .
i have implemented it.

let me know how urgent is the package to you. I'll publish a new release. Else in a week or so.

**Comment by joevanwanzeeleKF** [comment]
I appreciate that!  Sooner would be great (pre-release?), but a week would be fine if you need it.

**Comment by rajanadar** [comment]
This weekend
