### ISSUE TITLE
Default Microsoft SQL port

### ISSUE THREAD

**Issue by bardagadvergur** [rajanadar/VaultSharp#38]
The `MicrosoftSqlConfigureConnectionAsync` seem to default to the default SQL port of 1433. Using this connection string:
`"server=127.0.0.1;port=1402;user id=sa.....`
I get this error:
`Unable to open tcp connection with host localhost:1433`

I've tried a few different versions of the connection string but always the same error.

**Comment by rajanadar** [comment]
hi @bardagadvergur 

This maybe an inherent behavior of the Vault API MS SQL Backend. (which i think is a community supported backend for Vault)

VaultSharp doesn't dictate this connection string, and it just passes it along into the API.
