### ISSUE TITLE
Should the password in a UsernamePasswordCredentials instance be a SecureString?

### ISSUE THREAD

**Issue by pvandervelde** [rajanadar/VaultSharp#40]
The `UsernamePasswordCredentials` class stores the password part as a normal string. Would it not be more secure (if potentially a lot more inconvenient) to store the password as a [SecureString](https://msdn.microsoft.com/en-us/library/system.security.securestring%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)?

**Comment by rajanadar** [comment]
Yes @pvandervelde 

But I think VaultSharp is not the weakest link here. The consuming application & the downstream API would be. The downstream API needs a JSON value at which point, I have to convert it into a string anyways. Worst case, my POCOs with SecureString cannot be automatically serialized.

Having said that, I guess the password is used in LDAP and UserPass auth method. Let me know if it critically blocks your app, if the library doesn't use secure string.

**Comment by pvandervelde** [comment]
For the time being I've worked around it so it's fine. I just figured it would add another strength to the library.
