### ISSUE TITLE
Exception Message in C# Code : 404 NotFound. {"errors":[]} USING AppRoleAuthentication

### ISSUE THREAD

**Issue by bhupendrasinghnegi** [rajanadar/VaultSharp#42]
Hi I am receiving 404 NotFound. {"errors":[]} while using AppRoleAutherntication backend, please find the info below. I am passing valide approle id and secret id. I have tried this with multiple policy options its not working. Let me know if anywhere i am doing it worngly.

I am running this against my local vault installation

# Setting Vault Dev Server
#Setting VAULT_ADDR
set VAULT_ADDR=http://127.0.0.1:8200

vault secrets disable secret 
vault secrets enable -version=1 -path=secret kv

#Enable AppRole auth method
vault auth enable approle

#Create new policy [jenkins]
vault policy write jenkins "C:\Manager\Suming\2018\App1 Cloud Migration\Vault Policies\jenkins-pol.hcl"

#Create a new AppRole [jenkins] 
vault write auth/approle/role/jenkins secret_id_ttl=10m token_num_uses=10 token_ttl=20m token_max_ttl=30m secret_id_num_uses=40

#Attach policy [jenkins] to [jenkins] AppRole
vault write auth/approle/role/jenkins policies="jenkins"

#Read the [jenkins] AppRole to verify if [jenkins] policy is attached
vault read auth/approle/role/jenkins

#Get Role ID for [jenkins] approle
vault read auth/approle/role/jenkins/role-id

#Get Secret ID for [jenkins] approle
vault write -f auth/approle/role/jenkins/secret-id

#Creating Secret [TestKey=TestValue] at secret/aws/us-east-1/cd/servicing/sandbox
vault kv put secret/aws/us-east-1/rcd/servicing/sandbox TestKey=TestValue

# **Vault Policy** : jenkins-pol.hcl (just for testing, not relation to Jenkins at all)

path "secret/*" {
  capabilities = ["create","read"]
}

path "auth/approle/login" {
  capabilities = [ "create", "read" ]
}

path "secret/aws/us-east-1/cd/servicing/sandbox/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

path "sys/auth/approle" {
  capabilities = [ "create", "read", "update", "delete", "sudo" ]
}

path "sys/auth/approle/*" {
  capabilities = [ "create", "read", "update", "delete" ]
}

path "auth/approle/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

path "sys/policy/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

# **Exception Message in C# Code** : 404 NotFound. {"errors":[]}

# Code 
```
try
{
secret =
VaultClient
.ReadSecretAsync(fullSecretPath)
.GetAwaiter()
.GetResult();
}
catch(Exception exception)
{
throw
new InvalidOperationException
(
string.Format
(
CultureInfo.InvariantCulture,
"Unable to read secret {0} from vault store",
fullSecretPath
), 
exception
);
}
SecretCache.Add(fullSecretPath, secret);
```

**Stack Trace**
   at VaultSharp.DataAccess.HttpDataAccessManager.<MakeRequestAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.VaultClient.<MakeVaultApiRequest>d__225`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.VaultClient.<ReadSecretAsync>d__207.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LLB.Secrets.HashicorpVaultStore.ReadSecretFromStore(SecretMappingElement secretMappingElement) in C:\Projects\LLB\Cloud\Core Libraries\Secrets\Vault\Secrets\1.0\LLB.Secrets\HashicorpVaultStore.cs:line 107

**Comment by rajanadar** [comment]
@bhupendrasinghnegi  I normally get this error when my secret-id has expired. So everything is valid, except the password has expired. Can you please try again with the latest VaultSharp 0.10.4xxx and let me know if this still happens?
