### ISSUE TITLE
"400 BadRequest. {\"errors\":[\"unknown role: mssqlrole\"]}\n"

### ISSUE THREAD

**Issue by AnandJillawar** [rajanadar/VaultSharp#43]
I am trying to generate dynamic credentials for my MSSQL using https://github.com/rajanadar/VaultSharp#mssql-secret-backend

But every time I am getting below error
"400 BadRequest. {\"errors\":[\"unknown role: mssqlrole\"]}\n"

mssqlrole is my rolename

How to get rid of this issue? @rajanadar

**Comment by rajanadar** [comment]
@AnandJillawar you need to configure the role before you can generate dynamic credentials.
e.g. See this: https://www.vaultproject.io/docs/secrets/mssql/index.html
They configure a role named 'readonly'

**Comment by AnandJillawar** [comment]
@rajanadar 
Yes .. while configuring role called mssqlrole i am getting below error...

**400 BadRequest. {"errors":["Error validating connection info: failed to send SQL Batch: write tcp [::1]:***********:1433: wsasend: An existing connection was forcibly closed by the remote host."]}**

How to fix this issue?
