### ISSUE TITLE
Allow authentication with a wrapped token

### ISSUE THREAD

**Issue by pvandervelde** [rajanadar/VaultSharp#44]
Given that Vault allows creating wrapped tokens it should be possible to use a wrapped token for the initial authentication methods like AppRole and Token. That way it is easier and safer to provide the token to the consuming application.

In order to use a wrapped token as the authentication token the library would have to unwrap the token before using it to authenticate. According to the documentation this can be done by sending a POST request to the `/v1/sys/wrapping/unwrap` path with the token to be unwrapped in the x-vault-token header and nothing in the body. Unfortunately the `VaultClient` always creates a body at the moment even if no token is provided:

https://github.com/rajanadar/VaultSharp/blob/380ce0c7e06437198932129669c53d79da8251a4/src/VaultSharp/VaultClient.cs#L494

In this case Vault will return an error indicating that it was expecting a token in the body.

**Comment by ORuban** [comment]
You should be able to do this  by using `TokenAuthenticationInfo`:

```
// Uri vaultAddr;
IAuthenticationInfo tokenAuthenticationInfo = new TokenAuthenticationInfo(yourWrappedToken);
var vaultClient = VaultSharp.VaultClientFactory.CreateVaultClient(vaultAddr, tokenAuthenticationInfo);
var response = await vaultClient.UnwrapWrappedResponseDataAsync(null);
```

**Comment by pvandervelde** [comment]
Awesome. Just as a side note, I think for this to work the wrapped token needs to allow at least 2 acceses, one for the login and one to unwrap the token.
