### ISSUE TITLE
GitHub login, get calling token info, renew calling token and Version 10.4 Documentation

### ISSUE THREAD

**Issue by pnquest** [rajanadar/VaultSharp#49]
The new version looks great, and will likely eliminate several hacks we had to put in place to use this library, but the fact that the API has basically completely changed, combined with the fact that there is now 0 documentation makes updating a bit of a hard sell.

Are there any plans to add back documentation of the new API in the near future?

**Comment by rajanadar** [comment]
Thanks @pnquest for using the library.

The proper documentation with samples should be up by EOW. And hopefully the Library is very intuitive to use from now on.

Meanwhile, you can refer to https://github.com/rajanadar/VaultSharp/blob/master/test/VaultSharp.Samples/Program.cs for the short term. 

A couple more days and the proper documentation should be up.

Meanwhile, if there are specific things you are looking for, please let me know and I can send over some samples.

**Comment by pnquest** [comment]
@rajanadar Thanks!

A couple more critical things for my use case that I was wondering:

* How do I authenticate using Github auth now
* How do I access information about the Calling token now? (there used to be a method called `GetCallingTokenAsync`)
* How do I renew the calling token? (formerly `RenewCallingTokenAsync`)

**Comment by rajanadar** [comment]
@pnquest adding all 3 in 0.10.4001. GitHub is done. Other 2 in progress.

**Comment by rajanadar** [comment]
@pnquest all of the above have been added.
