### ISSUE TITLE
Was having a deadlock problem with MVC web application and using AppID Auth

### ISSUE THREAD

**Issue by dstrieby** [rajanadar/VaultSharp#5]
Hi,
Thanks for your library.  I have attached a patch of the changes I needed to make to workaround a problem I was having when trying to load a secret from an MVC web application.  Our application would experience a deadlock after receiving the response to the /v1/auth/app-id/login request.

All I did was to propagate the continueAsyncTasksOnCapturedContext parameter down through the Auth.  I only made changes needed to fix the AppIdAuthentication.  I expect you will want to propagate that parameter to all the other auth providers as well.

Thanks again and Have fun!
[patch.zip](https://github.com/rajanadar/VaultSharp/files/388725/patch.zip)

-dstrieby@springcm.com <Dave Strieby>

**Comment by rajanadar** [comment]
thank you @dstrieby for taking the time to send a patch and for using the library.

i'll absorb this change as part of the next release i am working on.

**Comment by rajanadar** [comment]
@dstrieby i have made the fix for all the auth providers.
the 0.6.1 merge to master should take care of this.
