### ISSUE TITLE
"400 BadRequest. {\"errors\":[\"unknown role: mssqlrole\"]}\n"

### ISSUE THREAD

**Issue by AnandJillawar** [rajanadar/VaultSharp#50]
@rajanadar 
Regarding issue https://github.com/rajanadar/VaultSharp/issues/43
Yes .. while configuring role called mssqlrole i am getting below error...

400 BadRequest. {"errors":["Error validating connection info: failed to send SQL Batch: write tcp [::1]:*******:1433: wsasend: An existing connection was forcibly closed by the remote host."]}

How to fix this issue?

**Comment by rajanadar** [comment]
Does it work in the cli?

Related: https://github.com/hashicorp/vault/issues/1852

**Comment by rajanadar** [comment]
Please let me know if the CLI behaves properly.

**Comment by AnandJillawar** [comment]
Hello,
It is not working in **cli** also .... I am getting same error.

**Comment by AnandJillawar** [comment]
Hello,
Actually i am getting below error while using CLI ....

**Error reading database/creds/myrole: Error making API request.
URL: GET http://127.0.0.1:8200/v1/database/creds/myrole
Code: 500. Errors:
* 1 error occurred:
* failed to find entry for connection with name: "master"**

**Comment by alvonellos** [comment]
I have this issue also.
