### ISSUE TITLE
Write to KV v1 secrets engine?

### ISSUE THREAD

**Issue by ronnyek** [rajanadar/VaultSharp#52]
Greetings..

I'm experimenting with the library and noticing that it seems like the only place I've found with any secrets engine, seems to be calling WriteAsync on the cubbyhole secrets engine. If I attempt to get intellisense with the v1 kv secrets engine, there are only two methods, both of which are read. 

Am I missing something?

**Comment by rajanadar** [comment]
@ronnyek Thanks for using the library.

The kv secrets engine (v1 and v2) will get the Write method in a day.
Please expect an updated VaultSharp in 1-2 days.
