### ISSUE TITLE
How to create simple wrapped request?

### ISSUE THREAD

**Issue by darkonejr** [rajanadar/VaultSharp#53]
Can you give an example of how to do a simple wrapped data request, (i.e. a post to `/sys/wrapping/wrap`)?

**Comment by rajanadar** [comment]
Thanks @darkonejr. I am out this week. I'll come back and respond to you.

**Comment by rajanadar** [comment]
Working on this today and tomorrow.

**Comment by rajanadar** [comment]
this is now implemented in VaultSharp 0.11.1002
Please see https://github.com/rajanadar/VaultSharp/blob/master/test/VaultSharp.Samples/Program.cs#L1089 for sample usage.
