### ISSUE TITLE
How to write a TOTP ?

### ISSUE THREAD

**Issue by clintnetwork** [rajanadar/VaultSharp#54]
Hello i would like to store a new a TOTP, is it possible with this library ?

thanks

**Comment by rajanadar** [comment]
Thanks for using the library. Acked. Please expect an update in a day.

**Comment by rajanadar** [comment]
@clintnetwork  Please the docs at https://github.com/rajanadar/VaultSharp/blob/master/README.md#totp-secrets-engine to see how you can generate TOTP code using Vault.
