### ISSUE TITLE
KeyValue Secrets Engine WriteSecret Doesn't Return Output

### ISSUE THREAD

**Issue by pnquest** [rajanadar/VaultSharp#63]
I have been using version `0.6.4` of this library for quite some time now, and am now trying to upgrade to the latest version. I have a workflow that requires reading the response data from writing a secret. The equivalent call in the new API, `client.V1.Secrets.KeyValue.V1.WriteSecretAsync`, no longer returns any output it received. Would it be possible to add this back?

**Comment by rajanadar** [comment]
@pnquest does the Vault-api return the result as part of the write operation?

if not, then VaultSharp may also not do that. I am simply trying to model the API's behavior.
Also, can you do a "read" call following the write, to get your value?

**Comment by pnquest** [comment]
Yes, the api returns the result as part of the write operation. The reason that method returns output is because it's return type is `Task`, rather than `Task<Secret<Dictionary<string, object>>`, which is what it was in the version I specified above. 

This use-case may be somewhat unusual, but in our vault implementation there are some endpoints where a `POST` to an endpoint is needed to get the secret you require. A `GET` to the same endpoint does not give any results.
