### ISSUE TITLE
TLS enabled (certificate) not authenticated using VAULTsharp

### ISSUE THREAD

**Issue by kkwft** [rajanadar/VaultSharp#64]
hi

I m able to configure certificate authentication uing vault command prompt as well as ui
also able to read write secrets using the same
 but when i am trying to authenticate same certificate and private key using vault sharp it is unable to authenticate and throws unable to create ssl channel.

i have used same code provided by you for certificate authentication

can you please provide certificate authentication along with how to pass token and read write.

as i am unable to find any code using all fully working sample for certification and read write.

**Comment by kkwft** [comment]
i am using .net framework 4.5

**Comment by kkwft** [comment]
need its solution urgently... can anybody please help here. #

**Comment by kkwft** [comment]
need its solution urgently... can anybody please help here. #

**Comment by rajanadar** [comment]
@kkwft Isn't this working for you?
https://github.com/rajanadar/VaultSharp/blob/master/README.md#certificate-tls-auth-method

**Comment by kkwft** [comment]
Nope its unable to create SSL channel..
 I have added certificate to trusted root certification..

Can you please provide some working example with full code

As we also need root token Authorization for login along with certificate
authentication...

**Comment by kkwft** [comment]
So u mean after certification authentication it won't ask for login token it will automatically get authented and start read write process ??

**Comment by kkwft** [comment]
Also the code provided by u doesn't have any option to add private key of certificate..

**Comment by kkwft** [comment]
Need some method which can take certificate file and private key path both as input..open SSL nuget already providing that  but it's unable to create SSL channel using vaultsharp

**Comment by rajanadar** [comment]
certificatePath is the path to your pfx. You can also load it from your cert store. Doesn't matter how.

Ultimately your pfx certificate needs to be in the clientCertificate instance. That's all.

**Comment by rajanadar** [comment]
Yes, after certificate, it won't ask for any token. 

I think we are outside the realm of VaultSharp and talking about how to load a private key in C# object.

Here are a few ways to load the certificate. 

https://stackoverflow.com/questions/9141198/how-to-programmatically-import-a-pfx-with-a-chain-of-certificates-into-the-certi 

Couple more things. Cert file and private key are not 2 separate things. The cert path is the path to your pfx file. 

Also what is the full stack trace?

**Comment by kkwft** [comment]
still unable to authenticate 


**Stack trace:**
The request was aborted: Could not create SSL/TLS secure channel.

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.AuthMethods.Cert.CertAuthMethodLoginProvider.<GetVaultTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValueSecretsEngineV2Provider.<ReadSecretAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by kkwft** [comment]
tried open ssl and other stuff still same
here is the code

ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol =
                SecurityProtocolType.Tls
                       | SecurityProtocolType.Tls11
                       | SecurityProtocolType.Tls12
                       | SecurityProtocolType.Ssl3;

                string certificateText = File.ReadAllText(@"c:\\Vault\\vaultcert1.pem");
                string privateKeyText = File.ReadAllText(@"c:\\Vault\\vaulkey123.pem");

                ICertificateProvider provider = new CertificateFromFileProvider(certificateText, privateKeyText);
                X509Certificate2 clientCertificate = provider.Certificate;

                IAuthMethodInfo authMethod = new CertAuthMethodInfo(clientCertificate);
                
                // Initialize settings. You can also set proxies, custom delegates etc. here.
                var vaultClientSettings = new VaultClientSettings("https://127.0.0.1:8200", authMethod);
                vaultClient = new VaultClient(vaultClientSettings);
                var path = "hello";
                var kv2Secret = await vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path);

**Comment by kkwft** [comment]
Still not working posted stack trace and code

**Comment by kkwft** [comment]
I am able to run the server from commndprompt as well as ui using same certificate and same key.
please help here.

**Comment by rajanadar** [comment]
@kkwft how are you doing https (SSL) on your local host? 127.0.0.1?
Maybe that is the problem.  Can you check http:// ?

**Comment by rajanadar** [comment]
Closing due to no response.
