### ISSUE TITLE
Okta - cannot authenticated

### ISSUE THREAD

**Issue by dillon-courts** [rajanadar/VaultSharp#65]
Hi,

I'm trying to authenticate with Okta with the following code:

```
IAuthMethodInfo authMethod = new OktaAuthMethodInfo("email@domain.com", "<password>");
var vaultClientSettings = new VaultClientSettings("<vault_addr>", authMethod);

IVaultClient vaultClient = new VaultClient(vaultClientSettings);

// Use client to read a v1 key-value secret.
VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.SecretData> kv2Secret = vaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync("local/test").Result;
```

This is returning an okta authentication error: {"errors":["Okta auth failed: HTTP Method: POST - URL: https://<okta_url>/api/v1/authn: - HTTP Status Code: 401, OKTA Error Code: E0000004, OKTA Error Summary: Authentication failed, OKTA Error Causes: []"]}

However, I am able to authenticate via postman just fine by doing a POST:

https://<vault_addr>/v1/auth/okta/login/email@domain.com and passing the password in as json in the body.

Any thoughts on this?

**Comment by rajanadar** [comment]
Hi @dillon-courts 

That is strange. VaultSharp sends the login request to your Vault server, which will do the /authn http call to Okta. It seems Okta is returning that error to your Vault Server.

Can you repeat your run with VaultSharp and capture a fiddler (or similar) http trace that goes from VaultSharp to your Vault server? Once you have that, do you see anything funky going on? Like, missing username in the URL, or escaping the at-the-rate-of' symbol etc.

Let me know

**Comment by dillon-courts** [comment]
I must have fat fingered something as this is working appropriately now. Thanks for the response!

**Comment by rajanadar** [comment]
Thanks for the confirmation
