### ISSUE TITLE
PKIReadCACertificateAsync does not exist

### ISSUE THREAD

**Issue by AbhiAgarwal192** [rajanadar/VaultSharp#69]
I am using vaultsharp version 0.11 and i dont see PKIReadCACertificateAsync method on vaultclient. 

I am referring PKI section of below document:

https://github.com/rajanadar/VaultSharp/blob/master/README-0.6.x.md

**Comment by rajanadar** [comment]
I'll add it to the next release.

**Comment by rajanadar** [comment]
@AbhiAgarwal192 Do you still need this functionality?

**Comment by AbhiAgarwal192** [comment]
@rajanadar Yes i need it. Thank you !!
