### ISSUE TITLE
Vault 0.6.x support?

### ISSUE THREAD

**Issue by fproulx-pbox** [rajanadar/VaultSharp#7]
@rajanadar I saw you changed the README, but I see zero code change on any branch since February. 

Are you confident 0.6.x is really coming soon ?

Is it purely incompatible or just not able to use newer features ?

**Comment by rajanadar** [comment]
hi @fproulx-pbox 

i have private repos, where i normally do my new version changes. and push them. i'll change remote later.

as for compatibility, VaultSharp 0.4.1 should be very very compatible with Vault 0.6.1

What does very very mean?

Vault pretty much works on a generic READ/WRITE API, which can be use to do any operation. All versions of Vault support this. Apart from that, this C# library adds a lot of strongly typed API access, and i have verified all of them to be working for 0.5.x of Vault.

For Vault 0.6.1, I haven't VERIFIED personally. Hence i am reluctant to write on my readme that it is surely compatible. but based on the Vault 0.6.1 changelog, i think it is 95% compatible.. its really missing just additive stuff like SQL Server backend, new App Role backend etc.

But the existing VaultSHarp 0.4.1 DLL should work for you with 0.6.1 as well, more than easily.

let me know if you find any issues.

and i expect VaultSharp 0.6.1 to be done, sometime in the second week of September.

**Comment by fproulx-pbox** [comment]
Awesome ! I truly appreciate your contribution to the community.

**Comment by rajanadar** [comment]
thanks @fproulx-pbox for using the library.

**Comment by rajanadar** [comment]
@fproulx-pbox 
 VaultSharp 0.6.4 is now live. cross-platform (.net standard 1,4), strongly named and parity with Vault 0.6.4
