### ISSUE TITLE
Generate the root certificate

### ISSUE THREAD

**Issue by Marusyk** [rajanadar/VaultSharp#70]
I'm going to use that package but I can't find how to generate the root certificate. Is there such functionality? 

I need follow [this guide](https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine) 

Thank you in advance.

**Comment by rajanadar** [comment]
Hi @Marusyk 

That functionality doesn't exist yet as a first-class method. I'll add it to the list of items for the next release.

**Comment by rajanadar** [comment]
btw @Marusyk , before implementing this feature, I want to check with you. 

Vault's documentation recommends that you have your Root Certificate outside of Vault. And only deal with intermediate-CA and leaf certificates in Vault. https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine#solution

Would you still need the Root CA generation ability in VaultSharp?

**Comment by Marusyk** [comment]
Hi @rajanadar 
Yeah, I do not need generate the root certificate anymore. For now this functionality is enoughю Thanks

**Comment by rajanadar** [comment]
Thanks for the confirmation.

**Comment by Marusyk** [comment]
@rajanadar Now I need possibility to revoke cert. How can I do that? 

Also after generation it would be nice to return expiration value

Thx
