### ISSUE TITLE
Provide the way to access the low-level Vault API (Polymath)

### ISSUE THREAD

**Issue by msvprogs** [rajanadar/VaultSharp#71]
I want to implement SSH key signing, which isn't a part of VaultSharp:
https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html#client-ssh-authentication

But all low-level API classes are internal, and I can't access them straightforwardly.
It would be great to be able to use Vault operations which aren't implemented in the high-level VaultSharp API.

**Comment by rajanadar** [comment]
@msvprogs Thanks for using the library.
Polymath is not supposed to be exposed to the clients. I would definitely like to take a feature request for this though. Can you please tell me the vault version you are using?

**Comment by msvprogs** [comment]
Ok, thanks for the answer. I'm using v1.1.0. It would be great to have this as a feature without dirty reflection hacks :)

**Comment by rajanadar** [comment]
Makes sense. I'll add this to the next set of items.
