### ISSUE TITLE
Possibility to remove expired certificates

### ISSUE THREAD

**Issue by Marusyk** [rajanadar/VaultSharp#79]
It would be nice to have possibility to remove expired certificates like in API

```
$ curl --header "X-Vault-Token: ..." \
       --request POST \
       --data '{"tidy_cert_store": true, "tidy_revoked_certs": true}' \
       https://127.0.0.1:8200/v1/pki_int/tidy
```

What do you think about it? I can prepare PR for that

**Comment by rajanadar** [comment]
i'll add the API @Marusyk

**Comment by Marusyk** [comment]
@rajanadar When? Like this [PR](https://github.com/rajanadar/VaultSharp/pull/76 ) in 4+ months?

**Comment by Marusyk** [comment]
@rajanadar When?

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping
