### ISSUE TITLE
Unknown fields exception from ReturnedLoginAuthInfo property

### ISSUE THREAD

**Issue by wavetylor** [rajanadar/VaultSharp#80]
We're trying to use the client like so:

```c#
IAuthMethodInfo authMethod = new GoogleCloudAuthMethodInfo(VaultAuthMountPoint, VaultRole, signJwt);
var vaultClientSettings = new VaultClientSettings(VaultUri, authMethod)
IVaultClient vaultClient = new VaultClient(vaultClientSettings);
var kvSecret = await vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync(VaultPath + "/path");
```

But this is always results in an exception: 
`VaultSharp.Core.VaultApiException : {"errors":["unknown fields: [\"ReturnedLoginAuthInfo\"]"]}`

We've managed to workaround it by forking and adding `[JsonIgnore]` to:
```c#
[JsonIgnore]
public AuthInfo ReturnedLoginAuthInfo { get; internal set; }
```
In src/VaultSharp/V1/AuthMethods/AbstractAuthMethodInfo.cs

Having a hard time imagining how this is working for anyone. Perhaps I've missed some basic settings. Tested against vault 0.11.4 and 0.11.6, using VaultSharp 1.11 and 1.11.1002.

Thanks!

**Comment by rajanadar** [comment]
I'll check this out.

**Comment by phenry20** [comment]
Any progress on this?
