### ISSUE TITLE
What about feature for KV "Delete Metadata and All Versions"

### ISSUE THREAD

**Issue by Marusyk** [rajanadar/VaultSharp#84]
Very useful feature is [Delete Metadata and All Versions
](https://www.vaultproject.io/api/secret/kv/kv-v2.html#delete-metadata-and-all-versions)

What do you thing about implement it in your package?

**Comment by rajanadar** [comment]
I'll triage it for vnext @Marusyk

**Comment by Marusyk** [comment]
@rajanadar ping
