### ISSUE TITLE
TLS auth is not working : {"errors":["client certificate must be supplied"]}

### ISSUE THREAD

**Issue by rahulmanasa** [rajanadar/VaultSharp#85]
//environment windows
 X509Certificate2 clientCertificate = null;
            X509Store store = new X509Store(StoreLocation.CurrentUser);
            store.Open(OpenFlags.ReadOnly);
            X509Certificate2Collection certificateList = store.Certificates.Find(X509FindType.FindBySubjectName, "subject name", false);

            if (certificateList.Count > 0)
            {
                clientCertificate = certificateList[0];
            };
            store.Close();
// got clientCertificate here, it has private key as well 

try
            {
                IAuthMethodInfo authMethod = new CertAuthMethodInfo(clientCertificate);
                var vaultClientSettings = new VaultClientSettings("endpoint:8200", authMethod);
                IVaultClient vaultClient = new VaultClient(vaultClientSettings);
                Secret<Dictionary<string, object>> secret = null;
                Task.Run(async () =>
                {
                     secret = await vaultClient.V1.Secrets.KeyValue.V1.ReadSecretAsync("dummy_app/dev/connection_strings");
                }).GetAwaiter().GetResult();

Above code is throwing error 

{"errors":["client certificate must be supplied"]}

Can you please help!

**Comment by rahulmanasa** [comment]
Need quicker response, can someone please help.
It seems cert and private key was available in the authmethod object. 
But VaultSharp is not passing it to vault while making the call.
Please help asap

Thanks,
Rahul Jain

**Comment by rahulmanasa** [comment]
no one is supporting vaultsharp community. 
There is no response.

**Comment by rajanadar** [comment]
@rahulmanasa  

That is quite strange. I am attaching the cert to the http request here.
https://github.com/rajanadar/VaultSharp/blob/master/src/VaultSharp/Core/Polymath.cs#L31

What version of .NET are you on?

**Comment by vadomlore** [comment]
I also faced with the same problem. curl works fine, but sdk report tls error (netcore2.2)
from secret storage. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: 
anyone still maintain this repo?

**Comment by david-castaneda** [comment]
im having the same problem.. anyone find a workaround?

**Comment by david-castaneda** [comment]
Found a fix for this:

So the certificate is not being attached when making a request to vault, or if it is being attached, vault does not like how the certificate is formatted. 

To fix this, turn your cert + key into pkcs12 format with the following command:

`openssl pkcs12 -export -out Cert.p12 -in your-cert.pem -inkey your-key.pem`

And then 

```dotnet
var certificate = new X509Certificate2(your-p12-bytes, your-pass);
```

**Comment by hoerup** [comment]
@david-castaneda 
When reading your solution my thought is to add a check for X509Certificate2.HasPrivateKey here: 
https://github.com/VaultSharp/VaultSharp/blob/master/src/VaultSharp/V1/AuthMethods/Cert/CertAuthMethodInfo.cs#L53

**Comment by rajanadar** [comment]
thanks @david-castaneda 

@hoerup , I have added the check for private key and also updated the docs to clearly mention @david-castaneda 's pointers.
