### ISSUE TITLE
VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync(path) throws exception with message {"errors":["1 error occurred:\n\t* permission denied\n\n"]} on v0.11.1001+

### ISSUE THREAD

**Issue by crimsonalba** [rajanadar/VaultSharp#86]
Hi,

I just upgraded to v0.11.1002 from I think the latest v0.10. 

I started getting ```{"errors":["1 error occurred:\n\t* permission denied\n\n"]}``` errors while using the VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync function. 

I am using an AppRole method of authentication, with the right values.

```
			var appRoleMethod = new AppRoleAuthMethodInfo(
				roleId: vaultConfiguration.VAULT_ROLE,
				secretId: vaultConfiguration.VAULT_SECRET);

			var clientSettings = new VaultClientSettings(vaultConfiguration.VAULT_ADDR, appRoleMethod);

			VaultClient = new VaultClient(clientSettings);
```

This was working previously, and I went back through the last 4 versions. It works correctly for the latest v0.10 version, the v0.11, v0.11.1000, but fails in both v0.11.1001 & v0.11.1002

Any ideas on what could have changed between 1000 and 1001? I am just reverting back to 0.11 for now.

**Comment by crimsonalba** [comment]
I think i found the problem?

Looks like commit 4b376024 Changed the KeyValueV1 / V2 constants from

```
        public const string KeyValueV2 = "secret";
        public const string KeyValueV1 = "kv";
```
To

```
        public const string KeyValueV1 = "secret";
        public const string KeyValueV2 = "kv";
```

But that seems to be erroneous?

**Comment by GrononS** [comment]
> I think i found the problem?
> 
> Looks like commit [4b37602](https://github.com/rajanadar/VaultSharp/commit/4b376024c4b6b7950b600b79846413d48ddb30ba) Changed the KeyValueV1 / V2 constants from
> 
> ```
>         public const string KeyValueV2 = "secret";
>         public const string KeyValueV1 = "kv";
> ```
> 
> To
> 
> ```
>         public const string KeyValueV1 = "secret";
>         public const string KeyValueV2 = "kv";
> ```
> 
> But that seems to be erroneous?

:(
I wasted hours because I use the default mountPoint for the secret and the default is now incorrect. 
I had to remove the mount point from my path and specify the correct one in the mountPoint parameter to keep the default mountPoint from killing the query :(

Thank you crimsonalba for catching because I would have undoubtedly wasted more time trying to figure out why it no longer worked.

I had to change this:
`KeyValue.V2.ReadSecretAsync("secret/database-definitions/test");`

to this:
`KeyValue.V2.ReadSecretAsync("database-definitions/test", null, "secret");`

**Comment by rajanadar** [comment]
Oh oh. I am sorry folks for the mix-up there.

I'll fix this in the coming version. Silly mistake.

**Comment by LukaszT-MGSC** [comment]
I'm using v 1.7.0.4 and this happened to me :) comment above helped me resolve problem @GrononS

**Comment by suehshtri** [comment]
2026-Feb-23, using VaultSharp 1.17.5.1,  I ran into a similar need to specify 
ReadSecretAsync<Dictionary<string, object>>(credentialPath, null, "secret");
Calling the shorter override resulted in PermissionDenied.
