### ISSUE TITLE
Login Method Unavailable

### ISSUE THREAD

**Issue by MikeL9286** [rajanadar/VaultSharp#89]
The VaultSharp client abstracts the need to 'login' and fetches its own token on the first request... but when the token expires, it does not attempt to fetch a new one.

I'm unable to find an exposed 'login' method and trying to call Renew with an expired token results in a 403 from the server.

The only work around I've found is to initialize a new instance of the client but I doubt that's the intended/recommended flow. What am I missing here?

I'm using version 0.11.1002 of the client in a .NET Core 2.1 application.

-ps- I'm using the cert auth method.

**Comment by seif** [comment]
@MikeL9286 the library doesn't renew the token automatically for you, we've had to startup a background thread on successful login that will try to renew the token in LeaseDuration/2 via calling RenewSelf.

**Comment by rajanadar** [comment]
@seif  is correct. 

I don't intend for the library to keep tracking of token lifetime OR expiry signals, and auto-renew it.

Also, initializing a new instance of Vault-Client is 100% fine. It is not expensive at all and is just an object initialization. In fact, that can actually re-initiatize the auth-info's lazy method to fetch the Vault token, and hence you'll get a new token.
