### ISSUE TITLE
Doesn't seem to work when web application has httpRuntime.targetFramework > 4.0

### ISSUE THREAD

**Issue by arfan-r** [rajanadar/VaultSharp#90]
I've created simple Asp.net application targeting 4.7.2 framework and added VaultSharp 0.11.0 project to solution in order to test/debug write and read Api calls. Please find below the code snippet.
```
VaultClientSettings s = new VaultClientSettings("VAULT_SERVER_WITH_PORT", new TokenAuthMethodInfo("TOKEN"))
{
	ContinueAsyncTasksOnCapturedContext = true
};

IVaultClient VaultClient = new VaultClient(s);
Guid guid = new Guid("CF7D2BCE-8577-4E79-91C0-F0A8BA63A926");				
var data = new Dictionary<string, object>
{
	{"Number", "12345678"},
};

VaultClient.V1.Secrets.KeyValue.V2.WriteSecretAsync($"Data/{guid.ToString()}", data).Wait();
var readData = VaultClient.V1.Secrets.KeyValue.V2.ReadSecretAsync($"Data/{guid.ToString()}").Result;
```
My web application has following settings in the web.config.

```
...
<system.web>
    <compilation debug="true" targetFramework="4.7.2"/>
    <httpRuntime targetFramework="4.7.2"/>    
...
```

Now the issue is I don't get response back when tries to write the data onto Vault with above web.config. Debugging the code revealed Request gets lost (seems deadlock) when httpClient sends the request at 
```
var httpResponseMessage = await _httpClient.SendAsync(httpRequestMessage).ConfigureAwait(VaultClientSettings.ContinueAsyncTasksOnCapturedContext); // Line 168 in VaultSharp.Core.Polymath
```
**Note:** The problem only appears when `targetFramework` attribute in the `httpRuntime` element of my application web.config is > 4.0 and my understanding is, not setting httpRuntime.targetFramework to latest will result running application in quirks mode.

There is no issue at all in writing/reading from Vault when `targetFramework` attribute in the `httpRuntime` element of my application web.config is not present (which means it takes default 4.0) or set to 4.0 and `targetFramework` attribute in the `compilation` element is 4.7.2

Please let me know if you need anymore details.

Thanks

**Comment by rajanadar** [comment]
@arfan-r  

Are you sure, you are not hitting this issue?

https://stackoverflow.com/questions/15021304/an-async-await-example-that-causes-a-deadlock
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d

Meanwhile, I'll check the difference in behavior between 4.0 and 4.7.2

Let me know.

**Comment by rajanadar** [comment]
@arfan-r  are you still hitting this?
