### ISSUE TITLE
Enterprise Namespace Support

### ISSUE THREAD

**Issue by droach282** [rajanadar/VaultSharp#91]
Greetings,

I'm trying to use VaultSharp against an instance of VaultSharp enterprise, where we have a namespace assigned by the local vault admins in our company.  I'm getting the following response when I try to log in to the vault with an app role auth method:

`One or more errors occurred. ({"errors":["invalid role ID"]}`

I've verified that the role ID is correct, so I'm guessing that VaultSharp is trying to log into the root namespace (where the role ID _would_ be invalid) instead of our namespace.  But I can't see any way to specify the namespace in VaultSharp.  Am I missing something?

Thanks in advance!

**Comment by matthewreiter** [comment]
You can specify the namespace by adding the X-Vault-Namespace header like this:
`var clientSettings = new VaultClientSettings(VaultUrl, vaultAuthMethod)
{
    BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
    {
        httpRequestMessage.Headers.Add("X-Vault-Namespace", VaultNamespace);
    }
};`

**Comment by rajanadar** [comment]
thanks @matthewreiter . Merged the PR.

@droach282  Please let us know if the workaround doesn't work for you. I'll publish @matthewreiter 's changes soon as well.
