### ISSUE TITLE
namespaces are not supported by vaultsharp

### ISSUE THREAD

**Issue by rahulmanasa** [rajanadar/VaultSharp#92]
How to authenticate to /or retrieve secrets from a "namespace".
It seems vaultsharp always communicates to **root** namespace.

Thanks,
Rahul Jain

**Comment by matthewreiter** [comment]
You can specify the namespace by adding the X-Vault-Namespace header like this:
```
var clientSettings = new VaultClientSettings(VaultUrl, vaultAuthMethod)
{
    BeforeApiRequestAction = (httpClient, httpRequestMessage) =>
    {
        httpRequestMessage.Headers.Add("X-Vault-Namespace", VaultNamespace);
    }
};
```

**Comment by rajanadar** [comment]
thanks @matthewreiter .
Please let me know if that works for you @rahulmanasa  ?

**Comment by rahulmanasa** [comment]
> thanks @matthewreiter .
> Please let me know if that works for you @rahulmanasa ?

yes - thank you!

Regards,
Rahul Jain
rahulmanasa

**Comment by rajanadar** [comment]
Btw, the latest version of vaultsharp has first class support for namespaces. You can specify it in the settings and don't need to in the beforeapirequestaction anymore @rahulmanasa
