### ISSUE TITLE
Handle vault session token TTL

### ISSUE THREAD

**Issue by nemmyam** [rajanadar/VaultSharp#93]
Currently I don't see any way of handling the renewal of a vault token and respecting the TTL after authentication.
What can currently be done in order to renew the token after getting an auth error when the TTL has passed other than restarting the whole process?
I'm using the KubernetesAuthMethodInfo if it makes a difference.
Thanks

**Comment by rajanadar** [comment]
I don't know what you mean by restarting the whole process.

If the token has expired, then all you need to do is reinitialize your Vault-Client with the KubernetesAuthInfo again. 

If it helps, I can provide an explicit method on Vault Client to set the vault token again, but I don't plan to add any timer or auto-renewal logic in the library. Let me know.

**Comment by nemmyam** [comment]
If it's possibile to know the given TTL of a token upon signup then adding a flag which will set a timer to renew the token just before the token expires will be very useful! 

if it's not possibile to know the TTL then the client could recognize the token failure when the TTL is due and automatically set a new token and resend the secret request again.

Otherwise, the current behavior is a bit frustrating when the client stops working due to unauthorized access all of a sudden.
