### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by seif** [rajanadar/VaultSharp#95]
@rajanadar hey, looks like you are busy as there are a couple of pull requests since May. Will you come back anytime soon? could any of previous contributors be interested in helping out (I can help out, but haven't really contributed to this repo yet)?

**Comment by rajanadar** [comment]
Had some family emergency for 2-3 months. Back now. Apologize for the radio silence.
I'll start picking up the items this week.

**Comment by seif** [comment]
Thanks @rajanadar , hope all if sorted with family and welcome back :) 

I still encourage you to try to get more contributors to the project so people can help you out.
