### ISSUE TITLE
Is there an API call for UndeleteSecret?  

### ISSUE THREAD

**Issue by PaulWendt** [rajanadar/VaultSharp#96]
I'm looking to Delete and possibly Undelete a secret later on.  Is there an API support for this?  Anyone know of an alternate plan for how I can get this done?  The only recourse I have so far is to issue commands from the command-prompt, which is obviously less than ideal.

Thank you!

**Comment by hoerup** [comment]
Is it this API call you refers to ? https://www.vaultproject.io/api-docs/secret/kv/kv-v2/#undelete-secret-versions

**Comment by rajanadar** [comment]
@PaulWendt  can you please confirm the API you need? we will get started on the solution.
