### ISSUE TITLE
Docs: VaultSharp and failover

### ISSUE THREAD

**Issue by hoerup** [rajanadar/VaultSharp#98]
I am trying to figure out if VaultSharp has built-in client-side failover either by supporting multiple endpoint URI's or by supporting roundrobin DNS.

It doesn't say anything about it in docs, but from what I can see in code it doesn't seem to support it.

**Comment by rajanadar** [comment]
No @hoerup 

VaultSharp doesn't have such built-in multiple URI support. It works off a single URL that you provide. Any sort of fail-over etc. needs to be done by you. 

You are free to instantiate a new instance of VaultClient with a different URI.

**Comment by hoerup** [comment]
Ok thanks. You might want to add this comment to README.md

**Comment by rajanadar** [comment]
added it clearly to docs.
