### ISSUE TITLE
Add Disposable to VaultClient (and PolyMath)

### ISSUE THREAD

**Issue by hoerup** [rajanadar/VaultSharp#99]
Deep inside VaultClient there is a Disposable HttpClient instance, but via normal usage, there is now way to force a Dispose of that client object.

**Comment by ushadayalan** [comment]
Is this code released? I have version 0.11.1002.0, but don't see the disposable implementation

**Comment by Marusyk** [comment]
No, it is not released

**Comment by ushadayalan** [comment]
Can you please release a new version with this change , would be really helpful,

Thank you !!

**Comment by Marusyk** [comment]
Sorry, I can't, I don't own this library

**Comment by rajanadar** [comment]
please see #100 

Lets discuss there.
